-- =============================================================================
-- Tabla  : adm_seg_rol_permiso   (abrev: rope)
-- Permisos otorgados a cada rol (N:M).
-- =============================================================================
create table adm_seg_rol_permiso (
    rol_permiso_id      number generated by default on null as identity,
    rol_id              number         not null,
    permiso_id          number         not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_rope primary key (rol_permiso_id),
    constraint fk_adm_rope_rol foreign key (rol_id) references adm_seg_rol (rol_id) on delete cascade,
    constraint fk_adm_rope_per foreign key (permiso_id) references adm_seg_permiso (permiso_id) on delete cascade,
    constraint uk_adm_rope_rol_permiso unique (rol_id, permiso_id)
);

-- (rol_id ya está indexado por uk_adm_rope_rol_permiso)
create index idx_adm_rope_permiso_id on adm_seg_rol_permiso (permiso_id);

comment on table adm_seg_rol_permiso is 'Permisos por rol. Abrev: rope';
comment on column adm_seg_rol_permiso.rol_permiso_id     is 'Identificador técnico (PK, identity)';
comment on column adm_seg_rol_permiso.rol_id             is 'Rol (FK adm_seg_rol)';
comment on column adm_seg_rol_permiso.permiso_id         is 'Permiso otorgado al rol (FK adm_seg_permiso)';
comment on column adm_seg_rol_permiso.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_seg_rol_permiso.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_seg_rol_permiso.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_seg_rol_permiso.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
