-- =============================================================================
-- Tabla  : adm_aud_cambio   (abrev: cam)
-- Historial de cambios de datos de TODAS las apps (maestros y configuración).
-- La llenan los triggers trg_<app>_<abrev>_aiud generados con
-- adm_aud_cambio_utl.generar_trigger. Una fila por registro modificado.
-- Solo inserción: no lleva modificado_por/fecha_modificacion; update y delete
-- están bloqueados por trg_adm_cam_bud (salvo la purga por retención).
-- Alto volumen: identity cache 1000. cambios es CLOB con is json (19c+).
-- =============================================================================
create table adm_aud_cambio (
    cambio_id           number generated by default on null as identity (cache 1000),
    app_codigo          varchar2(10)   not null,
    tabla               varchar2(128)  not null,
    registro_id         number         not null,
    registro_padre_id   number,
    empresa_id          number,
    operacion           varchar2(1)    not null,
    cambios             clob           not null,
    usuario             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha               timestamp with local time zone default on null systimestamp not null,
    apex_app_id         number,
    apex_pagina_id      number,
    apex_sesion_id      number,
    transaccion_id      varchar2(100),
    modulo              varchar2(100),
    constraint pk_adm_cam primary key (cambio_id),
    constraint ck_adm_cam_operacion check (operacion in ('I','U','D')),
    constraint ck_adm_cam_cambios_json check (cambios is json)
);

create index idx_adm_cam_tab_reg_fecha on adm_aud_cambio (tabla, registro_id, fecha);
create index idx_adm_cam_fecha         on adm_aud_cambio (fecha);
create index idx_adm_cam_tab_padre     on adm_aud_cambio (tabla, registro_padre_id);

comment on table  adm_aud_cambio                   is 'Historial de cambios de datos (auditoría en JSON). Abrev: cam';
comment on column adm_aud_cambio.cambio_id         is 'Identificador técnico (PK, identity)';
comment on column adm_aud_cambio.app_codigo        is 'Código de la app dueña de la tabla (ADM, ERP…)';
comment on column adm_aud_cambio.tabla             is 'Tabla auditada, en mayúsculas';
comment on column adm_aud_cambio.registro_id       is 'Valor de la PK del registro modificado';
comment on column adm_aud_cambio.registro_padre_id is 'PK del registro padre (ej. usuario de un rol asignado); null si no aplica';
comment on column adm_aud_cambio.empresa_id        is 'Empresa del registro, si la tabla tiene empresa_id';
comment on column adm_aud_cambio.operacion         is 'I=Alta, U=Modificación, D=Eliminación';
comment on column adm_aud_cambio.cambios           is 'JSON: [{"col","antes","despues"}] solo con las columnas que cambiaron; en D la fila completa';
comment on column adm_aud_cambio.usuario           is 'Usuario que hizo el cambio (APP_USER o usuario de BD)';
comment on column adm_aud_cambio.fecha             is 'Fecha y hora del cambio';
comment on column adm_aud_cambio.apex_app_id       is 'Aplicación APEX desde la que se hizo; null fuera de APEX';
comment on column adm_aud_cambio.apex_pagina_id    is 'Página APEX desde la que se hizo';
comment on column adm_aud_cambio.apex_sesion_id    is 'Sesión APEX';
comment on column adm_aud_cambio.transaccion_id    is 'Transacción de BD: agrupa los cambios hechos juntos';
comment on column adm_aud_cambio.modulo            is 'Módulo de la sesión de BD (programa, job o página que ejecutó el cambio)';
