-- =============================================================================
-- Tabla : adm_aud_login
-- App   : adm | Módulo: aud (Auditoría)
-- Desc  : Bitácora de intentos de inicio de sesión (exitosos y fallidos).
-- =============================================================================
create table adm_aud_login (
    login_id            number generated by default on null as identity,
    username            varchar2(100)  not null,
    resultado           varchar2(20)   not null,
    apex_app_id         number,
    ip_cliente          varchar2(50),
    fecha               timestamp      default on null systimestamp not null,
    constraint pk_adm_aud_login primary key (login_id),
    constraint ck_login_resultado check (resultado in ('OK','PASSWORD_INVALIDO','USUARIO_NO_EXISTE','BLOQUEADO','INACTIVO','SIN_ACCESO'))
);

create index idx_login_username_fecha on adm_aud_login (username, fecha);

comment on table adm_aud_login is 'Bitácora de inicios de sesión';
