-- =============================================================================
-- Tabla : adm_seg_rol
-- App   : adm | Módulo: seg
-- Desc  : Roles. Un rol pertenece a una aplicación (aplicacion_id) o es
--         global (aplicacion_id null, ej. SUPERADMIN).
--         es_superadmin = 'S' otorga todos los permisos de todas las apps.
-- =============================================================================
create table adm_seg_rol (
    rol_id              number generated by default on null as identity,
    aplicacion_id       number,
    codigo              varchar2(40)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    es_superadmin       varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_rol primary key (rol_id),
    constraint fk_admsegaplicacion_admsegrol foreign key (aplicacion_id)
        references adm_seg_aplicacion (aplicacion_id),
    constraint uk_rol_codigo unique (codigo),
    constraint ck_rol_es_superadmin check (es_superadmin in ('S','N')),
    constraint ck_rol_estado check (estado in ('A','I')),
    constraint ck_rol_codigo_mayus check (codigo = upper(codigo))
);

create index idx_rol_aplicacion on adm_seg_rol (aplicacion_id);

comment on table  adm_seg_rol               is 'Roles por aplicación o globales';
comment on column adm_seg_rol.aplicacion_id is 'Null = rol global';
