-- =============================================================================
-- Tabla : adm_seg_rol_permiso
-- App   : adm | Módulo: seg
-- Desc  : Permisos otorgados a cada rol (N:M).
-- =============================================================================
create table adm_seg_rol_permiso (
    rol_permiso_id      number generated by default on null as identity,
    rol_id              number         not null,
    permiso_id          number         not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_rol_permiso primary key (rol_permiso_id),
    constraint fk_admsegrol_admsegrolpermiso foreign key (rol_id)
        references adm_seg_rol (rol_id) on delete cascade,
    constraint fk_admsegpermiso_admsegrolpermiso foreign key (permiso_id)
        references adm_seg_permiso (permiso_id) on delete cascade,
    constraint uk_rol_permiso unique (rol_id, permiso_id)
);

create index idx_rol_permiso_permiso on adm_seg_rol_permiso (permiso_id);

comment on table adm_seg_rol_permiso is 'Permisos asignados a roles';
