-- =============================================================================
-- Tabla  : adm_seg_usuario_rol   (abrev: usro)
-- Roles por usuario, opcionalmente por empresa (null = todas) y con vigencia.
-- =============================================================================
create table adm_seg_usuario_rol (
    usuario_rol_id      number generated by default on null as identity,
    usuario_id          number         not null,
    rol_id              number         not null,
    empresa_id          number,
    fecha_desde         date           default on null trunc(current_date) not null,
    fecha_hasta         date,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_usro primary key (usuario_rol_id),
    constraint fk_adm_usro_usu foreign key (usuario_id) references adm_seg_usuario (usuario_id) on delete cascade,
    constraint fk_adm_usro_rol foreign key (rol_id) references adm_seg_rol (rol_id),
    constraint fk_adm_usro_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_adm_usro_usu_rol_emp unique (usuario_id, rol_id, empresa_id),
    constraint ck_adm_usro_vigencia check (fecha_hasta is null or fecha_hasta >= fecha_desde)
);

-- (usuario_id ya está indexado por uk_adm_usro_usu_rol_emp)
create index idx_adm_usro_rol_id     on adm_seg_usuario_rol (rol_id);
create index idx_adm_usro_empresa_id on adm_seg_usuario_rol (empresa_id);

comment on table adm_seg_usuario_rol is 'Roles por usuario con vigencia. Abrev: usro';
comment on column adm_seg_usuario_rol.usuario_rol_id     is 'Identificador técnico (PK, identity)';
comment on column adm_seg_usuario_rol.usuario_id         is 'Usuario (FK adm_seg_usuario)';
comment on column adm_seg_usuario_rol.rol_id             is 'Rol asignado (FK adm_seg_rol)';
comment on column adm_seg_usuario_rol.empresa_id         is 'Empresa donde aplica el rol; null = todas (FK adm_gen_empresa)';
comment on column adm_seg_usuario_rol.fecha_desde        is 'Inicio de vigencia (fecha del usuario)';
comment on column adm_seg_usuario_rol.fecha_hasta        is 'Fin de vigencia; null = sin vencimiento';
comment on column adm_seg_usuario_rol.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_seg_usuario_rol.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_seg_usuario_rol.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_seg_usuario_rol.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
