-- =============================================================================
-- Tabla  : adm_gen_mensaje_error   (abrev: mse)
-- Mensajes claros para el usuario por nombre de constraint (uk_, ck_, fk_).
-- Los usa el manejador de errores central para TODAS las apps.
-- =============================================================================
create table adm_gen_mensaje_error (
    mensaje_error_id    number generated by default on null as identity,
    codigo              varchar2(128)  not null,
    mensaje             varchar2(1000) not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_mse primary key (mensaje_error_id),
    constraint uk_adm_mse_codigo unique (codigo),
    constraint ck_adm_mse_codigo_mayus check (codigo = upper(codigo))
);

comment on table  adm_gen_mensaje_error                    is 'Mensajes de error por constraint. Abrev: mse';
comment on column adm_gen_mensaje_error.mensaje_error_id   is 'Identificador técnico (PK, identity)';
comment on column adm_gen_mensaje_error.codigo             is 'Nombre del constraint en mayúsculas (ej. UK_ADM_USU_USERNAME)';
comment on column adm_gen_mensaje_error.mensaje            is 'Mensaje que verá el usuario';
comment on column adm_gen_mensaje_error.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_gen_mensaje_error.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_gen_mensaje_error.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_gen_mensaje_error.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
