-- =============================================================================
-- Tabla  : adm_seg_modulo   (abrev: mod)
-- Módulos funcionales por aplicación.
-- =============================================================================
create table adm_seg_modulo (
    modulo_id           number generated by default on null as identity,
    aplicacion_id       number         not null,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    icono               varchar2(100),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_mod primary key (modulo_id),
    constraint fk_adm_mod_apl foreign key (aplicacion_id) references adm_seg_aplicacion (aplicacion_id),
    constraint uk_adm_mod_apl_codigo unique (aplicacion_id, codigo),
    constraint ck_adm_mod_estado check (estado in ('A','I')),
    constraint ck_adm_mod_codigo_mayus check (codigo = upper(codigo))
);

-- (aplicacion_id ya está indexado por uk_adm_mod_apl_codigo)

comment on table adm_seg_modulo is 'Módulos funcionales por aplicación. Abrev: mod';
