-- =============================================================================
-- Tabla : adm_seg_usuario_rol
-- App   : adm | Módulo: seg
-- Desc  : Roles asignados a usuarios, opcionalmente por empresa y con vigencia.
--         empresa_id null = el rol aplica a todas las empresas.
-- =============================================================================
create table adm_seg_usuario_rol (
    usuario_rol_id      number generated by default on null as identity,
    usuario_id          number         not null,
    rol_id              number         not null,
    empresa_id          number,
    fecha_desde         date           default on null trunc(sysdate) not null,
    fecha_hasta         date,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_usuario_rol primary key (usuario_rol_id),
    constraint fk_admsegusuario_admsegusuariorol foreign key (usuario_id)
        references adm_seg_usuario (usuario_id) on delete cascade,
    constraint fk_admsegrol_admsegusuariorol foreign key (rol_id)
        references adm_seg_rol (rol_id),
    constraint fk_admgenempresa_admsegusuariorol foreign key (empresa_id)
        references adm_gen_empresa (empresa_id),
    constraint uk_usuario_rol_empresa unique (usuario_id, rol_id, empresa_id),
    constraint ck_usuario_rol_vigencia check (fecha_hasta is null or fecha_hasta >= fecha_desde)
);

create index idx_usuario_rol_rol     on adm_seg_usuario_rol (rol_id);
create index idx_usuario_rol_empresa on adm_seg_usuario_rol (empresa_id);

comment on table adm_seg_usuario_rol is 'Roles por usuario (y por empresa) con vigencia';
