-- =============================================================================
-- Tabla  : adm_aud_error   (abrev: err)
-- Bitácora de errores inesperados de todas las apps (manejador de errores APEX
-- y bloques when others). Alto volumen: identity cache 1000.
-- =============================================================================
create table adm_aud_error (
    error_id            number generated by default on null as identity (cache 1000),
    apex_app_id         number,
    apex_pagina_id      number,
    username            varchar2(100),
    componente          varchar2(400),
    mensaje             varchar2(4000),
    ora_sqlcode         number,
    ora_sqlerrm         varchar2(4000),
    error_backtrace     varchar2(4000),
    fecha               timestamp with local time zone default on null systimestamp not null,
    constraint pk_adm_err primary key (error_id)
);

create index idx_adm_err_fecha on adm_aud_error (fecha);

comment on table  adm_aud_error                 is 'Bitácora de errores inesperados (incidentes). Abrev: err';
comment on column adm_aud_error.error_id        is 'Número de incidente que se muestra al usuario';
comment on column adm_aud_error.apex_app_id     is 'Aplicación APEX donde ocurrió';
comment on column adm_aud_error.apex_pagina_id  is 'Página APEX donde ocurrió';
comment on column adm_aud_error.username        is 'Usuario conectado';
comment on column adm_aud_error.componente      is 'Componente APEX o rutina PL/SQL que falló';
comment on column adm_aud_error.mensaje         is 'Mensaje original del error';
comment on column adm_aud_error.ora_sqlcode     is 'Código ORA (negativo)';
comment on column adm_aud_error.ora_sqlerrm     is 'Texto ORA completo';
comment on column adm_aud_error.error_backtrace is 'Pila de llamadas (dbms_utility.format_error_backtrace)';
comment on column adm_aud_error.fecha           is 'Fecha y hora del incidente';
