-- =============================================================================
-- Tabla : adm_seg_permiso
-- App   : adm | Módulo: seg
-- Desc  : Permisos atómicos dentro de un módulo. Pueden ser de tipo:
--           PAGINA  -> acceso a una página APEX (apex_pagina_id)
--           ACCION  -> botón/proceso (crear, anular, aprobar...)
--           REPORTE -> reportes/exportaciones
--         El código es único global, formato sugerido APP_MODULO_ENTIDAD_ACCION
--         (ej. ERP_FIN_FACTURA_ANULAR).
-- =============================================================================
create table adm_seg_permiso (
    permiso_id          number generated by default on null as identity,
    modulo_id           number         not null,
    codigo              varchar2(60)   not null,
    nombre              varchar2(150)  not null,
    descripcion         varchar2(500),
    tipo                varchar2(10)   default on null 'ACCION' not null,
    apex_pagina_id      number,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_permiso primary key (permiso_id),
    constraint fk_admsegmodulo_admsegpermiso foreign key (modulo_id)
        references adm_seg_modulo (modulo_id),
    constraint uk_permiso_codigo unique (codigo),
    constraint ck_permiso_tipo check (tipo in ('PAGINA','ACCION','REPORTE')),
    constraint ck_permiso_pagina check (tipo <> 'PAGINA' or apex_pagina_id is not null),
    constraint ck_permiso_estado check (estado in ('A','I')),
    constraint ck_permiso_codigo_mayus check (codigo = upper(codigo))
);

create index idx_permiso_modulo on adm_seg_permiso (modulo_id);

comment on table  adm_seg_permiso                is 'Permisos atómicos (página, acción o reporte)';
comment on column adm_seg_permiso.apex_pagina_id is 'Página APEX protegida cuando tipo = PAGINA';
