-- =============================================================================
-- Tabla : adm_gen_empresa
-- App   : adm (Administración Central)  | Módulo: gen (General)
-- Desc  : Empresas / unidades de negocio. Permite que todas las apps sean
--         multi-empresa y que los roles se asignen por empresa.
-- =============================================================================
create table adm_gen_empresa (
    empresa_id          number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    razon_social        varchar2(200)  not null,
    nombre_comercial    varchar2(200),
    nro_documento       varchar2(20),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_gen_empresa primary key (empresa_id),
    constraint uk_empresa_codigo unique (codigo),
    constraint ck_empresa_estado check (estado in ('A','I'))
);

comment on table  adm_gen_empresa        is 'Empresas / unidades de negocio (multi-empresa)';
comment on column adm_gen_empresa.estado is 'A=Activo, I=Inactivo';
