-- =============================================================================
-- Tabla : adm_seg_aplicacion
-- App   : adm | Módulo: seg (Seguridad)
-- Desc  : Catálogo de sistemas/aplicaciones (ADM, ERP, CRM...). Cada una puede
--         apuntar a su app APEX para armar el menú/portal de lanzamiento.
-- =============================================================================
create table adm_seg_aplicacion (
    aplicacion_id       number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    apex_app_id         number,
    icono               varchar2(100),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_aplicacion primary key (aplicacion_id),
    constraint uk_aplicacion_codigo unique (codigo),
    constraint uk_aplicacion_apex_app_id unique (apex_app_id),
    constraint ck_aplicacion_estado check (estado in ('A','I')),
    constraint ck_aplicacion_codigo_mayus check (codigo = upper(codigo))
);

comment on table  adm_seg_aplicacion             is 'Sistemas/aplicaciones gestionados por la seguridad central';
comment on column adm_seg_aplicacion.apex_app_id is 'ID de la aplicación APEX (APP_ID)';
