-- =============================================================================
-- Tabla  : adm_seg_aplicacion   (abrev: apl)
-- Catálogo de aplicaciones (ADM, ERP, CRM...).
-- =============================================================================
create table adm_seg_aplicacion (
    aplicacion_id       number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    apex_app_id         number,
    icono               varchar2(100),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_apl primary key (aplicacion_id),
    constraint uk_adm_apl_codigo unique (codigo),
    constraint uk_adm_apl_apex_app_id unique (apex_app_id),
    constraint ck_adm_apl_estado check (estado in ('A','I')),
    constraint ck_adm_apl_codigo_mayus check (codigo = upper(codigo))
);

comment on table  adm_seg_aplicacion             is 'Aplicaciones gestionadas por la seguridad central. Abrev: apl';
comment on column adm_seg_aplicacion.apex_app_id is 'ID de la aplicación APEX (APP_ID)';
comment on column adm_seg_aplicacion.aplicacion_id      is 'Identificador técnico (PK, identity)';
comment on column adm_seg_aplicacion.codigo             is 'Código de la aplicación en mayúsculas (ADM, ERP, CRM); prefijo de sus objetos';
comment on column adm_seg_aplicacion.nombre             is 'Nombre visible de la aplicación';
comment on column adm_seg_aplicacion.descripcion        is 'Descripción funcional';
comment on column adm_seg_aplicacion.icono              is 'Clase de ícono Font APEX (ej. fa-cubes)';
comment on column adm_seg_aplicacion.orden              is 'Orden de presentación en menús y portal';
comment on column adm_seg_aplicacion.estado             is 'A=Activo, I=Inactivo';
comment on column adm_seg_aplicacion.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_seg_aplicacion.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_seg_aplicacion.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_seg_aplicacion.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
