-- =============================================================================
-- Tabla  : adm_gen_empresa   (abrev: emp)
-- Empresas / unidades de negocio (multi-empresa).
-- =============================================================================
create table adm_gen_empresa (
    empresa_id          number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    razon_social        varchar2(200)  not null,
    nombre_comercial    varchar2(200),
    nro_documento       varchar2(20),
    zona_horaria        varchar2(64),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_emp primary key (empresa_id),
    constraint uk_adm_emp_codigo unique (codigo),
    constraint ck_adm_emp_estado check (estado in ('A','I'))
);

comment on table  adm_gen_empresa              is 'Empresas / unidades de negocio. Abrev: emp';
comment on column adm_gen_empresa.zona_horaria is 'Zona horaria IANA (ej. America/Asuncion) para fechas de negocio';
comment on column adm_gen_empresa.estado       is 'A=Activo, I=Inactivo';
comment on column adm_gen_empresa.empresa_id         is 'Identificador técnico (PK, identity)';
comment on column adm_gen_empresa.codigo             is 'Código corto único de la empresa';
comment on column adm_gen_empresa.razon_social       is 'Razón social legal';
comment on column adm_gen_empresa.nombre_comercial   is 'Nombre comercial o de fantasía';
comment on column adm_gen_empresa.nro_documento      is 'Número de identificación tributaria (RUC/NIT)';
comment on column adm_gen_empresa.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_gen_empresa.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_gen_empresa.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_gen_empresa.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
