-- =============================================================================
-- Tabla  : adm_seg_modulo   (abrev: mod)
-- Módulos funcionales por aplicación.
-- =============================================================================
create table adm_seg_modulo (
    modulo_id           number generated by default on null as identity,
    aplicacion_id       number         not null,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    icono               varchar2(100),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_mod primary key (modulo_id),
    constraint fk_adm_mod_apl foreign key (aplicacion_id) references adm_seg_aplicacion (aplicacion_id),
    constraint uk_adm_mod_apl_codigo unique (aplicacion_id, codigo),
    constraint ck_adm_mod_estado check (estado in ('A','I')),
    constraint ck_adm_mod_codigo_mayus check (codigo = upper(codigo))
);

-- (aplicacion_id ya está indexado por uk_adm_mod_apl_codigo)

comment on table adm_seg_modulo is 'Módulos funcionales por aplicación. Abrev: mod';
comment on column adm_seg_modulo.modulo_id          is 'Identificador técnico (PK, identity)';
comment on column adm_seg_modulo.aplicacion_id      is 'Aplicación a la que pertenece (FK adm_seg_aplicacion)';
comment on column adm_seg_modulo.codigo             is 'Código del módulo en mayúsculas, único dentro de la aplicación (FIN, STK)';
comment on column adm_seg_modulo.nombre             is 'Nombre visible del módulo';
comment on column adm_seg_modulo.descripcion        is 'Descripción funcional';
comment on column adm_seg_modulo.icono              is 'Clase de ícono Font APEX';
comment on column adm_seg_modulo.orden              is 'Orden de presentación';
comment on column adm_seg_modulo.estado             is 'A=Activo, I=Inactivo';
comment on column adm_seg_modulo.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_seg_modulo.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_seg_modulo.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_seg_modulo.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
