-- =============================================================================
-- Tabla  : adm_seg_rol   (abrev: rol)
-- Roles por aplicación (aplicacion_id) o globales (null). es_superadmin = S: acceso total.
-- =============================================================================
create table adm_seg_rol (
    rol_id              number generated by default on null as identity,
    aplicacion_id       number,
    codigo              varchar2(40)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    es_superadmin       varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_rol primary key (rol_id),
    constraint fk_adm_rol_apl foreign key (aplicacion_id) references adm_seg_aplicacion (aplicacion_id),
    constraint uk_adm_rol_codigo unique (codigo),
    constraint ck_adm_rol_es_superadmin check (es_superadmin in ('S','N')),
    constraint ck_adm_rol_estado check (estado in ('A','I')),
    constraint ck_adm_rol_codigo_mayus check (codigo = upper(codigo))
);

create index idx_adm_rol_aplicacion_id on adm_seg_rol (aplicacion_id);

comment on table  adm_seg_rol               is 'Roles. Abrev: rol';
comment on column adm_seg_rol.aplicacion_id is 'Null = rol global';
