-- =============================================================================
-- Tabla  : adm_aud_login   (abrev: log)
-- Bitácora de intentos de inicio de sesión. Alto volumen: identity cache 1000.
-- =============================================================================
create table adm_aud_login (
    login_id            number generated by default on null as identity (cache 1000),
    username            varchar2(100)  not null,
    resultado           varchar2(20)   not null,
    apex_app_id         number,
    ip_cliente          varchar2(50),
    fecha               timestamp with local time zone default on null systimestamp not null,
    constraint pk_adm_log primary key (login_id),
    constraint ck_adm_log_resultado check (resultado in ('OK','PASSWORD_INVALIDO','USUARIO_NO_EXISTE','BLOQUEADO','INACTIVO','SIN_ACCESO'))
);

create index idx_adm_log_username_fecha on adm_aud_login (username, fecha);

comment on table adm_aud_login is 'Bitácora de inicios de sesión. Abrev: log';
comment on column adm_aud_login.login_id    is 'Identificador técnico (PK, identity cache 1000)';
comment on column adm_aud_login.username    is 'Usuario que intentó ingresar (tal como lo escribió, en mayúsculas)';
comment on column adm_aud_login.resultado   is 'OK, PASSWORD_INVALIDO, USUARIO_NO_EXISTE, BLOQUEADO, INACTIVO o SIN_ACCESO';
comment on column adm_aud_login.apex_app_id is 'Aplicación APEX desde la que se intentó ingresar';
comment on column adm_aud_login.ip_cliente  is 'Dirección IP del cliente (si está disponible)';
comment on column adm_aud_login.fecha       is 'Fecha y hora del intento';
