-- =============================================================================
-- Tabla  : adm_seg_usuario   (abrev: usu)
-- Usuarios únicos para todas las apps. LOCAL (hash+salt) o SSO (proveedor externo).
-- =============================================================================
create table adm_seg_usuario (
    usuario_id              number generated by default on null as identity,
    username                varchar2(100)  not null,
    email                   varchar2(200)  not null,
    nombres                 varchar2(100)  not null,
    apellidos               varchar2(100),
    tipo_autenticacion      varchar2(10)   default on null 'LOCAL' not null,
    password_hash           raw(64),
    password_salt           raw(32),
    debe_cambiar_password   varchar2(1)    default on null 'S' not null,
    fecha_cambio_password   timestamp with local time zone,
    intentos_fallidos       number(3)      default on null 0 not null,
    fecha_ultimo_login      timestamp with local time zone,
    empresa_id_defecto      number,
    estado                  varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_usu primary key (usuario_id),
    constraint fk_adm_usu_emp_def foreign key (empresa_id_defecto) references adm_gen_empresa (empresa_id),
    constraint uk_adm_usu_username unique (username),
    constraint uk_adm_usu_email unique (email),
    constraint ck_adm_usu_username_mayus check (username = upper(username)),
    constraint ck_adm_usu_tipo_aut check (tipo_autenticacion in ('LOCAL','SSO')),
    constraint ck_adm_usu_password_local check (tipo_autenticacion <> 'LOCAL' or password_hash is not null),
    constraint ck_adm_usu_debe_cambiar check (debe_cambiar_password in ('S','N')),
    constraint ck_adm_usu_estado check (estado in ('A','I','B'))
);

create index idx_adm_usu_empresa_id_def on adm_seg_usuario (empresa_id_defecto);

comment on table  adm_seg_usuario        is 'Usuarios centrales. Abrev: usu';
comment on column adm_seg_usuario.estado is 'A=Activo, I=Inactivo, B=Bloqueado (intentos fallidos)';
comment on column adm_seg_usuario.usuario_id            is 'Identificador técnico (PK, identity)';
comment on column adm_seg_usuario.username              is 'Nombre de usuario para iniciar sesión, en mayúsculas';
comment on column adm_seg_usuario.email                 is 'Correo electrónico único, en minúsculas';
comment on column adm_seg_usuario.nombres               is 'Nombres de la persona';
comment on column adm_seg_usuario.apellidos             is 'Apellidos de la persona';
comment on column adm_seg_usuario.tipo_autenticacion    is 'LOCAL (contraseña propia) o SSO (proveedor externo)';
comment on column adm_seg_usuario.password_hash         is 'Hash PBKDF2-HMAC-SHA512 de la contraseña (solo LOCAL)';
comment on column adm_seg_usuario.password_salt         is 'Salt aleatorio de 32 bytes del hash (solo LOCAL)';
comment on column adm_seg_usuario.debe_cambiar_password is 'S = debe cambiar la contraseña en el próximo ingreso';
comment on column adm_seg_usuario.fecha_cambio_password is 'Fecha del último cambio de contraseña';
comment on column adm_seg_usuario.intentos_fallidos     is 'Intentos fallidos consecutivos; al llegar al máximo se bloquea';
comment on column adm_seg_usuario.fecha_ultimo_login    is 'Fecha del último inicio de sesión exitoso';
comment on column adm_seg_usuario.empresa_id_defecto    is 'Empresa con la que trabaja por defecto (FK adm_gen_empresa)';
comment on column adm_seg_usuario.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_seg_usuario.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_seg_usuario.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_seg_usuario.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
