-- =============================================================================
-- Tabla  : adm_seg_permiso   (abrev: per)
-- Permisos atómicos (PAGINA / ACCION / REPORTE). Código APP_MOD_ENTIDAD_ACCION.
-- =============================================================================
create table adm_seg_permiso (
    permiso_id          number generated by default on null as identity,
    modulo_id           number         not null,
    codigo              varchar2(60)   not null,
    nombre              varchar2(150)  not null,
    descripcion         varchar2(500),
    tipo                varchar2(10)   default on null 'ACCION' not null,
    apex_pagina_id      number,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_per primary key (permiso_id),
    constraint fk_adm_per_mod foreign key (modulo_id) references adm_seg_modulo (modulo_id),
    constraint uk_adm_per_codigo unique (codigo),
    constraint ck_adm_per_tipo check (tipo in ('PAGINA','ACCION','REPORTE')),
    constraint ck_adm_per_pagina check (tipo <> 'PAGINA' or apex_pagina_id is not null),
    constraint ck_adm_per_estado check (estado in ('A','I')),
    constraint ck_adm_per_codigo_mayus check (codigo = upper(codigo))
);

create index idx_adm_per_modulo_id on adm_seg_permiso (modulo_id);

comment on table  adm_seg_permiso                is 'Permisos atómicos. Abrev: per';
comment on column adm_seg_permiso.apex_pagina_id is 'Página APEX protegida cuando tipo = PAGINA';
comment on column adm_seg_permiso.permiso_id         is 'Identificador técnico (PK, identity)';
comment on column adm_seg_permiso.modulo_id          is 'Módulo al que pertenece (FK adm_seg_modulo)';
comment on column adm_seg_permiso.codigo             is 'Código único APP_MOD_ENTIDAD_ACCION; igual al authorization scheme de APEX';
comment on column adm_seg_permiso.nombre             is 'Descripción corta del permiso';
comment on column adm_seg_permiso.descripcion        is 'Explicación de qué habilita el permiso';
comment on column adm_seg_permiso.tipo               is 'PAGINA (acceso a página), ACCION (botón/proceso) o REPORTE';
comment on column adm_seg_permiso.estado             is 'A=Activo, I=Inactivo';
comment on column adm_seg_permiso.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column adm_seg_permiso.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column adm_seg_permiso.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column adm_seg_permiso.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
