-- =============================================================================
-- Tabla  : adm_seg_usuario   (abrev: usu)
-- Usuarios únicos para todas las apps. LOCAL (hash+salt) o SSO (proveedor externo).
-- =============================================================================
create table adm_seg_usuario (
    usuario_id              number generated by default on null as identity,
    username                varchar2(100)  not null,
    email                   varchar2(200)  not null,
    nombres                 varchar2(100)  not null,
    apellidos               varchar2(100),
    tipo_autenticacion      varchar2(10)   default on null 'LOCAL' not null,
    password_hash           raw(64),
    password_salt           raw(32),
    debe_cambiar_password   varchar2(1)    default on null 'S' not null,
    fecha_cambio_password   timestamp with local time zone,
    intentos_fallidos       number(3)      default on null 0 not null,
    fecha_ultimo_login      timestamp with local time zone,
    empresa_id_defecto      number,
    estado                  varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_adm_usu primary key (usuario_id),
    constraint fk_adm_usu_emp_def foreign key (empresa_id_defecto) references adm_gen_empresa (empresa_id),
    constraint uk_adm_usu_username unique (username),
    constraint uk_adm_usu_email unique (email),
    constraint ck_adm_usu_username_mayus check (username = upper(username)),
    constraint ck_adm_usu_tipo_aut check (tipo_autenticacion in ('LOCAL','SSO')),
    constraint ck_adm_usu_password_local check (tipo_autenticacion <> 'LOCAL' or password_hash is not null),
    constraint ck_adm_usu_debe_cambiar check (debe_cambiar_password in ('S','N')),
    constraint ck_adm_usu_estado check (estado in ('A','I','B'))
);

create index idx_adm_usu_empresa_id_def on adm_seg_usuario (empresa_id_defecto);

comment on table  adm_seg_usuario        is 'Usuarios centrales. Abrev: usu';
comment on column adm_seg_usuario.estado is 'A=Activo, I=Inactivo, B=Bloqueado (intentos fallidos)';
