-- =============================================================================
-- Tabla : adm_seg_usuario
-- App   : adm | Módulo: seg
-- Desc  : Usuarios únicos para TODAS las aplicaciones.
--         tipo_autenticacion:
--           LOCAL -> contraseña propia (hash + salt en esta tabla)
--           SSO   -> autenticado por proveedor externo (OCI IAM / Google / MS),
--                    aquí solo se controla estado y autorización.
--         Las contraseñas NUNCA se guardan en claro.
-- =============================================================================
create table adm_seg_usuario (
    usuario_id              number generated by default on null as identity,
    username                varchar2(100)  not null,
    email                   varchar2(200)  not null,
    nombres                 varchar2(100)  not null,
    apellidos               varchar2(100),
    tipo_autenticacion      varchar2(10)   default on null 'LOCAL' not null,
    password_hash           raw(64),
    password_salt           raw(32),
    debe_cambiar_password   varchar2(1)    default on null 'S' not null,
    fecha_cambio_password   timestamp,
    intentos_fallidos       number(3)      default on null 0 not null,
    fecha_ultimo_login      timestamp,
    empresa_id_defecto      number,
    estado                  varchar2(1)    default on null 'A' not null,
    creado_por              varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion          timestamp      default on null systimestamp not null,
    modificado_por          varchar2(100),
    fecha_modificacion      timestamp,
    constraint pk_adm_seg_usuario primary key (usuario_id),
    constraint fk_admgenempresa_admsegusuario foreign key (empresa_id_defecto)
        references adm_gen_empresa (empresa_id),
    constraint uk_usuario_username unique (username),
    constraint uk_usuario_email unique (email),
    constraint ck_usuario_username_mayus check (username = upper(username)),
    constraint ck_usuario_tipo_autenticacion check (tipo_autenticacion in ('LOCAL','SSO')),
    constraint ck_usuario_password_local check (tipo_autenticacion <> 'LOCAL' or password_hash is not null),
    constraint ck_usuario_debe_cambiar check (debe_cambiar_password in ('S','N')),
    constraint ck_usuario_estado check (estado in ('A','I','B'))
);

comment on table  adm_seg_usuario        is 'Usuarios centrales de todas las aplicaciones';
comment on column adm_seg_usuario.estado is 'A=Activo, I=Inactivo, B=Bloqueado (intentos fallidos)';
