-- =============================================================================
-- Tabla  : erp_gen_punto_expedicion   (abrev: ptex)
-- Puntos de expedición de comprobantes (3 dígitos) de una sucursal, opcionalmente de un departamento.
-- =============================================================================
create table erp_gen_punto_expedicion (
    punto_expedicion_id  number generated by default on null as identity,
    sucursal_id          number         not null,
    departamento_id      number,
    codigo               varchar2(3)    not null,
    nombre               varchar2(100)  not null,
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_ptex primary key (punto_expedicion_id),
    constraint fk_erp_ptex_suc foreign key (sucursal_id) references erp_gen_sucursal (sucursal_id),
    constraint fk_erp_ptex_dpto foreign key (departamento_id) references erp_gen_departamento (departamento_id),
    constraint uk_erp_ptex_suc_codigo unique (sucursal_id, codigo),
    constraint ck_erp_ptex_codigo check (regexp_like(codigo, '^[0-9]{3}$')),
    constraint ck_erp_ptex_estado check (estado in ('A','I'))
);

-- (sucursal_id ya indexado por la PK/UK)
create index idx_erp_ptex_departamento_id on erp_gen_punto_expedicion (departamento_id);

comment on table  erp_gen_punto_expedicion is 'Puntos de expedición de comprobantes (3 dígitos) de una sucursal, opcionalmente de un departamento. Abrev: ptex';
comment on column erp_gen_punto_expedicion.punto_expedicion_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_punto_expedicion.sucursal_id         is 'Sucursal / establecimiento (FK erp_gen_sucursal)';
comment on column erp_gen_punto_expedicion.departamento_id     is 'Departamento al que pertenece (FK erp_gen_departamento), opcional';
comment on column erp_gen_punto_expedicion.codigo              is 'Código del punto de expedición (001, 002…)';
comment on column erp_gen_punto_expedicion.nombre              is 'Descripción (Caja 1, Mostrador, Vendedor móvil…)';
comment on column erp_gen_punto_expedicion.estado              is 'A=Activo, I=Inactivo';
comment on column erp_gen_punto_expedicion.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_punto_expedicion.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_punto_expedicion.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_punto_expedicion.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
