-- =============================================================================
-- Tabla  : erp_doc_fe_lote   (abrev: felo)
-- Lote de documentos electrónicos para el envío asíncrono (hasta 50 DE del mismo tipo).
-- Manual Técnico SIFEN v150 §9.2 siRecepLoteDE y §9.3 siResultLoteDE (pág. 47-50).
-- =============================================================================
create table erp_doc_fe_lote (
    fe_lote_id            number generated by default on null as identity (cache 1000),
    empresa_id            number         not null,
    tipo_de               number(2)      not null,
    cantidad              number(3)      default on null 0 not null,
    estado                varchar2(1)    default on null 'P' not null,
    numero_lote           varchar2(15),
    codigo_respuesta      varchar2(4),
    mensaje_respuesta     varchar2(255),
    tiempo_proceso        number(5),
    fecha_envio           timestamp,
    fecha_respuesta       timestamp,
    fecha_limite_consulta timestamp,
    intentos              number(3)      default on null 0 not null,
    proximo_intento       timestamp      default on null localtimestamp,
    ultimo_error          varchar2(1000),
    creado_por            varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion        timestamp with local time zone default on null systimestamp not null,
    modificado_por        varchar2(100),
    fecha_modificacion    timestamp with local time zone,
    constraint pk_erp_felo primary key (fe_lote_id),
    constraint fk_erp_felo_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint ck_erp_felo_estado check (estado in ('P','E','C','R','X')),
    constraint ck_erp_felo_cantidad check (cantidad between 0 and 50)
);

create index idx_erp_felo_emp_estado on erp_doc_fe_lote (empresa_id, estado, proximo_intento);
create index idx_erp_felo_numero_lote on erp_doc_fe_lote (numero_lote);

comment on table  erp_doc_fe_lote is 'Lote de documentos electrónicos para el envío asíncrono (hasta 50 DE del mismo tipo). Abrev: felo';
comment on column erp_doc_fe_lote.fe_lote_id            is 'Identificador técnico (PK, identity); también es el identificador de control del envío (dId)';
comment on column erp_doc_fe_lote.empresa_id            is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_fe_lote.tipo_de               is 'Tipo de documento electrónico del lote (iTiDE); un lote lleva un solo tipo';
comment on column erp_doc_fe_lote.cantidad              is 'Cantidad de documentos del lote';
comment on column erp_doc_fe_lote.estado                is 'P=Pendiente de envío, E=Enviado (en proceso), C=Concluido, R=Rechazado (no encolado), X=Detenido por errores';
comment on column erp_doc_fe_lote.numero_lote           is 'Número de lote devuelto por SIFEN (dProtConsLote)';
comment on column erp_doc_fe_lote.codigo_respuesta      is 'Último código de respuesta (dCodRes / dCodResLot)';
comment on column erp_doc_fe_lote.mensaje_respuesta     is 'Último mensaje de respuesta';
comment on column erp_doc_fe_lote.tiempo_proceso        is 'Tiempo medio de procesamiento informado, en segundos (dTpoProces)';
comment on column erp_doc_fe_lote.fecha_envio           is 'Fecha y hora del envío';
comment on column erp_doc_fe_lote.fecha_respuesta       is 'Fecha y hora de la última respuesta';
comment on column erp_doc_fe_lote.fecha_limite_consulta is 'Hasta cuándo se consulta el lote; después se consulta cada documento por CDC';
comment on column erp_doc_fe_lote.intentos              is 'Intentos de envío o consulta fallidos';
comment on column erp_doc_fe_lote.proximo_intento       is 'Cuándo corresponde el próximo envío o consulta';
comment on column erp_doc_fe_lote.ultimo_error          is 'Último error técnico';
comment on column erp_doc_fe_lote.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_lote.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_lote.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_lote.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
