-- =============================================================================
-- Tabla  : erp_doc_numero_inutilizado   (abrev: nuin)
-- Números anulados, inutilizados o extraviados de un numerador, con motivo obligatorio.
-- Inutilización electrónica: Manual Técnico SIFEN v150 §11.1.1 (pág. 112-113): rango
-- secuencial de hasta 1000 números, con motivo.
-- =============================================================================
create table erp_doc_numero_inutilizado (
    numero_inutilizado_id  number generated by default on null as identity (cache 1000),
    empresa_id             number         not null,
    numerador_id           number         not null,
    numero_desde           number(7)      not null,
    numero_hasta           number(7)      not null,
    tipo                   varchar2(1)    not null,
    motivo_id              number,
    motivo                 varchar2(500)  not null,
    fecha                  date           default on null trunc(current_date) not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_nuin primary key (numero_inutilizado_id),
    constraint fk_erp_nuin_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_nuin_nume foreign key (numerador_id) references erp_doc_numerador (numerador_id),
    constraint fk_erp_nuin_moti foreign key (motivo_id) references erp_doc_motivo (motivo_id),
    constraint uk_erp_nuin_nume_desde unique (numerador_id, numero_desde),
    constraint ck_erp_nuin_rango check (numero_desde >= 1 and numero_hasta >= numero_desde),
    constraint ck_erp_nuin_tipo check (tipo in ('A','I','E')),
    constraint ck_erp_nuin_motivo check (length(trim(motivo)) >= 5)
);

-- (numerador_id ya indexado por la PK/UK)
create index idx_erp_nuin_emp_fecha on erp_doc_numero_inutilizado (empresa_id, fecha);
create index idx_erp_nuin_motivo_id on erp_doc_numero_inutilizado (motivo_id);

comment on table  erp_doc_numero_inutilizado is 'Números anulados, inutilizados o extraviados de un numerador, con motivo obligatorio. Abrev: nuin';
comment on column erp_doc_numero_inutilizado.numero_inutilizado_id is 'Identificador técnico (PK, identity)';
comment on column erp_doc_numero_inutilizado.empresa_id            is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_numero_inutilizado.numerador_id          is 'Numerador (FK erp_doc_numerador)';
comment on column erp_doc_numero_inutilizado.numero_desde          is 'Primer número del rango';
comment on column erp_doc_numero_inutilizado.numero_hasta          is 'Último número del rango (igual al primero si es un solo número)';
comment on column erp_doc_numero_inutilizado.tipo                  is 'A=Anulado, I=Inutilizado, E=Extraviado';
comment on column erp_doc_numero_inutilizado.motivo_id             is 'Motivo tipificado (FK erp_doc_motivo), opcional';
comment on column erp_doc_numero_inutilizado.motivo                is 'Texto del motivo (obligatorio, mínimo 5 caracteres)';
comment on column erp_doc_numero_inutilizado.fecha                 is 'Fecha del hecho (para el registro mensual de comprobantes)';
comment on column erp_doc_numero_inutilizado.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_numero_inutilizado.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_numero_inutilizado.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_numero_inutilizado.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
