-- =============================================================================
-- Tabla  : erp_gen_impuesto_tasa_vig   (abrev: itv)
-- Porcentaje de una tasa con vigencia: rige desde fecha_desde hasta la siguiente vigencia.
-- =============================================================================
create table erp_gen_impuesto_tasa_vig (
    impuesto_tasa_vig_id  number generated by default on null as identity,
    impuesto_tasa_id      number         not null,
    fecha_desde           date           not null,
    porcentaje            number(9,4)    not null,
    observacion           varchar2(400),
    creado_por            varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion        timestamp with local time zone default on null systimestamp not null,
    modificado_por        varchar2(100),
    fecha_modificacion    timestamp with local time zone,
    constraint pk_erp_itv primary key (impuesto_tasa_vig_id),
    constraint fk_erp_itv_imta foreign key (impuesto_tasa_id) references erp_gen_impuesto_tasa (impuesto_tasa_id) on delete cascade,
    constraint uk_erp_itv_tasa_fecha unique (impuesto_tasa_id, fecha_desde),
    constraint ck_erp_itv_porcentaje check (porcentaje between 0 and 100)
);

-- (impuesto_tasa_id ya indexado por la PK/UK)

comment on table  erp_gen_impuesto_tasa_vig is 'Porcentaje de una tasa con vigencia: rige desde fecha_desde hasta la siguiente vigencia. Abrev: itv';
comment on column erp_gen_impuesto_tasa_vig.impuesto_tasa_vig_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_impuesto_tasa_vig.impuesto_tasa_id     is 'Tasa (FK erp_gen_impuesto_tasa)';
comment on column erp_gen_impuesto_tasa_vig.fecha_desde          is 'Fecha desde la que rige el porcentaje';
comment on column erp_gen_impuesto_tasa_vig.porcentaje           is 'Porcentaje del impuesto (10 = 10 %)';
comment on column erp_gen_impuesto_tasa_vig.observacion          is 'Norma o comentario';
comment on column erp_gen_impuesto_tasa_vig.creado_por           is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_impuesto_tasa_vig.fecha_creacion       is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_impuesto_tasa_vig.modificado_por       is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_impuesto_tasa_vig.fecha_modificacion   is 'Fecha y hora de la última modificación (trigger _bu)';
