-- =============================================================================
-- Tabla  : erp_gen_tipo_doc_identidad   (abrev: tdi)
-- Tipos de documento de identidad por país (RUC, cédula, pasaporte…).
-- =============================================================================
create table erp_gen_tipo_doc_identidad (
    tipo_doc_identidad_id  number generated by default on null as identity,
    pais_id                number         not null,
    codigo                 varchar2(10)   not null,
    nombre                 varchar2(100)  not null,
    es_tributario          varchar2(1)    default on null 'N' not null,
    tiene_dv               varchar2(1)    default on null 'N' not null,
    formato_regexp         varchar2(200),
    codigo_oficial         varchar2(5),
    estado                 varchar2(1)    default on null 'A' not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_tdi primary key (tipo_doc_identidad_id),
    constraint fk_erp_tdi_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint uk_erp_tdi_pais_codigo unique (pais_id, codigo),
    constraint ck_erp_tdi_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_tdi_es_tributario check (es_tributario in ('S','N')),
    constraint ck_erp_tdi_tiene_dv check (tiene_dv in ('S','N')),
    constraint ck_erp_tdi_estado check (estado in ('A','I'))
);

-- (pais_id ya indexado por la PK/UK)

comment on table  erp_gen_tipo_doc_identidad is 'Tipos de documento de identidad por país (RUC, cédula, pasaporte…). Abrev: tdi';
comment on column erp_gen_tipo_doc_identidad.tipo_doc_identidad_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_tipo_doc_identidad.pais_id               is 'País emisor (FK erp_gen_pais)';
comment on column erp_gen_tipo_doc_identidad.codigo                is 'Código corto (RUC, CI, PAS…)';
comment on column erp_gen_tipo_doc_identidad.nombre                is 'Nombre';
comment on column erp_gen_tipo_doc_identidad.es_tributario         is 'S=Identificación tributaria (RUC)';
comment on column erp_gen_tipo_doc_identidad.tiene_dv              is 'S=Lleva dígito verificador';
comment on column erp_gen_tipo_doc_identidad.formato_regexp        is 'Expresión regular de validación del número (opcional)';
comment on column erp_gen_tipo_doc_identidad.codigo_oficial        is 'Código oficial (SIFEN iTipIDRec: 1=CI, 2=Pasaporte, 3=CI extranjera, 4=Carnet residencia, 5=Innominado, 6=Diplomática, 9=Otro)';
comment on column erp_gen_tipo_doc_identidad.estado                is 'A=Activo, I=Inactivo';
comment on column erp_gen_tipo_doc_identidad.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_tipo_doc_identidad.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_tipo_doc_identidad.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_tipo_doc_identidad.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
