-- =============================================================================
-- Tabla  : erp_stk_numerador   (abrev: stnu)
-- Numeración interna de documentos de inventario por empresa y sucursal (se toma con bloqueo en la transacción del documento).
-- =============================================================================
create table erp_stk_numerador (
    numerador_id        number generated by default on null as identity,
    empresa_id          number         not null,
    sucursal_id         number         not null,
    codigo              varchar2(20)   not null,
    ultimo_numero       number         default on null 0 not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_stnu primary key (numerador_id),
    constraint fk_erp_stnu_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_stnu_suc foreign key (sucursal_id) references erp_gen_sucursal (sucursal_id),
    constraint uk_erp_stnu_emp_suc_codigo unique (empresa_id, sucursal_id, codigo),
    constraint ck_erp_stnu_codigo_mayus check (codigo = upper(codigo))
);

create index idx_erp_stnu_sucursal_id on erp_stk_numerador (sucursal_id);

comment on table  erp_stk_numerador is 'Numeración interna de documentos de inventario por empresa y sucursal (se toma con bloqueo en la transacción del documento). Abrev: stnu';
comment on column erp_stk_numerador.numerador_id       is 'Identificador técnico (PK, identity)';
comment on column erp_stk_numerador.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_numerador.sucursal_id        is 'Sucursal (FK erp_gen_sucursal)';
comment on column erp_stk_numerador.codigo             is 'Documento numerado (TRASLADO)';
comment on column erp_stk_numerador.ultimo_numero      is 'Último número entregado';
comment on column erp_stk_numerador.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_numerador.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_numerador.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_numerador.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
