-- =============================================================================
-- Tabla  : erp_gen_persona_direccion   (abrev: prdi)
-- Direcciones de una persona (fiscal, entrega, cobro).
-- =============================================================================
create table erp_gen_persona_direccion (
    persona_direccion_id  number generated by default on null as identity (cache 1000),
    persona_id            number         not null,
    tipo                  varchar2(1)    default on null 'F' not null,
    direccion             varchar2(400)  not null,
    numero_casa           varchar2(10),
    ubicacion_id          number,
    referencia            varchar2(400),
    latitud               number(10,7),
    longitud              number(10,7),
    es_principal          varchar2(1)    default on null 'N' not null,
    estado                varchar2(1)    default on null 'A' not null,
    creado_por            varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion        timestamp with local time zone default on null systimestamp not null,
    modificado_por        varchar2(100),
    fecha_modificacion    timestamp with local time zone,
    constraint pk_erp_prdi primary key (persona_direccion_id),
    constraint fk_erp_prdi_prs foreign key (persona_id) references erp_gen_persona (persona_id) on delete cascade,
    constraint fk_erp_prdi_ubi foreign key (ubicacion_id) references erp_gen_ubicacion (ubicacion_id),
    constraint ck_erp_prdi_tipo check (tipo in ('F','E','C','O')),
    constraint ck_erp_prdi_es_principal check (es_principal in ('S','N')),
    constraint ck_erp_prdi_estado check (estado in ('A','I'))
);

create index idx_erp_prdi_persona_id on erp_gen_persona_direccion (persona_id);
create index idx_erp_prdi_ubicacion_id on erp_gen_persona_direccion (ubicacion_id);

comment on table  erp_gen_persona_direccion is 'Direcciones de una persona (fiscal, entrega, cobro). Abrev: prdi';
comment on column erp_gen_persona_direccion.persona_direccion_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_persona_direccion.persona_id           is 'Persona (FK erp_gen_persona)';
comment on column erp_gen_persona_direccion.tipo                 is 'F=Fiscal, E=Entrega, C=Cobro, O=Otra';
comment on column erp_gen_persona_direccion.direccion            is 'Calle y referencia principal';
comment on column erp_gen_persona_direccion.numero_casa          is 'Número de casa';
comment on column erp_gen_persona_direccion.ubicacion_id         is 'Ciudad (FK erp_gen_ubicacion)';
comment on column erp_gen_persona_direccion.referencia           is 'Referencia para llegar';
comment on column erp_gen_persona_direccion.latitud              is 'Latitud (GPS)';
comment on column erp_gen_persona_direccion.longitud             is 'Longitud (GPS)';
comment on column erp_gen_persona_direccion.es_principal         is 'S=Dirección principal de su tipo';
comment on column erp_gen_persona_direccion.estado               is 'A=Activo, I=Inactivo';
comment on column erp_gen_persona_direccion.creado_por           is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_persona_direccion.fecha_creacion       is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_persona_direccion.modificado_por       is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_persona_direccion.fecha_modificacion   is 'Fecha y hora de la última modificación (trigger _bu)';
