-- =============================================================================
-- Tabla  : erp_stk_producto_proveedor   (abrev: prpv)
-- Datos de compra del producto por proveedor: mínimo, múltiplo y plazo de entrega.
-- =============================================================================
create table erp_stk_producto_proveedor (
    producto_proveedor_id  number generated by default on null as identity,
    producto_id            number         not null,
    persona_id             number         not null,
    cantidad_minima        number(18,4),
    multiplo_compra        number(18,4),
    dias_entrega           number(4),
    es_principal           varchar2(1)    default on null 'N' not null,
    estado                 varchar2(1)    default on null 'A' not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_prpv primary key (producto_proveedor_id),
    constraint fk_erp_prpv_pro foreign key (producto_id) references erp_stk_producto (producto_id) on delete cascade,
    constraint fk_erp_prpv_prs foreign key (persona_id) references erp_gen_persona (persona_id),
    constraint uk_erp_prpv_pro_prs unique (producto_id, persona_id),
    constraint ck_erp_prpv_es_principal check (es_principal in ('S','N')),
    constraint ck_erp_prpv_cantidades check (coalesce(cantidad_minima, 0) >= 0 and coalesce(multiplo_compra, 1) > 0 and coalesce(dias_entrega, 0) >= 0),
    constraint ck_erp_prpv_estado check (estado in ('A','I'))
);

create index idx_erp_prpv_persona_id on erp_stk_producto_proveedor (persona_id);

comment on table  erp_stk_producto_proveedor is 'Datos de compra del producto por proveedor: mínimo, múltiplo y plazo de entrega. Abrev: prpv';
comment on column erp_stk_producto_proveedor.producto_proveedor_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_producto_proveedor.producto_id           is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_producto_proveedor.persona_id            is 'Proveedor (FK erp_gen_persona)';
comment on column erp_stk_producto_proveedor.cantidad_minima       is 'Mínimo de compra, en unidad de compra';
comment on column erp_stk_producto_proveedor.multiplo_compra       is 'La cantidad pedida se redondea hacia arriba a este múltiplo';
comment on column erp_stk_producto_proveedor.dias_entrega          is 'Plazo de entrega en días';
comment on column erp_stk_producto_proveedor.es_principal          is 'S=Proveedor habitual del producto';
comment on column erp_stk_producto_proveedor.estado                is 'A=Activo, I=Inactivo';
comment on column erp_stk_producto_proveedor.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_producto_proveedor.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_producto_proveedor.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_producto_proveedor.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
