-- =============================================================================
-- Tabla  : erp_doc_timbrado   (abrev: timb)
-- Timbrados de cada empresa (autorización de la administración tributaria para emitir comprobantes).
-- Manual Técnico SIFEN v150: campos C004 dNumTim (8 dígitos), C008 dFeIniT, C009 dFeFinT (pág. 63-64).
-- =============================================================================
create table erp_doc_timbrado (
    timbrado_id         number generated by default on null as identity,
    empresa_id          number         not null,
    numero              varchar2(8)    not null,
    tipo                varchar2(1)    not null,
    fecha_desde         date           not null,
    fecha_hasta         date,
    observacion         varchar2(400),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_timb primary key (timbrado_id),
    constraint fk_erp_timb_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_timb_emp_numero unique (empresa_id, numero),
    constraint ck_erp_timb_numero check (regexp_like(numero, '^[0-9]{8}$')),
    constraint ck_erp_timb_tipo check (tipo in ('E','P','A')),
    constraint ck_erp_timb_vigencia check (fecha_hasta is null or fecha_hasta >= fecha_desde),
    constraint ck_erp_timb_hasta_papel check (tipo = 'E' or fecha_hasta is not null),
    constraint ck_erp_timb_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)

comment on table  erp_doc_timbrado is 'Timbrados de cada empresa (autorización de la administración tributaria para emitir comprobantes). Abrev: timb';
comment on column erp_doc_timbrado.timbrado_id        is 'Identificador técnico (PK, identity)';
comment on column erp_doc_timbrado.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_timbrado.numero             is 'Número del timbrado (8 dígitos)';
comment on column erp_doc_timbrado.tipo               is 'E=Electrónico, P=Preimpreso, A=Autoimpresor';
comment on column erp_doc_timbrado.fecha_desde        is 'Inicio de vigencia';
comment on column erp_doc_timbrado.fecha_hasta        is 'Fin de vigencia (obligatorio en preimpreso y autoimpresor; el electrónico puede no tenerlo)';
comment on column erp_doc_timbrado.observacion        is 'Observaciones';
comment on column erp_doc_timbrado.estado             is 'A=Activo, I=Inactivo';
comment on column erp_doc_timbrado.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_timbrado.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_timbrado.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_timbrado.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
