-- =============================================================================
-- Tabla  : erp_stk_traslado_item   (abrev: trit)
-- Ítems del traslado con sus cantidades en cada etapa y el costo con que salió la mercadería.
-- =============================================================================
create table erp_stk_traslado_item (
    traslado_item_id               number generated by default on null as identity (cache 1000),
    traslado_id                    number         not null,
    linea                          number(6)      not null,
    producto_id                    number         not null,
    lote_id                        number,
    deposito_ubicacion_id_origen   number,
    deposito_ubicacion_id_destino  number,
    cantidad_solicitada            number(18,4)   not null,
    cantidad_aprobada              number(18,4)   default on null 0 not null,
    cantidad_despachada            number(18,4)   default on null 0 not null,
    cantidad_recibida              number(18,4)   default on null 0 not null,
    cantidad_averiada              number(18,4)   default on null 0 not null,
    cantidad_faltante              number(18,4)   default on null 0 not null,
    cantidad_perdida               number(18,4)   default on null 0 not null,
    cantidad_devuelta              number(18,4)   default on null 0 not null,
    costo_unitario                 number(18,6)   default on null 0 not null,
    costo_unitario_reporte         number(18,6)   default on null 0 not null,
    flete_unitario                 number(18,6)   default on null 0 not null,
    flete_unitario_reporte         number(18,6)   default on null 0 not null,
    observacion                    varchar2(400),
    creado_por                     varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion                 timestamp with local time zone default on null systimestamp not null,
    modificado_por                 varchar2(100),
    fecha_modificacion             timestamp with local time zone,
    constraint pk_erp_trit primary key (traslado_item_id),
    constraint fk_erp_trit_tra foreign key (traslado_id) references erp_stk_traslado (traslado_id),
    constraint fk_erp_trit_pro foreign key (producto_id) references erp_stk_producto (producto_id),
    constraint fk_erp_trit_lot foreign key (lote_id) references erp_stk_lote (lote_id),
    constraint fk_erp_trit_dpub_origen foreign key (deposito_ubicacion_id_origen) references erp_stk_deposito_ubicacion (deposito_ubicacion_id),
    constraint fk_erp_trit_dpub_destino foreign key (deposito_ubicacion_id_destino) references erp_stk_deposito_ubicacion (deposito_ubicacion_id),
    constraint uk_erp_trit_tra_linea unique (traslado_id, linea),
    constraint ck_erp_trit_solicitada check (cantidad_solicitada > 0),
    constraint ck_erp_trit_no_negativas check (cantidad_aprobada >= 0 and cantidad_despachada >= 0 and cantidad_recibida >= 0 and cantidad_averiada >= 0 and cantidad_faltante >= 0 and cantidad_perdida >= 0 and cantidad_devuelta >= 0),
    constraint ck_erp_trit_despachada check (cantidad_despachada <= cantidad_aprobada or cantidad_aprobada = 0),
    constraint ck_erp_trit_recibida check (cantidad_recibida + cantidad_averiada + cantidad_faltante + cantidad_perdida + cantidad_devuelta <= cantidad_despachada)
);

create index idx_erp_trit_producto_id on erp_stk_traslado_item (producto_id);
create index idx_erp_trit_lote_id on erp_stk_traslado_item (lote_id);
create index idx_erp_trit_ubicacion_origen on erp_stk_traslado_item (deposito_ubicacion_id_origen);
create index idx_erp_trit_ubicacion_destino on erp_stk_traslado_item (deposito_ubicacion_id_destino);

comment on table  erp_stk_traslado_item is 'Ítems del traslado con sus cantidades en cada etapa y el costo con que salió la mercadería. Abrev: trit';
comment on column erp_stk_traslado_item.traslado_item_id              is 'Identificador técnico (PK, identity)';
comment on column erp_stk_traslado_item.traslado_id                   is 'Traslado (FK erp_stk_traslado)';
comment on column erp_stk_traslado_item.linea                         is 'Número de línea';
comment on column erp_stk_traslado_item.producto_id                   is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_traslado_item.lote_id                       is 'Lote o serie (FK erp_stk_lote)';
comment on column erp_stk_traslado_item.deposito_ubicacion_id_origen  is 'Ubicación de retiro en el origen (FK erp_stk_deposito_ubicacion)';
comment on column erp_stk_traslado_item.deposito_ubicacion_id_destino is 'Ubicación de guardado en el destino (FK erp_stk_deposito_ubicacion)';
comment on column erp_stk_traslado_item.cantidad_solicitada           is 'Cantidad pedida';
comment on column erp_stk_traslado_item.cantidad_aprobada             is 'Cantidad aprobada y reservada en el origen';
comment on column erp_stk_traslado_item.cantidad_despachada           is 'Cantidad que salió del origen';
comment on column erp_stk_traslado_item.cantidad_recibida             is 'Cantidad recibida conforme en el destino';
comment on column erp_stk_traslado_item.cantidad_averiada             is 'Cantidad recibida con daños (entra a cuarentena)';
comment on column erp_stk_traslado_item.cantidad_faltante             is 'Faltante declarado pendiente de resolver (sigue en tránsito)';
comment on column erp_stk_traslado_item.cantidad_perdida              is 'Faltante resuelto como pérdida';
comment on column erp_stk_traslado_item.cantidad_devuelta             is 'Cantidad que volvió al origen (faltante devuelto o rechazo del destino)';
comment on column erp_stk_traslado_item.costo_unitario                is 'Costo unitario con que salió, en moneda funcional';
comment on column erp_stk_traslado_item.costo_unitario_reporte        is 'Costo unitario con que salió, en moneda de reporte';
comment on column erp_stk_traslado_item.flete_unitario                is 'Flete capitalizable prorrateado por unidad, en moneda funcional';
comment on column erp_stk_traslado_item.flete_unitario_reporte        is 'Flete capitalizable prorrateado por unidad, en moneda de reporte';
comment on column erp_stk_traslado_item.observacion                   is 'Observación';
comment on column erp_stk_traslado_item.creado_por                    is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_traslado_item.fecha_creacion                is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_traslado_item.modificado_por                is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_traslado_item.fecha_modificacion            is 'Fecha y hora de la última modificación (trigger _bu)';
