-- =============================================================================
-- Tabla  : erp_stk_movimiento   (abrev: mov)
-- Movimientos de stock (cabecera): un movimiento por evento, con origen genérico. Inmutable: se anula con un movimiento de reverso.
-- =============================================================================
create table erp_stk_movimiento (
    movimiento_id            number generated by default on null as identity (cache 1000),
    empresa_id               number         not null,
    tipo_movimiento_id       number         not null,
    fecha_movimiento         date           not null,
    origen_modulo            varchar2(3)    default on null 'STK' not null,
    origen_tabla             varchar2(30),
    origen_id                number,
    motivo                   varchar2(400),
    observacion              varchar2(4000),
    es_reverso               varchar2(1)    default on null 'N' not null,
    movimiento_id_reversado  number,
    estado                   varchar2(1)    default on null 'C' not null,
    creado_por               varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion           timestamp with local time zone default on null systimestamp not null,
    modificado_por           varchar2(100),
    fecha_modificacion       timestamp with local time zone,
    constraint pk_erp_mov primary key (movimiento_id),
    constraint fk_erp_mov_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_mov_timo foreign key (tipo_movimiento_id) references erp_stk_tipo_movimiento (tipo_movimiento_id),
    constraint fk_erp_mov_mov_reversado foreign key (movimiento_id_reversado) references erp_stk_movimiento (movimiento_id),
    constraint uk_erp_mov_reversado unique (movimiento_id_reversado),
    constraint ck_erp_mov_origen_mayus check (origen_modulo = upper(origen_modulo)),
    constraint ck_erp_mov_es_reverso check (es_reverso in ('S','N')),
    constraint ck_erp_mov_reverso check ((es_reverso = 'S' and movimiento_id_reversado is not null) or (es_reverso = 'N' and movimiento_id_reversado is null)),
    constraint ck_erp_mov_estado check (estado in ('C','R'))
);

create index idx_erp_mov_emp_fecha on erp_stk_movimiento (empresa_id, fecha_movimiento);
create index idx_erp_mov_emp_origen on erp_stk_movimiento (empresa_id, origen_modulo, origen_tabla, origen_id);
create index idx_erp_mov_tipo_movimiento on erp_stk_movimiento (tipo_movimiento_id);

comment on table  erp_stk_movimiento is 'Movimientos de stock (cabecera): un movimiento por evento, con origen genérico. Inmutable: se anula con un movimiento de reverso. Abrev: mov';
comment on column erp_stk_movimiento.movimiento_id           is 'Identificador técnico (PK, identity)';
comment on column erp_stk_movimiento.empresa_id              is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_movimiento.tipo_movimiento_id      is 'Tipo de movimiento (FK erp_stk_tipo_movimiento)';
comment on column erp_stk_movimiento.fecha_movimiento        is 'Fecha del movimiento (define el período)';
comment on column erp_stk_movimiento.origen_modulo           is 'Módulo del documento que lo generó (STK, COM, VEN…)';
comment on column erp_stk_movimiento.origen_tabla            is 'Tabla del documento de origen';
comment on column erp_stk_movimiento.origen_id               is 'Identificador del documento de origen';
comment on column erp_stk_movimiento.motivo                  is 'Motivo (obligatorio según el tipo)';
comment on column erp_stk_movimiento.observacion             is 'Observación';
comment on column erp_stk_movimiento.es_reverso              is 'S=Es el reverso de otro movimiento';
comment on column erp_stk_movimiento.movimiento_id_reversado is 'Movimiento que este reverso anula (FK erp_stk_movimiento)';
comment on column erp_stk_movimiento.estado                  is 'C=Confirmado, R=Reversado';
comment on column erp_stk_movimiento.creado_por              is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_movimiento.fecha_creacion          is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_movimiento.modificado_por          is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_movimiento.fecha_modificacion      is 'Fecha y hora de la última modificación (trigger _bu)';
