-- =============================================================================
-- Tabla  : erp_doc_fe_certificado   (abrev: fece)
-- Certificado digital X.509 de la empresa y su clave privada CIFRADA (AES-256) para la firma
-- de documentos electrónicos. Manual Técnico SIFEN v150 §7.5 (pág. 36-37): RSA 2048.
-- NUNCA se guarda la clave privada en claro ni se versionan claves o certificados reales.
-- =============================================================================
create table erp_doc_fe_certificado (
    fe_certificado_id       number generated by default on null as identity,
    empresa_id              number         not null,
    nombre                  varchar2(100)  not null,
    certificado             clob           not null,
    clave_publica           varchar2(4000) not null,
    clave_privada_cifrada   blob           not null,
    huella_sha256           varchar2(64)   not null,
    fecha_desde             timestamp      not null,
    fecha_hasta             timestamp      not null,
    es_prueba               varchar2(1)    default on null 'N' not null,
    estado                  varchar2(1)    default on null 'A' not null,
    creado_por              varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion          timestamp with local time zone default on null systimestamp not null,
    modificado_por          varchar2(100),
    fecha_modificacion      timestamp with local time zone,
    constraint pk_erp_fece primary key (fe_certificado_id),
    constraint fk_erp_fece_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_fece_emp_huella unique (empresa_id, huella_sha256),
    constraint ck_erp_fece_vigencia check (fecha_hasta >= fecha_desde),
    constraint ck_erp_fece_es_prueba check (es_prueba in ('S','N')),
    constraint ck_erp_fece_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)

comment on table  erp_doc_fe_certificado is 'Certificado digital X.509 de la empresa y su clave privada cifrada para firmar documentos electrónicos. Abrev: fece';
comment on column erp_doc_fe_certificado.fe_certificado_id     is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_certificado.empresa_id            is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_fe_certificado.nombre                is 'Nombre para identificarlo';
comment on column erp_doc_fe_certificado.certificado           is 'Certificado X.509 en Base64 (DER), sin cabeceras ni saltos de línea; va en X509Certificate';
comment on column erp_doc_fe_certificado.clave_publica         is 'Clave pública (SubjectPublicKeyInfo) en Base64, extraída del certificado; la usa la verificación';
comment on column erp_doc_fe_certificado.clave_privada_cifrada is 'Clave privada cifrada con AES-256-CBC (vector de inicialización + datos); la frase no se guarda';
comment on column erp_doc_fe_certificado.huella_sha256         is 'Huella SHA-256 del certificado en hexadecimal';
comment on column erp_doc_fe_certificado.fecha_desde           is 'Inicio de validez del certificado (UTC)';
comment on column erp_doc_fe_certificado.fecha_hasta           is 'Fin de validez del certificado (UTC)';
comment on column erp_doc_fe_certificado.es_prueba             is 'S=Certificado de prueba sin valor (autofirmado)';
comment on column erp_doc_fe_certificado.estado                is 'A=Activo, I=Inactivo';
comment on column erp_doc_fe_certificado.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_certificado.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_certificado.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_certificado.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
