-- =============================================================================
-- Tabla  : erp_gen_departamento   (abrev: dpto)
-- Departamentos / unidades de negocio de la empresa (de toda la empresa o de una sucursal). Dimensión de análisis opcional.
-- =============================================================================
create table erp_gen_departamento (
    departamento_id     number generated by default on null as identity,
    empresa_id          number         not null,
    sucursal_id         number,
    codigo              varchar2(10)   not null,
    nombre              varchar2(100)  not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_dpto primary key (departamento_id),
    constraint fk_erp_dpto_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_dpto_suc foreign key (sucursal_id) references erp_gen_sucursal (sucursal_id),
    constraint uk_erp_dpto_emp_codigo unique (empresa_id, codigo),
    constraint ck_erp_dpto_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_dpto_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_dpto_sucursal_id on erp_gen_departamento (sucursal_id);

comment on table  erp_gen_departamento is 'Departamentos / unidades de negocio de la empresa (de toda la empresa o de una sucursal). Dimensión de análisis opcional. Abrev: dpto';
comment on column erp_gen_departamento.departamento_id    is 'Identificador técnico (PK, identity)';
comment on column erp_gen_departamento.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_gen_departamento.sucursal_id        is 'Sucursal a la que pertenece; null = de toda la empresa (FK erp_gen_sucursal)';
comment on column erp_gen_departamento.codigo             is 'Código interno';
comment on column erp_gen_departamento.nombre             is 'Nombre (Ventas, Administración, Taller…)';
comment on column erp_gen_departamento.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_departamento.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_departamento.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_departamento.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_departamento.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
