-- =============================================================================
-- Tabla  : erp_gen_usuario_sucursal   (abrev: ussu)
-- Sucursales (y departamentos) que puede operar cada usuario, con su punto de expedición por defecto.
-- =============================================================================
create table erp_gen_usuario_sucursal (
    usuario_sucursal_id  number generated by default on null as identity,
    usuario_id           number         not null,
    sucursal_id          number         not null,
    departamento_id      number,
    punto_expedicion_id  number,
    es_defecto           varchar2(1)    default on null 'N' not null,
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_ussu primary key (usuario_sucursal_id),
    constraint fk_erp_ussu_usu foreign key (usuario_id) references adm_seg_usuario (usuario_id) on delete cascade,
    constraint fk_erp_ussu_suc foreign key (sucursal_id) references erp_gen_sucursal (sucursal_id) on delete cascade,
    constraint fk_erp_ussu_dpto foreign key (departamento_id) references erp_gen_departamento (departamento_id),
    constraint fk_erp_ussu_ptex foreign key (punto_expedicion_id) references erp_gen_punto_expedicion (punto_expedicion_id),
    constraint uk_erp_ussu_usu_suc_dpto unique (usuario_id, sucursal_id, departamento_id),
    constraint ck_erp_ussu_es_defecto check (es_defecto in ('S','N')),
    constraint ck_erp_ussu_estado check (estado in ('A','I'))
);

-- (usuario_id ya indexado por la PK/UK)
create index idx_erp_ussu_sucursal_id on erp_gen_usuario_sucursal (sucursal_id);
create index idx_erp_ussu_departamento_id on erp_gen_usuario_sucursal (departamento_id);
create index idx_erp_ussu_ptex on erp_gen_usuario_sucursal (punto_expedicion_id);

comment on table  erp_gen_usuario_sucursal is 'Sucursales (y departamentos) que puede operar cada usuario, con su punto de expedición por defecto. Abrev: ussu';
comment on column erp_gen_usuario_sucursal.usuario_sucursal_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_usuario_sucursal.usuario_id          is 'Usuario (FK adm_seg_usuario)';
comment on column erp_gen_usuario_sucursal.sucursal_id         is 'Sucursal habilitada (FK erp_gen_sucursal)';
comment on column erp_gen_usuario_sucursal.departamento_id     is 'Departamento habilitado; null = todos (FK erp_gen_departamento)';
comment on column erp_gen_usuario_sucursal.punto_expedicion_id is 'Punto de expedición por defecto (FK erp_gen_punto_expedicion)';
comment on column erp_gen_usuario_sucursal.es_defecto          is 'S=Sucursal con la que el usuario inicia';
comment on column erp_gen_usuario_sucursal.estado              is 'A=Activo, I=Inactivo';
comment on column erp_gen_usuario_sucursal.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_usuario_sucursal.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_usuario_sucursal.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_usuario_sucursal.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
