-- =============================================================================
-- Tabla  : erp_stk_motivo_traslado   (abrev: motr)
-- Motivos de traslado con su código SIFEN (iMotEmiNR) y los tipos de traslado en que se usan.
-- =============================================================================
create table erp_stk_motivo_traslado (
    motivo_traslado_id  number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    codigo_sifen        number(2),
    es_tipo_interno     varchar2(1)    default on null 'N' not null,
    es_tipo_remision    varchar2(1)    default on null 'N' not null,
    es_tipo_tercero     varchar2(1)    default on null 'N' not null,
    es_devolucion       varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_motr primary key (motivo_traslado_id),
    constraint uk_erp_motr_codigo unique (codigo),
    constraint ck_erp_motr_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_motr_es_interno check (es_tipo_interno in ('S','N')),
    constraint ck_erp_motr_es_remision check (es_tipo_remision in ('S','N')),
    constraint ck_erp_motr_es_tercero check (es_tipo_tercero in ('S','N')),
    constraint ck_erp_motr_es_devolucion check (es_devolucion in ('S','N')),
    constraint ck_erp_motr_estado check (estado in ('A','I'))
);


comment on table  erp_stk_motivo_traslado is 'Motivos de traslado con su código SIFEN (iMotEmiNR) y los tipos de traslado en que se usan. Abrev: motr';
comment on column erp_stk_motivo_traslado.motivo_traslado_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_motivo_traslado.codigo             is 'Código en mayúsculas';
comment on column erp_stk_motivo_traslado.nombre             is 'Nombre';
comment on column erp_stk_motivo_traslado.codigo_sifen       is 'Motivo de emisión de la nota de remisión en SIFEN; null = no emite remisión';
comment on column erp_stk_motivo_traslado.es_tipo_interno    is 'S=Se usa en traslados internos (sin remisión)';
comment on column erp_stk_motivo_traslado.es_tipo_remision   is 'S=Se usa en traslados con remisión entre locales de la empresa';
comment on column erp_stk_motivo_traslado.es_tipo_tercero    is 'S=Se usa en traslados a terceros';
comment on column erp_stk_motivo_traslado.es_devolucion      is 'S=Motivo de las devoluciones enlazadas';
comment on column erp_stk_motivo_traslado.estado             is 'A=Activo, I=Inactivo';
comment on column erp_stk_motivo_traslado.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_motivo_traslado.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_motivo_traslado.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_motivo_traslado.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
