-- =============================================================================
-- Tabla  : erp_doc_numerador   (abrev: nume)
-- Correlativo de comprobantes por timbrado + punto de expedición + tipo de documento (+ serie).
-- El número legal NUNCA sale de una secuencia: se toma con select … for update en la
-- transacción del documento (docs/ESTANDAR.md §1.3). Serie: Manual Técnico SIFEN v150 §10.5 (pág. 59-60).
-- =============================================================================
create table erp_doc_numerador (
    numerador_id             number generated by default on null as identity,
    empresa_id               number         not null,
    timbrado_id              number         not null,
    punto_expedicion_id      number         not null,
    tipo_documento_id        number         not null,
    serie                    varchar2(2),
    numero_desde             number(7)      default on null 1 not null,
    numero_hasta             number(7)      default on null 9999999 not null,
    numero_actual            number(7)      default on null 0 not null,
    dias_aviso_vencimiento   number(3)      default on null 30 not null,
    porcentaje_aviso         number(5,2)    default on null 90 not null,
    es_restringido           varchar2(1)    default on null 'N' not null,
    estado                   varchar2(1)    default on null 'A' not null,
    creado_por               varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion           timestamp with local time zone default on null systimestamp not null,
    modificado_por           varchar2(100),
    fecha_modificacion       timestamp with local time zone,
    constraint pk_erp_nume primary key (numerador_id),
    constraint fk_erp_nume_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_nume_timb foreign key (timbrado_id) references erp_doc_timbrado (timbrado_id),
    constraint fk_erp_nume_ptex foreign key (punto_expedicion_id) references erp_gen_punto_expedicion (punto_expedicion_id),
    constraint fk_erp_nume_tido foreign key (tipo_documento_id) references erp_doc_tipo_documento (tipo_documento_id),
    constraint uk_erp_nume_timb_ptex_tido unique (timbrado_id, punto_expedicion_id, tipo_documento_id, serie),
    constraint ck_erp_nume_serie check (serie is null or regexp_like(serie, '^[A-Z]{2}$')),
    constraint ck_erp_nume_rango check (numero_desde >= 1 and numero_hasta >= numero_desde),
    constraint ck_erp_nume_numero_actual check (numero_actual between numero_desde - 1 and numero_hasta),
    constraint ck_erp_nume_dias_aviso check (dias_aviso_vencimiento >= 0),
    constraint ck_erp_nume_porcentaje_aviso check (porcentaje_aviso between 0 and 100),
    constraint ck_erp_nume_es_restringido check (es_restringido in ('S','N')),
    constraint ck_erp_nume_estado check (estado in ('A','I'))
);

-- (timbrado_id ya indexado por la PK/UK)
create index idx_erp_nume_empresa_id on erp_doc_numerador (empresa_id);
create index idx_erp_nume_ptex_tido on erp_doc_numerador (punto_expedicion_id, tipo_documento_id);
create index idx_erp_nume_tipo_documento_id on erp_doc_numerador (tipo_documento_id);

comment on table  erp_doc_numerador is 'Correlativo de comprobantes por timbrado + punto de expedición + tipo de documento (+ serie). Abrev: nume';
comment on column erp_doc_numerador.numerador_id           is 'Identificador técnico (PK, identity)';
comment on column erp_doc_numerador.empresa_id             is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_numerador.timbrado_id            is 'Timbrado (FK erp_doc_timbrado)';
comment on column erp_doc_numerador.punto_expedicion_id    is 'Punto de expedición; el establecimiento sale de su sucursal (FK erp_gen_punto_expedicion)';
comment on column erp_doc_numerador.tipo_documento_id      is 'Tipo de documento (FK erp_doc_tipo_documento)';
comment on column erp_doc_numerador.serie                  is 'Serie de dos letras (AA, AB…); null mientras no se agote la numeración sin serie';
comment on column erp_doc_numerador.numero_desde           is 'Primer número autorizado del rango';
comment on column erp_doc_numerador.numero_hasta           is 'Último número autorizado del rango';
comment on column erp_doc_numerador.numero_actual          is 'Último número tomado (numero_desde - 1 si todavía no se usó ninguno)';
comment on column erp_doc_numerador.dias_aviso_vencimiento is 'Días antes del vencimiento del timbrado en que empieza el aviso';
comment on column erp_doc_numerador.porcentaje_aviso       is 'Porcentaje del rango usado a partir del cual se avisa';
comment on column erp_doc_numerador.es_restringido         is 'S=Solo los usuarios de erp_doc_numerador_usuario pueden tomar números';
comment on column erp_doc_numerador.estado                 is 'A=Activo, I=Inactivo';
comment on column erp_doc_numerador.creado_por             is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_numerador.fecha_creacion         is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_numerador.modificado_por         is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_numerador.fecha_modificacion     is 'Fecha y hora de la última modificación (trigger _bu)';
