-- =============================================================================
-- Tabla  : erp_gen_periodo_habilita   (abrev: peha)
-- Habilita a un usuario a registrar en un período cerrado, hasta una fecha, sin reabrirlo para todos.
-- =============================================================================
create table erp_gen_periodo_habilita (
    periodo_habilita_id  number generated by default on null as identity,
    periodo_id           number         not null,
    usuario_id           number         not null,
    fecha_hasta          date           not null,
    motivo               varchar2(400)  not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_peha primary key (periodo_habilita_id),
    constraint fk_erp_peha_peri foreign key (periodo_id) references erp_gen_periodo (periodo_id) on delete cascade,
    constraint fk_erp_peha_usu foreign key (usuario_id) references adm_seg_usuario (usuario_id) on delete cascade,
    constraint uk_erp_peha_peri_usu unique (periodo_id, usuario_id)
);

-- (periodo_id ya indexado por la PK/UK)
create index idx_erp_peha_usuario_id on erp_gen_periodo_habilita (usuario_id);

comment on table  erp_gen_periodo_habilita is 'Habilita a un usuario a registrar en un período cerrado, hasta una fecha, sin reabrirlo para todos. Abrev: peha';
comment on column erp_gen_periodo_habilita.periodo_habilita_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_periodo_habilita.periodo_id          is 'Período cerrado (FK erp_gen_periodo)';
comment on column erp_gen_periodo_habilita.usuario_id          is 'Usuario habilitado (FK adm_seg_usuario)';
comment on column erp_gen_periodo_habilita.fecha_hasta         is 'Último día de la habilitación';
comment on column erp_gen_periodo_habilita.motivo              is 'Por qué se habilita (queda en la auditoría)';
comment on column erp_gen_periodo_habilita.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_periodo_habilita.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_periodo_habilita.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_periodo_habilita.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
