-- =============================================================================
-- Tabla  : erp_stk_producto_unidad   (abrev: prun)
-- Conversión entre unidades por producto: cuántas unidades base contiene cada unidad alternativa.
-- =============================================================================
create table erp_stk_producto_unidad (
    producto_unidad_id  number generated by default on null as identity,
    producto_id         number         not null,
    unidad_id           number         not null,
    factor              number(18,6)   not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_prun primary key (producto_unidad_id),
    constraint fk_erp_prun_pro foreign key (producto_id) references erp_stk_producto (producto_id) on delete cascade,
    constraint fk_erp_prun_uni foreign key (unidad_id) references erp_stk_unidad (unidad_id),
    constraint uk_erp_prun_pro_uni unique (producto_id, unidad_id),
    constraint ck_erp_prun_factor check (factor > 0),
    constraint ck_erp_prun_estado check (estado in ('A','I'))
);

create index idx_erp_prun_unidad_id on erp_stk_producto_unidad (unidad_id);

comment on table  erp_stk_producto_unidad is 'Conversión entre unidades por producto: cuántas unidades base contiene cada unidad alternativa. Abrev: prun';
comment on column erp_stk_producto_unidad.producto_unidad_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_producto_unidad.producto_id        is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_producto_unidad.unidad_id          is 'Unidad alternativa (FK erp_stk_unidad)';
comment on column erp_stk_producto_unidad.factor             is 'Unidades base que contiene una unidad alternativa';
comment on column erp_stk_producto_unidad.estado             is 'A=Activo, I=Inactivo';
comment on column erp_stk_producto_unidad.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_producto_unidad.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_producto_unidad.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_producto_unidad.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
