-- =============================================================================
-- Tabla  : erp_doc_fe_evento   (abrev: feev)
-- Eventos de documentos electrónicos: cancelación e inutilización (emisor) y notificación,
-- conformidad, disconformidad y desconocimiento (receptor).
-- Manual Técnico SIFEN v150 cap. 11 (pág. 112-123); tipos: campo GDE006 dTiGDE (pág. 121).
-- =============================================================================
create table erp_doc_fe_evento (
    fe_evento_id           number generated by default on null as identity (cache 1000),
    empresa_id             number         not null,
    tipo_evento            number(2)      not null,
    fe_documento_id        number,
    numero_inutilizado_id  number,
    cdc                    varchar2(44),
    motivo                 varchar2(500)  not null,
    fecha_firma            timestamp,
    xml_firmado            clob,
    estado_envio           varchar2(1)    default on null 'P' not null,
    estado_sifen           varchar2(1)    default on null 'N' not null,
    codigo_respuesta       varchar2(4),
    mensaje_respuesta      varchar2(255),
    protocolo              varchar2(15),
    fecha_envio            timestamp,
    fecha_respuesta        timestamp,
    intentos               number(3)      default on null 0 not null,
    proximo_intento        timestamp      default on null localtimestamp,
    ultimo_error           varchar2(1000),
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_feev primary key (fe_evento_id),
    constraint fk_erp_feev_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_feev_fedo foreign key (fe_documento_id) references erp_doc_fe_documento (fe_documento_id),
    constraint fk_erp_feev_nuin foreign key (numero_inutilizado_id) references erp_doc_numero_inutilizado (numero_inutilizado_id),
    constraint ck_erp_feev_tipo_evento check (tipo_evento in (1, 2, 10, 11, 12, 13)),
    constraint ck_erp_feev_referencia check ((tipo_evento = 2 and numero_inutilizado_id is not null)
                                             or (tipo_evento <> 2 and cdc is not null)),
    constraint ck_erp_feev_motivo check (length(trim(motivo)) >= 5),
    constraint ck_erp_feev_estado_envio check (estado_envio in ('P','E','S','T','X','C')),
    constraint ck_erp_feev_estado_sifen check (estado_sifen in ('N','A','R'))
);

create index idx_erp_feev_cola on erp_doc_fe_evento (estado_envio, proximo_intento);
create index idx_erp_feev_empresa_id on erp_doc_fe_evento (empresa_id);
create index idx_erp_feev_fe_documento_id on erp_doc_fe_evento (fe_documento_id);
create index idx_erp_feev_nuin on erp_doc_fe_evento (numero_inutilizado_id);
create index idx_erp_feev_cdc on erp_doc_fe_evento (cdc);

comment on table  erp_doc_fe_evento is 'Eventos de documentos electrónicos: cancelación, inutilización y manifestaciones del receptor. Abrev: feev';
comment on column erp_doc_fe_evento.fe_evento_id          is 'Identificador técnico (PK, identity); también es el Id del evento (rEve)';
comment on column erp_doc_fe_evento.empresa_id            is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_fe_evento.tipo_evento           is '1=Cancelación, 2=Inutilización, 10=Notificación de recepción, 11=Conformidad, 12=Disconformidad, 13=Desconocimiento';
comment on column erp_doc_fe_evento.fe_documento_id       is 'Documento electrónico propio afectado (FK erp_doc_fe_documento)';
comment on column erp_doc_fe_evento.numero_inutilizado_id is 'Rango inutilizado (FK erp_doc_numero_inutilizado), para el evento de inutilización';
comment on column erp_doc_fe_evento.cdc                   is 'CDC del documento afectado (propio o recibido)';
comment on column erp_doc_fe_evento.motivo                is 'Motivo del evento (mOtEve, 5 a 500 caracteres)';
comment on column erp_doc_fe_evento.fecha_firma           is 'Fecha y hora de la firma del evento';
comment on column erp_doc_fe_evento.xml_firmado           is 'XML del evento firmado';
comment on column erp_doc_fe_evento.estado_envio          is 'P=Pendiente, E=Enviado, S=Sin respuesta, T=Error técnico, X=Detenido, C=Concluido';
comment on column erp_doc_fe_evento.estado_sifen          is 'N=Sin resultado, A=Registrado, R=Rechazado';
comment on column erp_doc_fe_evento.codigo_respuesta      is 'Código de respuesta de SIFEN';
comment on column erp_doc_fe_evento.mensaje_respuesta     is 'Mensaje de respuesta de SIFEN';
comment on column erp_doc_fe_evento.protocolo             is 'Número de transacción del registro del evento (dProtAut)';
comment on column erp_doc_fe_evento.fecha_envio           is 'Fecha y hora del último envío';
comment on column erp_doc_fe_evento.fecha_respuesta       is 'Fecha y hora del resultado';
comment on column erp_doc_fe_evento.intentos              is 'Intentos fallidos acumulados';
comment on column erp_doc_fe_evento.proximo_intento       is 'Cuándo puede volver a tomarse de la cola';
comment on column erp_doc_fe_evento.ultimo_error          is 'Último error técnico';
comment on column erp_doc_fe_evento.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_evento.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_evento.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_evento.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
