-- =============================================================================
-- Tabla  : erp_stk_lote   (abrev: lot)
-- Lotes y números de serie de cada producto, con elaboración y vencimiento.
-- =============================================================================
create table erp_stk_lote (
    lote_id             number generated by default on null as identity (cache 1000),
    empresa_id          number         not null,
    producto_id         number         not null,
    codigo              varchar2(50)   not null,
    tipo                varchar2(1)    default on null 'L' not null,
    fecha_elaboracion   date,
    fecha_vencimiento   date,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_lot primary key (lote_id),
    constraint fk_erp_lot_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_lot_pro foreign key (producto_id) references erp_stk_producto (producto_id),
    constraint uk_erp_lot_pro_codigo unique (producto_id, codigo),
    constraint ck_erp_lot_tipo check (tipo in ('L','S')),
    constraint ck_erp_lot_vigencia check (fecha_vencimiento is null or fecha_elaboracion is null or fecha_vencimiento >= fecha_elaboracion),
    constraint ck_erp_lot_estado check (estado in ('A','B','I'))
);

create index idx_erp_lot_emp_vencimiento on erp_stk_lote (empresa_id, fecha_vencimiento);

comment on table  erp_stk_lote is 'Lotes y números de serie de cada producto, con elaboración y vencimiento. Abrev: lot';
comment on column erp_stk_lote.lote_id            is 'Identificador técnico (PK, identity)';
comment on column erp_stk_lote.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_lote.producto_id        is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_lote.codigo             is 'Número de lote o de serie';
comment on column erp_stk_lote.tipo               is 'L=Lote, S=Número de serie (saldo máximo 1)';
comment on column erp_stk_lote.fecha_elaboracion  is 'Fecha de elaboración';
comment on column erp_stk_lote.fecha_vencimiento  is 'Fecha de vencimiento';
comment on column erp_stk_lote.estado             is 'A=Activo, B=Bloqueado (no sale), I=Inactivo';
comment on column erp_stk_lote.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_lote.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_lote.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_lote.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
