-- =============================================================================
-- Tabla  : erp_gen_funcionalidad   (abrev: func)
-- Funcionalidades activables por empresa (lotes, series, safra, vendedores…): adaptan el ERP a cada rubro.
-- =============================================================================
create table erp_gen_funcionalidad (
    funcionalidad_id    number generated by default on null as identity,
    codigo              varchar2(30)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(400),
    modulo              varchar2(3),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_func primary key (funcionalidad_id),
    constraint uk_erp_func_codigo unique (codigo),
    constraint ck_erp_func_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_func_estado check (estado in ('A','I'))
);


comment on table  erp_gen_funcionalidad is 'Funcionalidades activables por empresa (lotes, series, safra, vendedores…): adaptan el ERP a cada rubro. Abrev: func';
comment on column erp_gen_funcionalidad.funcionalidad_id   is 'Identificador técnico (PK, identity)';
comment on column erp_gen_funcionalidad.codigo             is 'Código en mayúsculas (LOTE, SAFRA, VENDEDOR…); lo usan las condiciones de APEX';
comment on column erp_gen_funcionalidad.nombre             is 'Nombre visible';
comment on column erp_gen_funcionalidad.descripcion        is 'Qué habilita en el sistema';
comment on column erp_gen_funcionalidad.modulo             is 'Módulo principal al que afecta (VEN, STK, FIN…)';
comment on column erp_gen_funcionalidad.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_funcionalidad.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_funcionalidad.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_funcionalidad.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_funcionalidad.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
