-- =============================================================================
-- Tabla  : erp_gen_categoria_tasa   (abrev: cata)
-- Tasas que componen una categoría fiscal. Por impuesto, la suma de porcentaje_base no supera 100; el resto es exento.
-- =============================================================================
create table erp_gen_categoria_tasa (
    categoria_tasa_id    number generated by default on null as identity,
    categoria_fiscal_id  number         not null,
    impuesto_tasa_id     number         not null,
    porcentaje_base      number(9,4)    default on null 100 not null,
    orden                number(3)      default on null 1 not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_cata primary key (categoria_tasa_id),
    constraint fk_erp_cata_cafi foreign key (categoria_fiscal_id) references erp_gen_categoria_fiscal (categoria_fiscal_id) on delete cascade,
    constraint fk_erp_cata_imta foreign key (impuesto_tasa_id) references erp_gen_impuesto_tasa (impuesto_tasa_id),
    constraint uk_erp_cata_cafi_tasa unique (categoria_fiscal_id, impuesto_tasa_id),
    constraint ck_erp_cata_porcentaje_base check (porcentaje_base > 0 and porcentaje_base <= 100)
);

-- (categoria_fiscal_id ya indexado por la PK/UK)
create index idx_erp_cata_impuesto_tasa_id on erp_gen_categoria_tasa (impuesto_tasa_id);

comment on table  erp_gen_categoria_tasa is 'Tasas que componen una categoría fiscal. Por impuesto, la suma de porcentaje_base no supera 100; el resto es exento. Abrev: cata';
comment on column erp_gen_categoria_tasa.categoria_tasa_id   is 'Identificador técnico (PK, identity)';
comment on column erp_gen_categoria_tasa.categoria_fiscal_id is 'Categoría fiscal (FK erp_gen_categoria_fiscal)';
comment on column erp_gen_categoria_tasa.impuesto_tasa_id    is 'Tasa aplicada (FK erp_gen_impuesto_tasa)';
comment on column erp_gen_categoria_tasa.porcentaje_base     is 'Porcentaje de la base afectado por la tasa (100 = toda la base)';
comment on column erp_gen_categoria_tasa.orden               is 'Orden de cálculo';
comment on column erp_gen_categoria_tasa.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_categoria_tasa.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_categoria_tasa.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_categoria_tasa.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
