-- =============================================================================
-- Tabla  : erp_stk_producto_deposito   (abrev: prdp)
-- Parámetros del producto en cada depósito: mínimo, máximo, punto de pedido y ubicación habitual.
-- =============================================================================
create table erp_stk_producto_deposito (
    producto_deposito_id   number generated by default on null as identity,
    producto_id            number         not null,
    deposito_id            number         not null,
    stock_minimo           number(18,4),
    stock_maximo           number(18,4),
    punto_pedido           number(18,4),
    deposito_ubicacion_id  number,
    estado                 varchar2(1)    default on null 'A' not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_prdp primary key (producto_deposito_id),
    constraint fk_erp_prdp_pro foreign key (producto_id) references erp_stk_producto (producto_id) on delete cascade,
    constraint fk_erp_prdp_dpo foreign key (deposito_id) references erp_stk_deposito (deposito_id),
    constraint fk_erp_prdp_dpub foreign key (deposito_ubicacion_id) references erp_stk_deposito_ubicacion (deposito_ubicacion_id),
    constraint uk_erp_prdp_pro_dpo unique (producto_id, deposito_id),
    constraint ck_erp_prdp_cantidades check (coalesce(stock_minimo, 0) >= 0 and coalesce(punto_pedido, 0) >= 0 and (stock_maximo is null or stock_maximo >= coalesce(stock_minimo, 0))),
    constraint ck_erp_prdp_estado check (estado in ('A','I'))
);

create index idx_erp_prdp_deposito_id on erp_stk_producto_deposito (deposito_id);
create index idx_erp_prdp_ubicacion on erp_stk_producto_deposito (deposito_ubicacion_id);

comment on table  erp_stk_producto_deposito is 'Parámetros del producto en cada depósito: mínimo, máximo, punto de pedido y ubicación habitual. Abrev: prdp';
comment on column erp_stk_producto_deposito.producto_deposito_id  is 'Identificador técnico (PK, identity)';
comment on column erp_stk_producto_deposito.producto_id           is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_producto_deposito.deposito_id           is 'Depósito (FK erp_stk_deposito)';
comment on column erp_stk_producto_deposito.stock_minimo          is 'Stock mínimo';
comment on column erp_stk_producto_deposito.stock_maximo          is 'Stock máximo';
comment on column erp_stk_producto_deposito.punto_pedido          is 'Saldo disponible por debajo del cual se sugiere reponer';
comment on column erp_stk_producto_deposito.deposito_ubicacion_id is 'Ubicación habitual (FK erp_stk_deposito_ubicacion)';
comment on column erp_stk_producto_deposito.estado                is 'A=Activo, I=Inactivo';
comment on column erp_stk_producto_deposito.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_producto_deposito.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_producto_deposito.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_producto_deposito.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
