-- =============================================================================
-- Tabla  : erp_gen_persona   (abrev: prs)
-- Personas físicas y jurídicas, únicas en el esquema. Cliente, proveedor y empleado son roles por empresa.
-- =============================================================================
create table erp_gen_persona (
    persona_id             number generated by default on null as identity (cache 1000),
    tipo_persona           varchar2(1)    not null,
    tipo_doc_identidad_id  number         not null,
    nro_documento          varchar2(20)   not null,
    dv                     varchar2(1),
    razon_social           varchar2(200)  not null,
    nombres                varchar2(100),
    apellidos              varchar2(100),
    nombre_fantasia        varchar2(200),
    es_contribuyente       varchar2(1)    default on null 'N' not null,
    pais_id                number         not null,
    fecha_nacimiento       date,
    email                  varchar2(200),
    telefono               varchar2(30),
    observacion            varchar2(4000),
    estado                 varchar2(1)    default on null 'A' not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_prs primary key (persona_id),
    constraint fk_erp_prs_tdi foreign key (tipo_doc_identidad_id) references erp_gen_tipo_doc_identidad (tipo_doc_identidad_id),
    constraint fk_erp_prs_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint uk_erp_prs_tdi_nro unique (tipo_doc_identidad_id, nro_documento),
    constraint ck_erp_prs_tipo_persona check (tipo_persona in ('F','J')),
    constraint ck_erp_prs_es_contribuyente check (es_contribuyente in ('S','N')),
    constraint ck_erp_prs_estado check (estado in ('A','I'))
);

-- (tipo_doc_identidad_id ya indexado por la PK/UK)
create index idx_erp_prs_pais_id on erp_gen_persona (pais_id);
create index idx_erp_prs_razon_social on erp_gen_persona (upper(razon_social));

comment on table  erp_gen_persona is 'Personas físicas y jurídicas, únicas en el esquema. Cliente, proveedor y empleado son roles por empresa. Abrev: prs';
comment on column erp_gen_persona.persona_id            is 'Identificador técnico (PK, identity)';
comment on column erp_gen_persona.tipo_persona          is 'F=Física, J=Jurídica';
comment on column erp_gen_persona.tipo_doc_identidad_id is 'Tipo de documento (FK erp_gen_tipo_doc_identidad)';
comment on column erp_gen_persona.nro_documento         is 'Número de documento sin dígito verificador';
comment on column erp_gen_persona.dv                    is 'Dígito verificador (RUC)';
comment on column erp_gen_persona.razon_social          is 'Razón social o nombre completo';
comment on column erp_gen_persona.nombres               is 'Nombres (persona física)';
comment on column erp_gen_persona.apellidos             is 'Apellidos (persona física)';
comment on column erp_gen_persona.nombre_fantasia       is 'Nombre comercial o de fantasía';
comment on column erp_gen_persona.es_contribuyente      is 'S=Contribuyente de IVA (SIFEN iNatRec)';
comment on column erp_gen_persona.pais_id               is 'País de la persona (FK erp_gen_pais)';
comment on column erp_gen_persona.fecha_nacimiento      is 'Fecha de nacimiento o de constitución';
comment on column erp_gen_persona.email                 is 'Correo principal (envío de comprobantes electrónicos)';
comment on column erp_gen_persona.telefono              is 'Teléfono principal';
comment on column erp_gen_persona.observacion           is 'Observaciones';
comment on column erp_gen_persona.estado                is 'A=Activo, I=Inactivo';
comment on column erp_gen_persona.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_persona.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_persona.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_persona.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
