-- =============================================================================
-- Tabla  : erp_stk_traslado   (abrev: tra)
-- Traslados de stock entre depósitos (cabecera): un solo documento con estado, tránsito, transporte y datos de la nota de remisión.
-- =============================================================================
create table erp_stk_traslado (
    traslado_id               number generated by default on null as identity (cache 1000),
    empresa_id                number         not null,
    sucursal_id               number         not null,
    numero                    number         not null,
    tipo                      varchar2(1)    not null,
    motivo_traslado_id        number         not null,
    deposito_id_origen        number         not null,
    deposito_id_transito      number,
    deposito_id_destino       number         not null,
    es_un_paso                varchar2(1)    default on null 'N' not null,
    traslado_id_origen        number,
    relacion                  varchar2(1),
    persona_id_destino        number,
    fecha_emision             date           not null,
    fecha_requerida           date,
    fecha_salida_estimada     timestamp with local time zone,
    fecha_llegada_estimada    timestamp with local time zone,
    fecha_salida_real         timestamp with local time zone,
    fecha_llegada_real        timestamp with local time zone,
    kilometros                number(10,2),
    horas_estimadas           number(8,2),
    vehiculo_id               number,
    persona_id_transportista  number,
    persona_id_conductor      number,
    vehiculo_chapa            varchar2(20),
    vehiculo_marca            varchar2(50),
    vehiculo_tipo             varchar2(30),
    conductor_nombre          varchar2(200),
    conductor_documento       varchar2(20),
    tipo_transporte           varchar2(1),
    modalidad_transporte      varchar2(1)   default on null 'T' not null,
    responsable_emision       number(1),
    punto_expedicion_id       number,
    remision_estado           varchar2(1)   default on null 'N' not null,
    remision_numero           varchar2(15),
    remision_cdc              varchar2(44),
    remision_documento_id     number,
    monto_flete               number(18,2)   default on null 0 not null,
    es_flete_capitalizable    varchar2(1)    default on null 'N' not null,
    usuario_solicita          varchar2(100),
    fecha_solicitud           timestamp with local time zone,
    usuario_aprueba           varchar2(100),
    fecha_aprobacion          timestamp with local time zone,
    usuario_despacha          varchar2(100),
    motivo_rechazo            varchar2(400),
    motivo_anulacion          varchar2(400),
    movimiento_id_despacho    number,
    observacion               varchar2(4000),
    estado                    varchar2(1)    default on null 'B' not null,
    creado_por                varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion            timestamp with local time zone default on null systimestamp not null,
    modificado_por            varchar2(100),
    fecha_modificacion        timestamp with local time zone,
    constraint pk_erp_tra primary key (traslado_id),
    constraint fk_erp_tra_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_tra_suc foreign key (sucursal_id) references erp_gen_sucursal (sucursal_id),
    constraint fk_erp_tra_motr foreign key (motivo_traslado_id) references erp_stk_motivo_traslado (motivo_traslado_id),
    constraint fk_erp_tra_dpo_origen foreign key (deposito_id_origen) references erp_stk_deposito (deposito_id),
    constraint fk_erp_tra_dpo_transito foreign key (deposito_id_transito) references erp_stk_deposito (deposito_id),
    constraint fk_erp_tra_dpo_destino foreign key (deposito_id_destino) references erp_stk_deposito (deposito_id),
    constraint fk_erp_tra_tra_origen foreign key (traslado_id_origen) references erp_stk_traslado (traslado_id),
    constraint fk_erp_tra_prs_destino foreign key (persona_id_destino) references erp_gen_persona (persona_id),
    constraint fk_erp_tra_veh foreign key (vehiculo_id) references erp_stk_vehiculo (vehiculo_id),
    constraint fk_erp_tra_prs_transp foreign key (persona_id_transportista) references erp_gen_persona (persona_id),
    constraint fk_erp_tra_prs_conductor foreign key (persona_id_conductor) references erp_gen_persona (persona_id),
    constraint fk_erp_tra_ptex foreign key (punto_expedicion_id) references erp_gen_punto_expedicion (punto_expedicion_id),
    constraint fk_erp_tra_mov_despacho foreign key (movimiento_id_despacho) references erp_stk_movimiento (movimiento_id),
    constraint uk_erp_tra_emp_suc_numero unique (empresa_id, sucursal_id, numero),
    constraint ck_erp_tra_tipo check (tipo in ('I','R','T')),
    constraint ck_erp_tra_depositos check (deposito_id_origen <> deposito_id_destino),
    constraint ck_erp_tra_es_un_paso check (es_un_paso in ('S','N')),
    constraint ck_erp_tra_un_paso check ((es_un_paso = 'S' and tipo = 'I' and deposito_id_transito is null) or (es_un_paso = 'N' and deposito_id_transito is not null)),
    constraint ck_erp_tra_relacion check ((traslado_id_origen is null and relacion is null) or (traslado_id_origen is not null and relacion in ('D','C'))),
    constraint ck_erp_tra_fechas_estimadas check (fecha_llegada_estimada is null or fecha_salida_estimada is null or fecha_llegada_estimada >= fecha_salida_estimada),
    constraint ck_erp_tra_fechas_reales check (fecha_llegada_real is null or fecha_salida_real is null or fecha_llegada_real >= fecha_salida_real),
    constraint ck_erp_tra_tipo_transporte check (tipo_transporte in ('P','T')),
    constraint ck_erp_tra_modalidad check (modalidad_transporte in ('T','F','A','M')),
    constraint ck_erp_tra_responsable check (responsable_emision between 1 and 5),
    constraint ck_erp_tra_remision_estado check (remision_estado in ('N','P','G','C')),
    constraint ck_erp_tra_flete check (monto_flete >= 0),
    constraint ck_erp_tra_es_flete_cap check (es_flete_capitalizable in ('S','N')),
    constraint ck_erp_tra_estado check (estado in ('B','S','P','T','R','D','C','X','A'))
);

create index idx_erp_tra_emp_estado_fecha on erp_stk_traslado (empresa_id, estado, fecha_emision);
create index idx_erp_tra_sucursal_id on erp_stk_traslado (sucursal_id);
create index idx_erp_tra_motivo_traslado on erp_stk_traslado (motivo_traslado_id);
create index idx_erp_tra_deposito_origen on erp_stk_traslado (deposito_id_origen);
create index idx_erp_tra_deposito_transito on erp_stk_traslado (deposito_id_transito);
create index idx_erp_tra_deposito_destino on erp_stk_traslado (deposito_id_destino);
create index idx_erp_tra_traslado_origen on erp_stk_traslado (traslado_id_origen);
create index idx_erp_tra_persona_destino on erp_stk_traslado (persona_id_destino);
create index idx_erp_tra_vehiculo_id on erp_stk_traslado (vehiculo_id);
create index idx_erp_tra_transportista on erp_stk_traslado (persona_id_transportista);
create index idx_erp_tra_conductor on erp_stk_traslado (persona_id_conductor);
create index idx_erp_tra_punto_expedicion on erp_stk_traslado (punto_expedicion_id);
create index idx_erp_tra_mov_despacho on erp_stk_traslado (movimiento_id_despacho);

comment on table  erp_stk_traslado is 'Traslados de stock entre depósitos (cabecera): un solo documento con estado, tránsito, transporte y datos de la nota de remisión. Abrev: tra';
comment on column erp_stk_traslado.traslado_id              is 'Identificador técnico (PK, identity)';
comment on column erp_stk_traslado.empresa_id               is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_traslado.sucursal_id              is 'Sucursal de origen; define la numeración (FK erp_gen_sucursal)';
comment on column erp_stk_traslado.numero                   is 'Número interno por empresa y sucursal de origen';
comment on column erp_stk_traslado.tipo                     is 'I=Interno sin remisión, R=Con remisión entre locales, T=A terceros';
comment on column erp_stk_traslado.motivo_traslado_id       is 'Motivo (FK erp_stk_motivo_traslado)';
comment on column erp_stk_traslado.deposito_id_origen       is 'Depósito de salida (FK erp_stk_deposito)';
comment on column erp_stk_traslado.deposito_id_transito     is 'Depósito de tránsito de la sucursal de origen; null si es de un paso (FK erp_stk_deposito)';
comment on column erp_stk_traslado.deposito_id_destino      is 'Depósito de llegada (FK erp_stk_deposito)';
comment on column erp_stk_traslado.es_un_paso               is 'S=Interno de un paso: sale y entra en el mismo movimiento';
comment on column erp_stk_traslado.traslado_id_origen       is 'Traslado del que nace (devolución o complemento) (FK erp_stk_traslado)';
comment on column erp_stk_traslado.relacion                 is 'Con el traslado de origen: D=Devolución, C=Complemento de un despacho parcial';
comment on column erp_stk_traslado.persona_id_destino       is 'Tercero que recibe, en traslados de tipo T (FK erp_gen_persona)';
comment on column erp_stk_traslado.fecha_emision            is 'Fecha del documento';
comment on column erp_stk_traslado.fecha_requerida          is 'Fecha en que el destino necesita la mercadería';
comment on column erp_stk_traslado.fecha_salida_estimada    is 'Salida estimada';
comment on column erp_stk_traslado.fecha_llegada_estimada   is 'Llegada estimada (salida más horas de la ruta)';
comment on column erp_stk_traslado.fecha_salida_real        is 'Despacho real';
comment on column erp_stk_traslado.fecha_llegada_real       is 'Última recepción';
comment on column erp_stk_traslado.kilometros               is 'Kilómetros estimados de recorrido (SIFEN dKmR)';
comment on column erp_stk_traslado.horas_estimadas          is 'Horas estimadas de viaje (sugeridas por la ruta)';
comment on column erp_stk_traslado.vehiculo_id              is 'Vehículo (FK erp_stk_vehiculo)';
comment on column erp_stk_traslado.persona_id_transportista is 'Transportista (FK erp_gen_persona)';
comment on column erp_stk_traslado.persona_id_conductor     is 'Conductor (FK erp_gen_persona)';
comment on column erp_stk_traslado.vehiculo_chapa           is 'Foto: chapa del vehículo al despachar';
comment on column erp_stk_traslado.vehiculo_marca           is 'Foto: marca del vehículo';
comment on column erp_stk_traslado.vehiculo_tipo            is 'Foto: tipo de vehículo';
comment on column erp_stk_traslado.conductor_nombre         is 'Foto: nombre del conductor al despachar';
comment on column erp_stk_traslado.conductor_documento      is 'Foto: documento del conductor';
comment on column erp_stk_traslado.tipo_transporte          is 'P=Propio, T=Tercero (SIFEN iTipTrans)';
comment on column erp_stk_traslado.modalidad_transporte     is 'T=Terrestre, F=Fluvial, A=Aéreo, M=Multimodal (SIFEN iModTrans)';
comment on column erp_stk_traslado.responsable_emision      is 'Responsable de la emisión de la remisión (SIFEN iRespEmiNR)';
comment on column erp_stk_traslado.punto_expedicion_id      is 'Punto de expedición que emite la remisión (FK erp_gen_punto_expedicion)';
comment on column erp_stk_traslado.remision_estado          is 'N=No aplica, P=Pendiente de emitir, G=Generada, C=Cancelada';
comment on column erp_stk_traslado.remision_numero          is 'Número fiscal de la remisión (001-001-0000001)';
comment on column erp_stk_traslado.remision_cdc             is 'Código de control del documento electrónico';
comment on column erp_stk_traslado.remision_documento_id    is 'Identificador del documento electrónico en el módulo de documentos';
comment on column erp_stk_traslado.monto_flete              is 'Costo del flete en moneda funcional';
comment on column erp_stk_traslado.es_flete_capitalizable   is 'S=El flete se suma al costo de entrada en destino';
comment on column erp_stk_traslado.usuario_solicita         is 'Usuario que solicitó';
comment on column erp_stk_traslado.fecha_solicitud          is 'Fecha de la solicitud';
comment on column erp_stk_traslado.usuario_aprueba          is 'Usuario que aprobó o rechazó';
comment on column erp_stk_traslado.fecha_aprobacion         is 'Fecha de la aprobación o del rechazo';
comment on column erp_stk_traslado.usuario_despacha         is 'Usuario que despachó';
comment on column erp_stk_traslado.motivo_rechazo           is 'Motivo del rechazo';
comment on column erp_stk_traslado.motivo_anulacion         is 'Motivo de la anulación';
comment on column erp_stk_traslado.movimiento_id_despacho   is 'Movimiento de stock del despacho (FK erp_stk_movimiento)';
comment on column erp_stk_traslado.observacion              is 'Observación';
comment on column erp_stk_traslado.estado                   is 'B=Borrador, S=Solicitado, P=Aprobado, T=En tránsito, R=Recibido parcial, D=Con diferencias, C=Completado, X=Rechazado, A=Anulado';
comment on column erp_stk_traslado.creado_por               is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_traslado.fecha_creacion           is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_traslado.modificado_por           is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_traslado.fecha_modificacion       is 'Fecha y hora de la última modificación (trigger _bu)';
