-- =============================================================================
-- Tabla  : erp_stk_traslado_recep_det   (abrev: trrd)
-- Detalle de cada recepción: recibido, dañado, faltante y sobrante por ítem, y cómo se resolvió el faltante.
-- =============================================================================
create table erp_stk_traslado_recep_det (
    traslado_recep_det_id     number generated by default on null as identity (cache 1000),
    traslado_recep_id         number         not null,
    traslado_item_id          number         not null,
    cantidad_recibida         number(18,4)   default on null 0 not null,
    cantidad_averiada         number(18,4)   default on null 0 not null,
    cantidad_faltante         number(18,4)   default on null 0 not null,
    cantidad_sobrante         number(18,4)   default on null 0 not null,
    resolucion                varchar2(1),
    fecha_resolucion          timestamp with local time zone,
    usuario_resuelve          varchar2(100),
    persona_id_responsable    number,
    movimiento_id_resolucion  number,
    observacion               varchar2(400),
    creado_por                varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion            timestamp with local time zone default on null systimestamp not null,
    modificado_por            varchar2(100),
    fecha_modificacion        timestamp with local time zone,
    constraint pk_erp_trrd primary key (traslado_recep_det_id),
    constraint fk_erp_trrd_trre foreign key (traslado_recep_id) references erp_stk_traslado_recep (traslado_recep_id),
    constraint fk_erp_trrd_trit foreign key (traslado_item_id) references erp_stk_traslado_item (traslado_item_id),
    constraint fk_erp_trrd_prs_responsable foreign key (persona_id_responsable) references erp_gen_persona (persona_id),
    constraint fk_erp_trrd_mov_resolucion foreign key (movimiento_id_resolucion) references erp_stk_movimiento (movimiento_id),
    constraint uk_erp_trrd_trre_trit unique (traslado_recep_id, traslado_item_id),
    constraint ck_erp_trrd_cantidades check (cantidad_recibida >= 0 and cantidad_averiada >= 0 and cantidad_faltante >= 0 and cantidad_sobrante >= 0),
    constraint ck_erp_trrd_resolucion check (resolucion in ('P','D','R','M'))
);

create index idx_erp_trrd_traslado_item on erp_stk_traslado_recep_det (traslado_item_id);
create index idx_erp_trrd_responsable on erp_stk_traslado_recep_det (persona_id_responsable);
create index idx_erp_trrd_mov_resolucion on erp_stk_traslado_recep_det (movimiento_id_resolucion);

comment on table  erp_stk_traslado_recep_det is 'Detalle de cada recepción: recibido, dañado, faltante y sobrante por ítem, y cómo se resolvió el faltante. Abrev: trrd';
comment on column erp_stk_traslado_recep_det.traslado_recep_det_id    is 'Identificador técnico (PK, identity)';
comment on column erp_stk_traslado_recep_det.traslado_recep_id        is 'Recepción (FK erp_stk_traslado_recep)';
comment on column erp_stk_traslado_recep_det.traslado_item_id         is 'Ítem del traslado (FK erp_stk_traslado_item)';
comment on column erp_stk_traslado_recep_det.cantidad_recibida        is 'Recibido conforme';
comment on column erp_stk_traslado_recep_det.cantidad_averiada        is 'Recibido con daños (a cuarentena)';
comment on column erp_stk_traslado_recep_det.cantidad_faltante        is 'Faltante declarado';
comment on column erp_stk_traslado_recep_det.cantidad_sobrante        is 'Sobrante informado (no entra al stock: requiere un despacho complementario)';
comment on column erp_stk_traslado_recep_det.resolucion               is 'Del faltante: null=Pendiente, P=Pérdida, D=Devolución al origen, R=Recepción posterior, M=Merma dentro de la tolerancia';
comment on column erp_stk_traslado_recep_det.fecha_resolucion         is 'Fecha de la resolución';
comment on column erp_stk_traslado_recep_det.usuario_resuelve         is 'Usuario que resolvió';
comment on column erp_stk_traslado_recep_det.persona_id_responsable   is 'Responsable de la pérdida (FK erp_gen_persona)';
comment on column erp_stk_traslado_recep_det.movimiento_id_resolucion is 'Movimiento de stock de la resolución (FK erp_stk_movimiento)';
comment on column erp_stk_traslado_recep_det.observacion              is 'Observación';
comment on column erp_stk_traslado_recep_det.creado_por               is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_traslado_recep_det.fecha_creacion           is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_traslado_recep_det.modificado_por           is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_traslado_recep_det.fecha_modificacion       is 'Fecha y hora de la última modificación (trigger _bu)';
