-- =============================================================================
-- Tabla  : erp_gen_persona_contacto   (abrev: prco)
-- Medios de contacto de una persona (teléfonos, correos) y personas de contacto.
-- =============================================================================
create table erp_gen_persona_contacto (
    persona_contacto_id  number generated by default on null as identity (cache 1000),
    persona_id           number         not null,
    tipo                 varchar2(3)    not null,
    valor                varchar2(200)  not null,
    nombre_contacto      varchar2(100),
    cargo                varchar2(100),
    es_principal         varchar2(1)    default on null 'N' not null,
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_prco primary key (persona_contacto_id),
    constraint fk_erp_prco_prs foreign key (persona_id) references erp_gen_persona (persona_id) on delete cascade,
    constraint ck_erp_prco_tipo check (tipo in ('TEL','CEL','EML','WEB')),
    constraint ck_erp_prco_es_principal check (es_principal in ('S','N')),
    constraint ck_erp_prco_estado check (estado in ('A','I'))
);

create index idx_erp_prco_persona_id on erp_gen_persona_contacto (persona_id);

comment on table  erp_gen_persona_contacto is 'Medios de contacto de una persona (teléfonos, correos) y personas de contacto. Abrev: prco';
comment on column erp_gen_persona_contacto.persona_contacto_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_persona_contacto.persona_id          is 'Persona (FK erp_gen_persona)';
comment on column erp_gen_persona_contacto.tipo                is 'TEL=Teléfono, CEL=Celular, EML=Correo, WEB=Sitio web';
comment on column erp_gen_persona_contacto.valor               is 'Número, correo o URL';
comment on column erp_gen_persona_contacto.nombre_contacto     is 'Nombre de la persona de contacto';
comment on column erp_gen_persona_contacto.cargo               is 'Cargo de la persona de contacto';
comment on column erp_gen_persona_contacto.es_principal        is 'S=Contacto principal de su tipo';
comment on column erp_gen_persona_contacto.estado              is 'A=Activo, I=Inactivo';
comment on column erp_gen_persona_contacto.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_persona_contacto.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_persona_contacto.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_persona_contacto.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
