-- =============================================================================
-- Tabla  : erp_gen_parametro   (abrev: par)
-- Parámetros del ERP (clave/valor tipado). Valor por empresa o general (empresa null).
-- =============================================================================
create table erp_gen_parametro (
    parametro_id        number generated by default on null as identity,
    empresa_id          number,
    codigo              varchar2(60)   not null,
    valor               varchar2(4000),
    tipo_dato           varchar2(1)    default on null 'T' not null,
    descripcion         varchar2(400),
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_par primary key (parametro_id),
    constraint fk_erp_par_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_par_codigo_emp unique (codigo, empresa_id),
    constraint ck_erp_par_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_par_tipo_dato check (tipo_dato in ('T','N','F','S'))
);

create index idx_erp_par_empresa_id on erp_gen_parametro (empresa_id);

comment on table  erp_gen_parametro is 'Parámetros del ERP (clave/valor tipado). Valor por empresa o general (empresa null). Abrev: par';
comment on column erp_gen_parametro.parametro_id       is 'Identificador técnico (PK, identity)';
comment on column erp_gen_parametro.empresa_id         is 'Empresa; null = valor general por defecto (FK adm_gen_empresa)';
comment on column erp_gen_parametro.codigo             is 'Código del parámetro en mayúsculas';
comment on column erp_gen_parametro.valor              is 'Valor (fechas en formato AAAA-MM-DD, S/N para indicadores)';
comment on column erp_gen_parametro.tipo_dato          is 'T=Texto, N=Número, F=Fecha, S=Sí/No';
comment on column erp_gen_parametro.descripcion        is 'Para qué sirve';
comment on column erp_gen_parametro.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_parametro.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_parametro.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_parametro.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
