-- =============================================================================
-- Tabla  : erp_stk_producto_codigo   (abrev: prcd)
-- Códigos alternativos del producto: barras de unidad y de bulto, código del proveedor y código en sistemas externos.
-- =============================================================================
create table erp_stk_producto_codigo (
    producto_codigo_id  number generated by default on null as identity (cache 1000),
    empresa_id          number         not null,
    producto_id         number         not null,
    tipo                varchar2(1)    not null,
    valor               varchar2(60)   not null,
    unidad_id           number,
    factor              number(18,6),
    persona_id          number,
    sistema             varchar2(30),
    es_principal        varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_prcd primary key (producto_codigo_id),
    constraint fk_erp_prcd_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_prcd_pro foreign key (producto_id) references erp_stk_producto (producto_id) on delete cascade,
    constraint fk_erp_prcd_uni foreign key (unidad_id) references erp_stk_unidad (unidad_id),
    constraint fk_erp_prcd_prs foreign key (persona_id) references erp_gen_persona (persona_id),
    constraint ck_erp_prcd_tipo check (tipo in ('B','C','P','E')),
    constraint ck_erp_prcd_es_principal check (es_principal in ('S','N')),
    constraint ck_erp_prcd_factor check (factor > 0),
    constraint ck_erp_prcd_estado check (estado in ('A','I'))
);

create unique index uk_erp_prcd_emp_tipo_valor on erp_stk_producto_codigo (empresa_id, tipo, valor, coalesce(persona_id, 0), coalesce(sistema, '-'));
create index idx_erp_prcd_producto_id on erp_stk_producto_codigo (producto_id);
create index idx_erp_prcd_unidad_id on erp_stk_producto_codigo (unidad_id);
create index idx_erp_prcd_persona_id on erp_stk_producto_codigo (persona_id);
create index idx_erp_prcd_emp_valor on erp_stk_producto_codigo (empresa_id, valor);

comment on table  erp_stk_producto_codigo is 'Códigos alternativos del producto: barras de unidad y de bulto, código del proveedor y código en sistemas externos. Abrev: prcd';
comment on column erp_stk_producto_codigo.producto_codigo_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_producto_codigo.empresa_id         is 'Empresa (FK adm_gen_empresa); el código es único por empresa y tipo';
comment on column erp_stk_producto_codigo.producto_id        is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_producto_codigo.tipo               is 'B=Barras de la unidad, C=Barras del bulto o caja, P=Código del proveedor, E=Código en un sistema externo';
comment on column erp_stk_producto_codigo.valor              is 'Código';
comment on column erp_stk_producto_codigo.unidad_id          is 'Unidad que identifica el código (bulto, caja…) (FK erp_stk_unidad)';
comment on column erp_stk_producto_codigo.factor             is 'Unidades base que contiene el bulto identificado por el código';
comment on column erp_stk_producto_codigo.persona_id         is 'Proveedor dueño del código, para el tipo P (FK erp_gen_persona)';
comment on column erp_stk_producto_codigo.sistema            is 'Sistema externo, para el tipo E';
comment on column erp_stk_producto_codigo.es_principal       is 'S=Código que se imprime por defecto';
comment on column erp_stk_producto_codigo.estado             is 'A=Activo, I=Inactivo';
comment on column erp_stk_producto_codigo.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_producto_codigo.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_producto_codigo.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_producto_codigo.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
