-- =============================================================================
-- Tabla  : erp_doc_numerador_usuario   (abrev: nuus)
-- Usuarios autorizados a tomar números de un numerador restringido.
-- =============================================================================
create table erp_doc_numerador_usuario (
    numerador_usuario_id  number generated by default on null as identity,
    numerador_id          number         not null,
    usuario_id            number         not null,
    estado                varchar2(1)    default on null 'A' not null,
    creado_por            varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion        timestamp with local time zone default on null systimestamp not null,
    modificado_por        varchar2(100),
    fecha_modificacion    timestamp with local time zone,
    constraint pk_erp_nuus primary key (numerador_usuario_id),
    -- al eliminar el numerador o el usuario se elimina la autorización
    constraint fk_erp_nuus_nume foreign key (numerador_id) references erp_doc_numerador (numerador_id) on delete cascade,
    constraint fk_erp_nuus_usu foreign key (usuario_id) references adm_seg_usuario (usuario_id) on delete cascade,
    constraint uk_erp_nuus_nume_usu unique (numerador_id, usuario_id),
    constraint ck_erp_nuus_estado check (estado in ('A','I'))
);

-- (numerador_id ya indexado por la PK/UK)
create index idx_erp_nuus_usuario_id on erp_doc_numerador_usuario (usuario_id);

comment on table  erp_doc_numerador_usuario is 'Usuarios autorizados a tomar números de un numerador restringido. Abrev: nuus';
comment on column erp_doc_numerador_usuario.numerador_usuario_id is 'Identificador técnico (PK, identity)';
comment on column erp_doc_numerador_usuario.numerador_id         is 'Numerador (FK erp_doc_numerador)';
comment on column erp_doc_numerador_usuario.usuario_id           is 'Usuario autorizado (FK adm_seg_usuario)';
comment on column erp_doc_numerador_usuario.estado               is 'A=Activo, I=Inactivo';
comment on column erp_doc_numerador_usuario.creado_por           is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_numerador_usuario.fecha_creacion       is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_numerador_usuario.modificado_por       is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_numerador_usuario.fecha_modificacion   is 'Fecha y hora de la última modificación (trigger _bu)';
