-- =============================================================================
-- Tabla  : erp_gen_impuesto   (abrev: imp)
-- Impuestos, retenciones y percepciones por país (IVA, ISC, IRE…).
-- =============================================================================
create table erp_gen_impuesto (
    impuesto_id         number generated by default on null as identity,
    pais_id             number         not null,
    codigo              varchar2(10)   not null,
    nombre              varchar2(100)  not null,
    tipo                varchar2(1)    default on null 'I' not null,
    codigo_oficial      varchar2(5),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_imp primary key (impuesto_id),
    constraint fk_erp_imp_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint uk_erp_imp_pais_codigo unique (pais_id, codigo),
    constraint ck_erp_imp_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_imp_tipo check (tipo in ('I','R','P')),
    constraint ck_erp_imp_estado check (estado in ('A','I'))
);

-- (pais_id ya indexado por la PK/UK)

comment on table  erp_gen_impuesto is 'Impuestos, retenciones y percepciones por país (IVA, ISC, IRE…). Abrev: imp';
comment on column erp_gen_impuesto.impuesto_id        is 'Identificador técnico (PK, identity)';
comment on column erp_gen_impuesto.pais_id            is 'País (FK erp_gen_pais)';
comment on column erp_gen_impuesto.codigo             is 'Código corto (IVA, ISC, RET_IVA…)';
comment on column erp_gen_impuesto.nombre             is 'Nombre del impuesto';
comment on column erp_gen_impuesto.tipo               is 'I=Impuesto, R=Retención, P=Percepción';
comment on column erp_gen_impuesto.codigo_oficial     is 'Código oficial (SIFEN iTImp: 1=IVA, 2=ISC, 3=Renta, 4=Ninguno, 5=IVA-Renta)';
comment on column erp_gen_impuesto.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_impuesto.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_impuesto.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_impuesto.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_impuesto.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
