-- =============================================================================
-- Tabla  : erp_stk_vehiculo   (abrev: veh)
-- Vehículos de transporte por empresa, con su transportista y conductor habituales (nota de remisión).
-- =============================================================================
create table erp_stk_vehiculo (
    vehiculo_id               number generated by default on null as identity,
    empresa_id                number         not null,
    chapa                     varchar2(20)   not null,
    tipo                      varchar2(30),
    marca                     varchar2(50),
    capacidad                 number(18,4),
    tara                      number(18,4),
    tolerancia_tara           number(18,4),
    persona_id_transportista  number,
    persona_id_conductor      number,
    es_generico               varchar2(1)    default on null 'N' not null,
    estado                    varchar2(1)    default on null 'A' not null,
    creado_por                varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion            timestamp with local time zone default on null systimestamp not null,
    modificado_por            varchar2(100),
    fecha_modificacion        timestamp with local time zone,
    constraint pk_erp_veh primary key (vehiculo_id),
    constraint fk_erp_veh_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_veh_prs_transp foreign key (persona_id_transportista) references erp_gen_persona (persona_id),
    constraint fk_erp_veh_prs_conductor foreign key (persona_id_conductor) references erp_gen_persona (persona_id),
    constraint uk_erp_veh_emp_chapa unique (empresa_id, chapa),
    constraint ck_erp_veh_chapa_mayus check (chapa = upper(chapa)),
    constraint ck_erp_veh_es_generico check (es_generico in ('S','N')),
    constraint ck_erp_veh_pesos check (coalesce(capacidad, 0) >= 0 and coalesce(tara, 0) >= 0 and coalesce(tolerancia_tara, 0) >= 0),
    constraint ck_erp_veh_estado check (estado in ('A','I'))
);

create index idx_erp_veh_transportista on erp_stk_vehiculo (persona_id_transportista);
create index idx_erp_veh_conductor on erp_stk_vehiculo (persona_id_conductor);

comment on table  erp_stk_vehiculo is 'Vehículos de transporte por empresa, con su transportista y conductor habituales (nota de remisión). Abrev: veh';
comment on column erp_stk_vehiculo.vehiculo_id              is 'Identificador técnico (PK, identity)';
comment on column erp_stk_vehiculo.empresa_id               is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_vehiculo.chapa                    is 'Chapa o matrícula en mayúsculas, única por empresa';
comment on column erp_stk_vehiculo.tipo                     is 'Tipo de vehículo (camión, furgón, camioneta…)';
comment on column erp_stk_vehiculo.marca                    is 'Marca';
comment on column erp_stk_vehiculo.capacidad                is 'Capacidad de carga (kg)';
comment on column erp_stk_vehiculo.tara                     is 'Tara (kg)';
comment on column erp_stk_vehiculo.tolerancia_tara          is 'Diferencia de tara admitida en el pesaje (kg)';
comment on column erp_stk_vehiculo.persona_id_transportista is 'Transportista habitual (FK erp_gen_persona)';
comment on column erp_stk_vehiculo.persona_id_conductor     is 'Conductor habitual (FK erp_gen_persona)';
comment on column erp_stk_vehiculo.es_generico              is 'S=Vehículo genérico para transportes ocasionales: la chapa real se carga en cada traslado';
comment on column erp_stk_vehiculo.estado                   is 'A=Activo, I=Inactivo';
comment on column erp_stk_vehiculo.creado_por               is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_vehiculo.fecha_creacion           is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_vehiculo.modificado_por           is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_vehiculo.fecha_modificacion       is 'Fecha y hora de la última modificación (trigger _bu)';
