-- =============================================================================
-- Tabla  : erp_gen_ubicacion   (abrev: ubi)
-- Ubicación geográfica jerárquica por país (departamento, distrito, ciudad) con código oficial.
-- =============================================================================
create table erp_gen_ubicacion (
    ubicacion_id        number generated by default on null as identity,
    pais_id             number         not null,
    ubicacion_id_padre  number,
    tipo                varchar2(3)    not null,
    codigo_oficial      varchar2(20)   not null,
    nombre              varchar2(150)  not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_ubi primary key (ubicacion_id),
    constraint fk_erp_ubi_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint fk_erp_ubi_ubi_padre foreign key (ubicacion_id_padre) references erp_gen_ubicacion (ubicacion_id),
    constraint uk_erp_ubi_pais_tipo_codigo unique (pais_id, tipo, codigo_oficial),
    constraint ck_erp_ubi_tipo check (tipo in ('DEP','DIS','CIU')),
    constraint ck_erp_ubi_estado check (estado in ('A','I'))
);

-- (pais_id ya indexado por la PK/UK)
create index idx_erp_ubi_ubicacion_id_padre on erp_gen_ubicacion (ubicacion_id_padre);

comment on table  erp_gen_ubicacion is 'Ubicación geográfica jerárquica por país (departamento, distrito, ciudad) con código oficial. Abrev: ubi';
comment on column erp_gen_ubicacion.ubicacion_id       is 'Identificador técnico (PK, identity)';
comment on column erp_gen_ubicacion.pais_id            is 'País (FK erp_gen_pais)';
comment on column erp_gen_ubicacion.ubicacion_id_padre is 'Ubicación superior (FK erp_gen_ubicacion); null = primer nivel';
comment on column erp_gen_ubicacion.tipo               is 'DEP=Departamento/estado, DIS=Distrito/municipio, CIU=Ciudad/localidad';
comment on column erp_gen_ubicacion.codigo_oficial     is 'Código oficial (tabla de SIFEN/DNIT para Paraguay)';
comment on column erp_gen_ubicacion.nombre             is 'Nombre';
comment on column erp_gen_ubicacion.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_ubicacion.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_ubicacion.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_ubicacion.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_ubicacion.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
