-- =============================================================================
-- Tabla  : erp_stk_categoria   (abrev: ctg)
-- Categorías de producto en árbol, con línea de negocio, grupo contable por defecto y definición de atributos por rubro.
-- =============================================================================
create table erp_stk_categoria (
    categoria_id        number generated by default on null as identity,
    empresa_id          number         not null,
    categoria_id_padre  number,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    linea_negocio       varchar2(30),
    grupo_contable      varchar2(30),
    atributos_def       varchar2(4000),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_ctg primary key (categoria_id),
    constraint fk_erp_ctg_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_ctg_ctg_padre foreign key (categoria_id_padre) references erp_stk_categoria (categoria_id),
    constraint uk_erp_ctg_emp_codigo unique (empresa_id, codigo),
    constraint ck_erp_ctg_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_ctg_padre check (categoria_id_padre is null or categoria_id_padre <> categoria_id),
    constraint ck_erp_ctg_atributos_json check (atributos_def is json),
    constraint ck_erp_ctg_estado check (estado in ('A','I'))
);

create index idx_erp_ctg_categoria_id_padre on erp_stk_categoria (categoria_id_padre);

comment on table  erp_stk_categoria is 'Categorías de producto en árbol, con línea de negocio, grupo contable por defecto y definición de atributos por rubro. Abrev: ctg';
comment on column erp_stk_categoria.categoria_id       is 'Identificador técnico (PK, identity)';
comment on column erp_stk_categoria.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_categoria.categoria_id_padre is 'Categoría padre; null = raíz (FK erp_stk_categoria)';
comment on column erp_stk_categoria.codigo             is 'Código en mayúsculas, único por empresa';
comment on column erp_stk_categoria.nombre             is 'Nombre';
comment on column erp_stk_categoria.linea_negocio      is 'Línea de negocio para reportes y reglas contables (se hereda del padre si está vacía)';
comment on column erp_stk_categoria.grupo_contable     is 'Grupo contable por defecto para las reglas contables (se hereda del padre si está vacío)';
comment on column erp_stk_categoria.atributos_def      is 'Definición JSON de los atributos adicionales de sus productos: [{codigo,nombre,tipo T/N/F/S,requerido S/N,valores[]}]';
comment on column erp_stk_categoria.estado             is 'A=Activo, I=Inactivo';
comment on column erp_stk_categoria.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_categoria.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_categoria.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_categoria.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
