-- =============================================================================
-- Tabla  : erp_doc_clase_documento   (abrev: cldo)
-- Catálogo global de sistema con las clases de documento (factura, nota de crédito, recibo…).
-- Es lo ÚNICO que el código puede consultar: nunca se compara por código de tipo de documento.
-- =============================================================================
create table erp_doc_clase_documento (
    clase_documento_id  number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(400),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_cldo primary key (clase_documento_id),
    constraint uk_erp_cldo_codigo unique (codigo),
    constraint ck_erp_cldo_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_cldo_estado check (estado in ('A','I'))
);

comment on table  erp_doc_clase_documento is 'Catálogo global de sistema con las clases de documento; lo único que el código puede consultar. Abrev: cldo';
comment on column erp_doc_clase_documento.clase_documento_id is 'Identificador técnico (PK, identity)';
comment on column erp_doc_clase_documento.codigo             is 'Código de sistema en mayúsculas (FACTURA, NOTA_CREDITO, RECIBO…)';
comment on column erp_doc_clase_documento.nombre             is 'Nombre';
comment on column erp_doc_clase_documento.descripcion        is 'Para qué sirve la clase';
comment on column erp_doc_clase_documento.orden              is 'Orden de presentación';
comment on column erp_doc_clase_documento.estado             is 'A=Activo, I=Inactivo';
comment on column erp_doc_clase_documento.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_clase_documento.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_clase_documento.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_clase_documento.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
