-- =============================================================================
-- Tabla  : erp_gen_persona_documento   (abrev: prdo)
-- Documentos de identidad adicionales de una persona (cédula + RUC, pasaporte + RUC…). El principal está en erp_gen_persona.
-- =============================================================================
create table erp_gen_persona_documento (
    persona_documento_id   number generated by default on null as identity (cache 1000),
    persona_id             number         not null,
    tipo_doc_identidad_id  number         not null,
    nro_documento          varchar2(20)   not null,
    dv                     varchar2(1),
    fecha_desde            date           default on null trunc(current_date) not null,
    fecha_hasta            date,
    estado                 varchar2(1)    default on null 'A' not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_prdo primary key (persona_documento_id),
    constraint fk_erp_prdo_prs foreign key (persona_id) references erp_gen_persona (persona_id) on delete cascade,
    constraint fk_erp_prdo_tdi foreign key (tipo_doc_identidad_id) references erp_gen_tipo_doc_identidad (tipo_doc_identidad_id),
    constraint uk_erp_prdo_tdi_nro unique (tipo_doc_identidad_id, nro_documento),
    constraint ck_erp_prdo_vigencia check (fecha_hasta is null or fecha_hasta >= fecha_desde),
    constraint ck_erp_prdo_estado check (estado in ('A','I'))
);

-- (tipo_doc_identidad_id ya indexado por la PK/UK)
create index idx_erp_prdo_persona_id on erp_gen_persona_documento (persona_id);

comment on table  erp_gen_persona_documento is 'Documentos de identidad adicionales de una persona (cédula + RUC, pasaporte + RUC…). El principal está en erp_gen_persona. Abrev: prdo';
comment on column erp_gen_persona_documento.persona_documento_id  is 'Identificador técnico (PK, identity)';
comment on column erp_gen_persona_documento.persona_id            is 'Persona (FK erp_gen_persona)';
comment on column erp_gen_persona_documento.tipo_doc_identidad_id is 'Tipo de documento (FK erp_gen_tipo_doc_identidad)';
comment on column erp_gen_persona_documento.nro_documento         is 'Número sin dígito verificador';
comment on column erp_gen_persona_documento.dv                    is 'Dígito verificador';
comment on column erp_gen_persona_documento.fecha_desde           is 'Desde cuándo es válido';
comment on column erp_gen_persona_documento.fecha_hasta           is 'Vencimiento; null = vigente';
comment on column erp_gen_persona_documento.estado                is 'A=Activo, I=Inactivo';
comment on column erp_gen_persona_documento.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_persona_documento.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_persona_documento.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_persona_documento.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
