-- =============================================================================
-- Tabla  : erp_gen_pais   (abrev: pai)
-- Países (ISO 3166) con su moneda por defecto.
-- =============================================================================
create table erp_gen_pais (
    pais_id             number generated by default on null as identity,
    codigo              varchar2(2)    not null,
    codigo_iso3         varchar2(3)    not null,
    nombre              varchar2(100)  not null,
    moneda_id           number,
    prefijo_telefono    varchar2(5),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_pai primary key (pais_id),
    constraint fk_erp_pai_mon foreign key (moneda_id) references erp_gen_moneda (moneda_id),
    constraint uk_erp_pai_codigo unique (codigo),
    constraint uk_erp_pai_codigo_iso3 unique (codigo_iso3),
    constraint ck_erp_pai_codigo_mayus check (codigo = upper(codigo) and codigo_iso3 = upper(codigo_iso3)),
    constraint ck_erp_pai_estado check (estado in ('A','I'))
);

create index idx_erp_pai_moneda_id on erp_gen_pais (moneda_id);

comment on table  erp_gen_pais is 'Países (ISO 3166) con su moneda por defecto. Abrev: pai';
comment on column erp_gen_pais.pais_id            is 'Identificador técnico (PK, identity)';
comment on column erp_gen_pais.codigo             is 'Código ISO 3166 alfa-2 (PY, BR…)';
comment on column erp_gen_pais.codigo_iso3        is 'Código ISO 3166 alfa-3 (PRY, BRA…), usado por SIFEN';
comment on column erp_gen_pais.nombre             is 'Nombre del país';
comment on column erp_gen_pais.moneda_id          is 'Moneda por defecto del país (FK erp_gen_moneda)';
comment on column erp_gen_pais.prefijo_telefono   is 'Prefijo telefónico internacional (+595)';
comment on column erp_gen_pais.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_pais.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_pais.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_pais.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_pais.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
