-- =============================================================================
-- Tabla  : erp_doc_fe_actividad   (abrev: feac)
-- Actividades económicas del emisor declaradas en el RUC (de 1 a 9 por documento electrónico).
-- Manual Técnico SIFEN v150, grupo D2.1 gActEco, campos D131-D132 (pág. 69).
-- =============================================================================
create table erp_doc_fe_actividad (
    fe_actividad_id     number generated by default on null as identity,
    empresa_id          number         not null,
    codigo              varchar2(8)    not null,
    descripcion         varchar2(300)  not null,
    orden               number(2)      default on null 1 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_feac primary key (fe_actividad_id),
    constraint fk_erp_feac_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_feac_emp_codigo unique (empresa_id, codigo),
    constraint ck_erp_feac_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)

comment on table  erp_doc_fe_actividad is 'Actividades económicas del emisor declaradas en el RUC. Abrev: feac';
comment on column erp_doc_fe_actividad.fe_actividad_id    is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_actividad.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_fe_actividad.codigo             is 'Código de la actividad económica (cActEco)';
comment on column erp_doc_fe_actividad.descripcion        is 'Descripción de la actividad económica (dDesActEco)';
comment on column erp_doc_fe_actividad.orden              is 'Orden en el documento (la principal primero)';
comment on column erp_doc_fe_actividad.estado             is 'A=Activo, I=Inactivo';
comment on column erp_doc_fe_actividad.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_actividad.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_actividad.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_actividad.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
