-- =============================================================================
-- Tabla  : erp_doc_tipo_documento   (abrev: tido)
-- Tipos de documento de cada empresa. Todo el comportamiento (cuenta corriente, stock,
-- fiscal, tesorería, control, análisis, contabilidad) es dato; el código solo consulta la
-- clase (erp_doc_clase_documento) y estos atributos, nunca el código del tipo.
-- Código SIFEN: Manual Técnico SIFEN v150, campo C002 iTiDE (pág. 63).
-- =============================================================================
create table erp_doc_tipo_documento (
    tipo_documento_id            number generated by default on null as identity,
    empresa_id                   number         not null,
    clase_documento_id           number         not null,
    codigo                       varchar2(10)   not null,
    nombre                       varchar2(100)  not null,
    abreviatura                  varchar2(10)   not null,
    modulo                       varchar2(3)    not null,
    origen                       varchar2(1)    default on null 'E' not null,
    -- cuenta corriente
    tipo_cuenta                  varchar2(1)    default on null 'N' not null,
    signo_cuenta                 varchar2(1)    default on null 'N' not null,
    tiene_saldo_aplicable        varchar2(1)    default on null 'N' not null,
    debe_excluir_limite_credito  varchar2(1)    default on null 'N' not null,
    -- stock
    signo_stock                  number(1)      default on null 0 not null,
    debe_valorizar_costo         varchar2(1)    default on null 'N' not null,
    -- fiscal
    es_legal                     varchar2(1)    default on null 'S' not null,
    tipo_emision                 varchar2(1)    default on null 'I' not null,
    debe_exigir_timbrado         varchar2(1)    default on null 'N' not null,
    codigo_sifen                 number(2),
    libro_iva                    varchar2(1)    default on null 'N' not null,
    signo_libro_iva              number(1)      default on null 1 not null,
    debe_calcular_impuesto       varchar2(1)    default on null 'N' not null,
    max_items                    number(4),
    debe_exigir_ruc              varchar2(1)    default on null 'N' not null,
    debe_exigir_motivo           varchar2(1)    default on null 'N' not null,
    -- tesorería
    debe_exigir_cuenta_fondo     varchar2(1)    default on null 'N' not null,
    tipo_cotizacion              varchar2(1),
    -- control
    requiere_documento_origen    varchar2(1)    default on null 'N' not null,
    debe_exigir_vendedor         varchar2(1)    default on null 'N' not null,
    debe_exigir_adjunto          varchar2(1)    default on null 'N' not null,
    debe_exigir_aprobacion       varchar2(1)    default on null 'N' not null,
    dias_max_antiguedad          number(4),
    permite_carga_manual         varchar2(1)    default on null 'S' not null,
    es_intercompany              varchar2(1)    default on null 'N' not null,
    -- análisis
    grupo_estadistico            varchar2(30),
    signo_estadistica            number(1)      default on null 0 not null,
    -- contabilidad (la regla contable se enlaza en la fase de contabilidad)
    debe_generar_asiento         varchar2(1)    default on null 'N' not null,
    estado                       varchar2(1)    default on null 'A' not null,
    creado_por                   varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion               timestamp with local time zone default on null systimestamp not null,
    modificado_por               varchar2(100),
    fecha_modificacion           timestamp with local time zone,
    constraint pk_erp_tido primary key (tipo_documento_id),
    constraint fk_erp_tido_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_tido_cldo foreign key (clase_documento_id) references erp_doc_clase_documento (clase_documento_id),
    constraint uk_erp_tido_emp_codigo unique (empresa_id, codigo),
    constraint ck_erp_tido_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_tido_modulo check (modulo = upper(modulo)),
    constraint ck_erp_tido_origen check (origen in ('E','R')),
    constraint ck_erp_tido_tipo_cuenta check (tipo_cuenta in ('C','P','N')),
    constraint ck_erp_tido_signo_cuenta check (signo_cuenta in ('D','C','N')),
    constraint ck_erp_tido_cuenta_coherente check ((tipo_cuenta = 'N' and signo_cuenta = 'N')
                                                   or (tipo_cuenta <> 'N' and signo_cuenta <> 'N')),
    constraint ck_erp_tido_saldo_aplicable check (tiene_saldo_aplicable in ('S','N')),
    constraint ck_erp_tido_excluir_limite check (debe_excluir_limite_credito in ('S','N')),
    constraint ck_erp_tido_signo_stock check (signo_stock in (-1, 0, 1)),
    constraint ck_erp_tido_valorizar_costo check (debe_valorizar_costo in ('S','N')),
    constraint ck_erp_tido_es_legal check (es_legal in ('S','N')),
    constraint ck_erp_tido_tipo_emision check (tipo_emision in ('E','P','I')),
    constraint ck_erp_tido_exigir_timbrado check (debe_exigir_timbrado in ('S','N')),
    constraint ck_erp_tido_sifen check ((tipo_emision = 'E' and codigo_sifen is not null)
                                        or (tipo_emision <> 'E' and codigo_sifen is null)),
    constraint ck_erp_tido_electr_timbrado check (tipo_emision <> 'E' or debe_exigir_timbrado = 'S'),
    constraint ck_erp_tido_libro_iva check (libro_iva in ('V','C','N')),
    constraint ck_erp_tido_signo_libro_iva check (signo_libro_iva in (-1, 1)),
    constraint ck_erp_tido_calcular_imp check (debe_calcular_impuesto in ('S','N')),
    constraint ck_erp_tido_max_items check (max_items is null or max_items > 0),
    constraint ck_erp_tido_exigir_ruc check (debe_exigir_ruc in ('S','N')),
    constraint ck_erp_tido_exigir_motivo check (debe_exigir_motivo in ('S','N')),
    constraint ck_erp_tido_exigir_cta_fondo check (debe_exigir_cuenta_fondo in ('S','N')),
    constraint ck_erp_tido_tipo_cotizacion check (tipo_cotizacion in ('C','V')),
    constraint ck_erp_tido_requiere_origen check (requiere_documento_origen in ('S','N')),
    constraint ck_erp_tido_exigir_vendedor check (debe_exigir_vendedor in ('S','N')),
    constraint ck_erp_tido_exigir_adjunto check (debe_exigir_adjunto in ('S','N')),
    constraint ck_erp_tido_exigir_aprob check (debe_exigir_aprobacion in ('S','N')),
    constraint ck_erp_tido_dias_antiguedad check (dias_max_antiguedad is null or dias_max_antiguedad >= 0),
    constraint ck_erp_tido_carga_manual check (permite_carga_manual in ('S','N')),
    constraint ck_erp_tido_es_intercompany check (es_intercompany in ('S','N')),
    constraint ck_erp_tido_signo_estad check (signo_estadistica in (-1, 0, 1)),
    constraint ck_erp_tido_generar_asiento check (debe_generar_asiento in ('S','N')),
    constraint ck_erp_tido_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_tido_clase_documento_id on erp_doc_tipo_documento (clase_documento_id);

comment on table  erp_doc_tipo_documento is 'Tipos de documento de cada empresa, con todo su comportamiento como datos. Abrev: tido';
comment on column erp_doc_tipo_documento.tipo_documento_id           is 'Identificador técnico (PK, identity)';
comment on column erp_doc_tipo_documento.empresa_id                  is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_tipo_documento.clase_documento_id          is 'Clase de sistema (FK erp_doc_clase_documento)';
comment on column erp_doc_tipo_documento.codigo                      is 'Código en mayúsculas, único en la empresa (lo elige la empresa; el código nunca lo compara)';
comment on column erp_doc_tipo_documento.nombre                      is 'Nombre';
comment on column erp_doc_tipo_documento.abreviatura                 is 'Abreviatura para listados y reportes';
comment on column erp_doc_tipo_documento.modulo                      is 'Módulo del ERP que lo usa (VEN, COM, FIN, STK…)';
comment on column erp_doc_tipo_documento.origen                      is 'E=Emitido por la empresa, R=Recibido de terceros';
comment on column erp_doc_tipo_documento.tipo_cuenta                 is 'Cuenta corriente que afecta: C=A cobrar, P=A pagar, N=Ninguna';
comment on column erp_doc_tipo_documento.signo_cuenta                is 'Efecto en la cuenta corriente: D=Débito, C=Crédito, N=Ninguno';
comment on column erp_doc_tipo_documento.tiene_saldo_aplicable       is 'S=Genera un saldo que se aplica contra otros documentos (anticipos, notas de crédito)';
comment on column erp_doc_tipo_documento.debe_excluir_limite_credito is 'S=No cuenta para el límite de crédito';
comment on column erp_doc_tipo_documento.signo_stock                 is 'Efecto en stock: 1=Entrada, -1=Salida, 0=Ninguno';
comment on column erp_doc_tipo_documento.debe_valorizar_costo        is 'S=El movimiento de stock actualiza el costo';
comment on column erp_doc_tipo_documento.es_legal                    is 'S=Comprobante legal (entra al registro de comprobantes)';
comment on column erp_doc_tipo_documento.tipo_emision                is 'E=Electrónico, P=Preimpreso o autoimpresor, I=Interno';
comment on column erp_doc_tipo_documento.debe_exigir_timbrado        is 'S=Exige timbrado; los documentos sin timbrado usan un tipo con N (no hay timbrados comodín)';
comment on column erp_doc_tipo_documento.codigo_sifen                is 'Tipo de documento electrónico SIFEN (iTiDE): 1 FE, 4 AFE, 5 NCE, 6 NDE, 7 NRE';
comment on column erp_doc_tipo_documento.libro_iva                   is 'Libro de IVA: V=Ventas, C=Compras, N=Ninguno';
comment on column erp_doc_tipo_documento.signo_libro_iva             is 'Signo en el libro de IVA: 1=Suma, -1=Resta';
comment on column erp_doc_tipo_documento.debe_calcular_impuesto      is 'S=Calcula impuestos por ítem';
comment on column erp_doc_tipo_documento.max_items                   is 'Máximo de ítems por comprobante (preimpresos); null = sin límite';
comment on column erp_doc_tipo_documento.debe_exigir_ruc             is 'S=La contraparte debe tener RUC';
comment on column erp_doc_tipo_documento.debe_exigir_motivo          is 'S=Exige un motivo tipificado (erp_doc_motivo)';
comment on column erp_doc_tipo_documento.debe_exigir_cuenta_fondo    is 'S=Exige caja o cuenta bancaria';
comment on column erp_doc_tipo_documento.tipo_cotizacion             is 'Cotización a usar: C=Compra, V=Venta; null = la de la empresa';
comment on column erp_doc_tipo_documento.requiere_documento_origen   is 'S=Exige un documento asociado (notas de crédito y débito)';
comment on column erp_doc_tipo_documento.debe_exigir_vendedor        is 'S=Exige vendedor';
comment on column erp_doc_tipo_documento.debe_exigir_adjunto         is 'S=Exige un archivo adjunto';
comment on column erp_doc_tipo_documento.debe_exigir_aprobacion      is 'S=Exige aprobación antes de emitir';
comment on column erp_doc_tipo_documento.dias_max_antiguedad         is 'Antigüedad máxima admitida de la fecha del documento, en días; null = sin límite';
comment on column erp_doc_tipo_documento.permite_carga_manual        is 'S=Se puede cargar a mano; N=Solo lo generan los procesos';
comment on column erp_doc_tipo_documento.es_intercompany             is 'S=Documento entre empresas del grupo';
comment on column erp_doc_tipo_documento.grupo_estadistico           is 'Grupo para estadísticas y reportes';
comment on column erp_doc_tipo_documento.signo_estadistica           is 'Signo en las estadísticas: 1=Suma, -1=Resta, 0=No participa';
comment on column erp_doc_tipo_documento.debe_generar_asiento        is 'S=Genera asiento contable';
comment on column erp_doc_tipo_documento.estado                      is 'A=Activo, I=Inactivo';
comment on column erp_doc_tipo_documento.creado_por                  is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_tipo_documento.fecha_creacion              is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_tipo_documento.modificado_por              is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_tipo_documento.fecha_modificacion          is 'Fecha y hora de la última modificación (trigger _bu)';
