-- =============================================================================
-- Tabla  : erp_stk_movimiento_item   (abrev: moit)
-- Líneas del movimiento, con signo, costo unitario en moneda funcional y de reporte y saldo resultante.
-- =============================================================================
create table erp_stk_movimiento_item (
    movimiento_item_id      number generated by default on null as identity (cache 1000),
    movimiento_id           number         not null,
    empresa_id              number         not null,
    linea                   number(6)      not null,
    fecha_movimiento        date           not null,
    deposito_id             number         not null,
    producto_id             number         not null,
    lote_id                 number,
    deposito_ubicacion_id   number,
    cantidad                number(18,4)   not null,
    costo_unitario          number(18,6)   default on null 0 not null,
    costo_unitario_reporte  number(18,6)   default on null 0 not null,
    costo_total             number(18,2)   default on null 0 not null,
    costo_total_reporte     number(18,2)   default on null 0 not null,
    saldo_cantidad          number(18,4)   not null,
    saldo_costo             number(18,6)   not null,
    origen_linea_id         number,
    creado_por              varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion          timestamp with local time zone default on null systimestamp not null,
    modificado_por          varchar2(100),
    fecha_modificacion      timestamp with local time zone,
    constraint pk_erp_moit primary key (movimiento_item_id),
    constraint fk_erp_moit_mov foreign key (movimiento_id) references erp_stk_movimiento (movimiento_id),
    constraint fk_erp_moit_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_moit_dpo foreign key (deposito_id) references erp_stk_deposito (deposito_id),
    constraint fk_erp_moit_pro foreign key (producto_id) references erp_stk_producto (producto_id),
    constraint fk_erp_moit_lot foreign key (lote_id) references erp_stk_lote (lote_id),
    constraint fk_erp_moit_dpub foreign key (deposito_ubicacion_id) references erp_stk_deposito_ubicacion (deposito_ubicacion_id),
    constraint uk_erp_moit_mov_linea unique (movimiento_id, linea),
    constraint ck_erp_moit_cantidad check (cantidad <> 0),
    constraint ck_erp_moit_costo check (costo_unitario >= 0 and costo_unitario_reporte >= 0)
);

create index idx_erp_moit_emp_pro_dpo_fecha on erp_stk_movimiento_item (empresa_id, producto_id, deposito_id, fecha_movimiento);
create index idx_erp_moit_producto_id on erp_stk_movimiento_item (producto_id);
create index idx_erp_moit_deposito_id on erp_stk_movimiento_item (deposito_id);
create index idx_erp_moit_lote_id on erp_stk_movimiento_item (lote_id);
create index idx_erp_moit_ubicacion on erp_stk_movimiento_item (deposito_ubicacion_id);

comment on table  erp_stk_movimiento_item is 'Líneas del movimiento, con signo, costo unitario en moneda funcional y de reporte y saldo resultante. Abrev: moit';
comment on column erp_stk_movimiento_item.movimiento_item_id     is 'Identificador técnico (PK, identity)';
comment on column erp_stk_movimiento_item.movimiento_id          is 'Movimiento (FK erp_stk_movimiento)';
comment on column erp_stk_movimiento_item.empresa_id             is 'Empresa (FK adm_gen_empresa), repetida para consultas e índices';
comment on column erp_stk_movimiento_item.linea                  is 'Número de línea dentro del movimiento';
comment on column erp_stk_movimiento_item.fecha_movimiento       is 'Fecha del movimiento, repetida para la ficha de stock';
comment on column erp_stk_movimiento_item.deposito_id            is 'Depósito (FK erp_stk_deposito)';
comment on column erp_stk_movimiento_item.producto_id            is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_movimiento_item.lote_id                is 'Lote o serie (FK erp_stk_lote)';
comment on column erp_stk_movimiento_item.deposito_ubicacion_id  is 'Ubicación dentro del depósito (FK erp_stk_deposito_ubicacion)';
comment on column erp_stk_movimiento_item.cantidad               is 'Cantidad en unidad base: positiva entra, negativa sale';
comment on column erp_stk_movimiento_item.costo_unitario         is 'Costo unitario en moneda funcional';
comment on column erp_stk_movimiento_item.costo_unitario_reporte is 'Costo unitario en moneda de reporte';
comment on column erp_stk_movimiento_item.costo_total            is 'Cantidad por costo, con signo, en moneda funcional';
comment on column erp_stk_movimiento_item.costo_total_reporte    is 'Cantidad por costo, con signo, en moneda de reporte';
comment on column erp_stk_movimiento_item.saldo_cantidad         is 'Saldo de la fila de stock después de la línea';
comment on column erp_stk_movimiento_item.saldo_costo            is 'Costo unitario del saldo después de la línea (moneda funcional)';
comment on column erp_stk_movimiento_item.origen_linea_id        is 'Identificador de la línea del documento de origen';
comment on column erp_stk_movimiento_item.creado_por             is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_movimiento_item.fecha_creacion         is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_movimiento_item.modificado_por         is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_movimiento_item.fecha_modificacion     is 'Fecha y hora de la última modificación (trigger _bu)';
