-- =============================================================================
-- Tabla  : erp_doc_fe_log   (abrev: felg)
-- Bitácora de cada intercambio con SIFEN (pedido y respuesta) para auditoría y soporte.
-- Solo inserción; se escribe en transacción autónoma para conservarla aunque falle el envío.
-- =============================================================================
create table erp_doc_fe_log (
    fe_log_id           number generated by default on null as identity (cache 1000),
    empresa_id          number,
    servicio            varchar2(30)   not null,
    url                 varchar2(400),
    fe_documento_id     number,
    fe_lote_id          number,
    fe_evento_id        number,
    id_envio            varchar2(15),
    pedido              clob,
    respuesta           clob,
    estado_http         number(3),
    codigo_respuesta    varchar2(4),
    duracion_ms         number,
    error               varchar2(4000),
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_felg primary key (fe_log_id)
);

-- Sin claves foráneas a propósito: la bitácora se escribe en transacción autónoma y debe
-- poder referirse a filas que la transacción principal todavía no confirmó.
create index idx_erp_felg_emp_fecha on erp_doc_fe_log (empresa_id, fecha_creacion);
create index idx_erp_felg_fe_documento_id on erp_doc_fe_log (fe_documento_id);
create index idx_erp_felg_fe_lote_id on erp_doc_fe_log (fe_lote_id);
create index idx_erp_felg_fe_evento_id on erp_doc_fe_log (fe_evento_id);

comment on table  erp_doc_fe_log is 'Bitácora de cada intercambio con SIFEN (pedido y respuesta) para auditoría y soporte. Abrev: felg';
comment on column erp_doc_fe_log.fe_log_id          is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_log.empresa_id         is 'Empresa';
comment on column erp_doc_fe_log.servicio           is 'Servicio invocado (siRecepDE, siRecepLoteDE, siResultLoteDE, siConsDE, siConsRUC, siRecepEvento)';
comment on column erp_doc_fe_log.url                is 'Dirección invocada';
comment on column erp_doc_fe_log.fe_documento_id    is 'Documento electrónico relacionado';
comment on column erp_doc_fe_log.fe_lote_id         is 'Lote relacionado';
comment on column erp_doc_fe_log.fe_evento_id       is 'Evento relacionado';
comment on column erp_doc_fe_log.id_envio           is 'Identificador de control del envío (dId)';
comment on column erp_doc_fe_log.pedido             is 'Mensaje enviado';
comment on column erp_doc_fe_log.respuesta          is 'Mensaje recibido';
comment on column erp_doc_fe_log.estado_http        is 'Código de estado HTTP';
comment on column erp_doc_fe_log.codigo_respuesta   is 'Código de respuesta de SIFEN';
comment on column erp_doc_fe_log.duracion_ms        is 'Duración del intercambio en milisegundos';
comment on column erp_doc_fe_log.error              is 'Error técnico, si hubo';
comment on column erp_doc_fe_log.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_log.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_log.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_log.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
