-- =============================================================================
-- Tabla  : erp_stk_marca   (abrev: mar)
-- Marcas de producto por empresa.
-- =============================================================================
create table erp_stk_marca (
    marca_id            number generated by default on null as identity,
    empresa_id          number         not null,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_mar primary key (marca_id),
    constraint fk_erp_mar_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_mar_emp_codigo unique (empresa_id, codigo),
    constraint ck_erp_mar_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_mar_estado check (estado in ('A','I'))
);


comment on table  erp_stk_marca is 'Marcas de producto por empresa. Abrev: mar';
comment on column erp_stk_marca.marca_id           is 'Identificador técnico (PK, identity)';
comment on column erp_stk_marca.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_marca.codigo             is 'Código en mayúsculas, único por empresa';
comment on column erp_stk_marca.nombre             is 'Nombre';
comment on column erp_stk_marca.estado             is 'A=Activo, I=Inactivo';
comment on column erp_stk_marca.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_marca.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_marca.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_marca.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
