-- =============================================================================
-- Tabla  : erp_stk_kit   (abrev: kit)
-- Componentes de un producto compuesto (kit).
-- =============================================================================
create table erp_stk_kit (
    kit_id                  number generated by default on null as identity,
    producto_id             number         not null,
    producto_id_componente  number         not null,
    cantidad                number(18,4)   not null,
    estado                  varchar2(1)    default on null 'A' not null,
    creado_por              varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion          timestamp with local time zone default on null systimestamp not null,
    modificado_por          varchar2(100),
    fecha_modificacion      timestamp with local time zone,
    constraint pk_erp_kit primary key (kit_id),
    constraint fk_erp_kit_pro foreign key (producto_id) references erp_stk_producto (producto_id) on delete cascade,
    constraint fk_erp_kit_pro_componente foreign key (producto_id_componente) references erp_stk_producto (producto_id),
    constraint uk_erp_kit_pro_componente unique (producto_id, producto_id_componente),
    constraint ck_erp_kit_cantidad check (cantidad > 0),
    constraint ck_erp_kit_distinto check (producto_id <> producto_id_componente),
    constraint ck_erp_kit_estado check (estado in ('A','I'))
);

create index idx_erp_kit_componente on erp_stk_kit (producto_id_componente);

comment on table  erp_stk_kit is 'Componentes de un producto compuesto (kit). Abrev: kit';
comment on column erp_stk_kit.kit_id                 is 'Identificador técnico (PK, identity)';
comment on column erp_stk_kit.producto_id            is 'Producto compuesto, de tipo K (FK erp_stk_producto)';
comment on column erp_stk_kit.producto_id_componente is 'Componente (FK erp_stk_producto)';
comment on column erp_stk_kit.cantidad               is 'Cantidad del componente por unidad del kit, en unidad base del componente';
comment on column erp_stk_kit.estado                 is 'A=Activo, I=Inactivo';
comment on column erp_stk_kit.creado_por             is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_kit.fecha_creacion         is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_kit.modificado_por         is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_kit.fecha_modificacion     is 'Fecha y hora de la última modificación (trigger _bu)';
