-- =============================================================================
-- Tabla  : erp_gen_categoria_fiscal   (abrev: cafi)
-- Categoría fiscal de productos y servicios: define qué tasas aplican y sobre qué parte de la base.
-- =============================================================================
create table erp_gen_categoria_fiscal (
    categoria_fiscal_id  number generated by default on null as identity,
    pais_id              number         not null,
    codigo               varchar2(20)   not null,
    nombre               varchar2(100)  not null,
    codigo_oficial       varchar2(5),
    descripcion          varchar2(400),
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_cafi primary key (categoria_fiscal_id),
    constraint fk_erp_cafi_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint uk_erp_cafi_pais_codigo unique (pais_id, codigo),
    constraint ck_erp_cafi_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_cafi_estado check (estado in ('A','I'))
);

-- (pais_id ya indexado por la PK/UK)

comment on table  erp_gen_categoria_fiscal is 'Categoría fiscal de productos y servicios: define qué tasas aplican y sobre qué parte de la base. Abrev: cafi';
comment on column erp_gen_categoria_fiscal.categoria_fiscal_id is 'Identificador técnico (PK, identity)';
comment on column erp_gen_categoria_fiscal.pais_id             is 'País (FK erp_gen_pais)';
comment on column erp_gen_categoria_fiscal.codigo              is 'Código corto (GRAV10, GRAV5, EXENTO…)';
comment on column erp_gen_categoria_fiscal.nombre              is 'Nombre de la categoría';
comment on column erp_gen_categoria_fiscal.codigo_oficial      is 'Código oficial (SIFEN iAfecIVA: 1=Gravado, 2=Exonerado, 3=Exento, 4=Gravado parcial)';
comment on column erp_gen_categoria_fiscal.descripcion         is 'Descripción y norma aplicable';
comment on column erp_gen_categoria_fiscal.estado              is 'A=Activo, I=Inactivo';
comment on column erp_gen_categoria_fiscal.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_categoria_fiscal.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_categoria_fiscal.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_categoria_fiscal.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
