-- =============================================================================
-- Tabla  : erp_gen_empresa_func   (abrev: emfu)
-- Funcionalidades activas en cada empresa (A=activa, I=desactivada).
-- =============================================================================
create table erp_gen_empresa_func (
    empresa_func_id     number generated by default on null as identity,
    empresa_id          number         not null,
    funcionalidad_id    number         not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_emfu primary key (empresa_func_id),
    constraint fk_erp_emfu_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_emfu_func foreign key (funcionalidad_id) references erp_gen_funcionalidad (funcionalidad_id) on delete cascade,
    constraint uk_erp_emfu_emp_func unique (empresa_id, funcionalidad_id),
    constraint ck_erp_emfu_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_emfu_funcionalidad_id on erp_gen_empresa_func (funcionalidad_id);

comment on table  erp_gen_empresa_func is 'Funcionalidades activas en cada empresa (A=activa, I=desactivada). Abrev: emfu';
comment on column erp_gen_empresa_func.empresa_func_id    is 'Identificador técnico (PK, identity)';
comment on column erp_gen_empresa_func.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_gen_empresa_func.funcionalidad_id   is 'Funcionalidad (FK erp_gen_funcionalidad)';
comment on column erp_gen_empresa_func.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_empresa_func.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_empresa_func.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_empresa_func.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_empresa_func.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
