-- =============================================================================
-- Tabla  : erp_gen_sucursal   (abrev: suc)
-- Sucursales / establecimientos de cada empresa (código de establecimiento SIFEN de 3 dígitos).
-- =============================================================================
create table erp_gen_sucursal (
    sucursal_id         number generated by default on null as identity,
    empresa_id          number         not null,
    codigo              varchar2(10)   not null,
    nombre              varchar2(100)  not null,
    establecimiento     varchar2(3)    not null,
    direccion           varchar2(400),
    numero_casa         varchar2(10),
    ubicacion_id        number,
    telefono            varchar2(30),
    email               varchar2(200),
    es_casa_matriz      varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_suc primary key (sucursal_id),
    constraint fk_erp_suc_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_suc_ubi foreign key (ubicacion_id) references erp_gen_ubicacion (ubicacion_id),
    constraint uk_erp_suc_emp_codigo unique (empresa_id, codigo),
    constraint uk_erp_suc_emp_establec unique (empresa_id, establecimiento),
    constraint ck_erp_suc_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_suc_establecimiento check (regexp_like(establecimiento, '^[0-9]{3}$')),
    constraint ck_erp_suc_es_casa_matriz check (es_casa_matriz in ('S','N')),
    constraint ck_erp_suc_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_suc_ubicacion_id on erp_gen_sucursal (ubicacion_id);

comment on table  erp_gen_sucursal is 'Sucursales / establecimientos de cada empresa (código de establecimiento SIFEN de 3 dígitos). Abrev: suc';
comment on column erp_gen_sucursal.sucursal_id        is 'Identificador técnico (PK, identity)';
comment on column erp_gen_sucursal.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_gen_sucursal.codigo             is 'Código interno de la sucursal';
comment on column erp_gen_sucursal.nombre             is 'Nombre';
comment on column erp_gen_sucursal.establecimiento    is 'Código de establecimiento para comprobantes (001, 002…)';
comment on column erp_gen_sucursal.direccion          is 'Dirección';
comment on column erp_gen_sucursal.numero_casa        is 'Número de casa (SIFEN dNumCas)';
comment on column erp_gen_sucursal.ubicacion_id       is 'Ciudad (FK erp_gen_ubicacion)';
comment on column erp_gen_sucursal.telefono           is 'Teléfono';
comment on column erp_gen_sucursal.email              is 'Correo electrónico';
comment on column erp_gen_sucursal.es_casa_matriz     is 'S=Casa matriz';
comment on column erp_gen_sucursal.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_sucursal.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_sucursal.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_sucursal.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_sucursal.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
