-- =============================================================================
-- Tabla  : erp_gen_periodo   (abrev: peri)
-- Períodos operativos (año/mes) por empresa y módulo: abierto o cerrado.
-- =============================================================================
create table erp_gen_periodo (
    periodo_id          number generated by default on null as identity,
    empresa_id          number         not null,
    modulo              varchar2(3)    not null,
    anio                number(4)      not null,
    mes                 number(2)      not null,
    estado              varchar2(1)    default on null 'A' not null,
    fecha_cierre        timestamp with local time zone,
    cerrado_por         varchar2(100),
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_peri primary key (periodo_id),
    constraint fk_erp_peri_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_peri_emp_mod_anio_mes unique (empresa_id, modulo, anio, mes),
    constraint ck_erp_peri_modulo_mayus check (modulo = upper(modulo)),
    constraint ck_erp_peri_anio check (anio between 2000 and 2999),
    constraint ck_erp_peri_mes check (mes between 1 and 12),
    constraint ck_erp_peri_estado check (estado in ('A','C'))
);

-- (empresa_id ya indexado por la PK/UK)

comment on table  erp_gen_periodo is 'Períodos operativos (año/mes) por empresa y módulo: abierto o cerrado. Abrev: peri';
comment on column erp_gen_periodo.periodo_id         is 'Identificador técnico (PK, identity)';
comment on column erp_gen_periodo.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_gen_periodo.modulo             is 'Código de módulo del ERP (VEN, COM, STK, FIN, CNT…)';
comment on column erp_gen_periodo.anio               is 'Año';
comment on column erp_gen_periodo.mes                is 'Mes (1-12)';
comment on column erp_gen_periodo.estado             is 'A=Abierto, C=Cerrado';
comment on column erp_gen_periodo.fecha_cierre       is 'Fecha y hora del último cierre';
comment on column erp_gen_periodo.cerrado_por        is 'Usuario que cerró el período';
comment on column erp_gen_periodo.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_periodo.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_periodo.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_periodo.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
