-- =============================================================================
-- Tabla  : erp_stk_deposito_ubicacion   (abrev: dpub)
-- Ubicaciones dentro de un depósito: almacenaje, recepción, despacho y cuarentena.
-- =============================================================================
create table erp_stk_deposito_ubicacion (
    deposito_ubicacion_id  number generated by default on null as identity,
    deposito_id            number         not null,
    codigo                 varchar2(20)   not null,
    nombre                 varchar2(100)  not null,
    tipo                   varchar2(1)    default on null 'A' not null,
    es_disponible          varchar2(1)    default on null 'S' not null,
    estado                 varchar2(1)    default on null 'A' not null,
    creado_por             varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion         timestamp with local time zone default on null systimestamp not null,
    modificado_por         varchar2(100),
    fecha_modificacion     timestamp with local time zone,
    constraint pk_erp_dpub primary key (deposito_ubicacion_id),
    constraint fk_erp_dpub_dpo foreign key (deposito_id) references erp_stk_deposito (deposito_id),
    constraint uk_erp_dpub_dpo_codigo unique (deposito_id, codigo),
    constraint ck_erp_dpub_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_dpub_tipo check (tipo in ('A','R','D','C')),
    constraint ck_erp_dpub_es_disponible check (es_disponible in ('S','N')),
    constraint ck_erp_dpub_cuarentena check (tipo <> 'C' or es_disponible = 'N'),
    constraint ck_erp_dpub_estado check (estado in ('A','I'))
);


comment on table  erp_stk_deposito_ubicacion is 'Ubicaciones dentro de un depósito: almacenaje, recepción, despacho y cuarentena. Abrev: dpub';
comment on column erp_stk_deposito_ubicacion.deposito_ubicacion_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_deposito_ubicacion.deposito_id           is 'Depósito (FK erp_stk_deposito)';
comment on column erp_stk_deposito_ubicacion.codigo                is 'Código en mayúsculas, único en el depósito';
comment on column erp_stk_deposito_ubicacion.nombre                is 'Nombre';
comment on column erp_stk_deposito_ubicacion.tipo                  is 'A=Almacenaje, R=Recepción, D=Despacho, C=Cuarentena';
comment on column erp_stk_deposito_ubicacion.es_disponible         is 'S=Su stock se puede vender, reservar y despachar; la cuarentena siempre es N';
comment on column erp_stk_deposito_ubicacion.estado                is 'A=Activo, I=Inactivo';
comment on column erp_stk_deposito_ubicacion.creado_por            is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_deposito_ubicacion.fecha_creacion        is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_deposito_ubicacion.modificado_por        is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_deposito_ubicacion.fecha_modificacion    is 'Fecha y hora de la última modificación (trigger _bu)';
