-- =============================================================================
-- Tabla  : erp_stk_traslado_evento   (abrev: trev)
-- Historial inmutable de las transiciones de cada traslado (línea de tiempo).
-- =============================================================================
create table erp_stk_traslado_evento (
    traslado_evento_id  number generated by default on null as identity (cache 1000),
    traslado_id         number         not null,
    evento              varchar2(20)   not null,
    estado_anterior     varchar2(1),
    estado_nuevo        varchar2(1)    not null,
    usuario             varchar2(100)  not null,
    fecha_evento        timestamp with local time zone default on null systimestamp not null,
    movimiento_id       number,
    detalle             varchar2(4000),
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    constraint pk_erp_trev primary key (traslado_evento_id),
    constraint fk_erp_trev_tra foreign key (traslado_id) references erp_stk_traslado (traslado_id),
    constraint fk_erp_trev_mov foreign key (movimiento_id) references erp_stk_movimiento (movimiento_id),
    constraint ck_erp_trev_detalle_json check (detalle is json)
);

create index idx_erp_trev_traslado_fecha on erp_stk_traslado_evento (traslado_id, fecha_evento);
create index idx_erp_trev_movimiento_id on erp_stk_traslado_evento (movimiento_id);

comment on table  erp_stk_traslado_evento is 'Historial inmutable de las transiciones de cada traslado (línea de tiempo). Abrev: trev';
comment on column erp_stk_traslado_evento.traslado_evento_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_traslado_evento.traslado_id        is 'Traslado (FK erp_stk_traslado)';
comment on column erp_stk_traslado_evento.evento             is 'CREAR, MODIFICAR, SOLICITAR, APROBAR, RECHAZAR, DESPACHAR, RECIBIR, RESOLVER, ANULAR, DEVOLVER, REMISION';
comment on column erp_stk_traslado_evento.estado_anterior    is 'Estado antes del evento';
comment on column erp_stk_traslado_evento.estado_nuevo       is 'Estado después del evento';
comment on column erp_stk_traslado_evento.usuario            is 'Usuario que lo ejecutó';
comment on column erp_stk_traslado_evento.fecha_evento       is 'Fecha y hora';
comment on column erp_stk_traslado_evento.movimiento_id      is 'Movimiento de stock generado (FK erp_stk_movimiento)';
comment on column erp_stk_traslado_evento.detalle            is 'Datos del evento (JSON)';
comment on column erp_stk_traslado_evento.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_traslado_evento.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
