-- =============================================================================
-- Tabla  : erp_gen_impuesto_tasa   (abrev: imta)
-- Tasas de un impuesto (IVA10, IVA5…). El porcentaje vigente está en erp_gen_impuesto_tasa_vig.
-- =============================================================================
create table erp_gen_impuesto_tasa (
    impuesto_tasa_id    number generated by default on null as identity,
    impuesto_id         number         not null,
    codigo              varchar2(10)   not null,
    nombre              varchar2(100)  not null,
    codigo_oficial      varchar2(5),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_imta primary key (impuesto_tasa_id),
    constraint fk_erp_imta_imp foreign key (impuesto_id) references erp_gen_impuesto (impuesto_id),
    constraint uk_erp_imta_imp_codigo unique (impuesto_id, codigo),
    constraint ck_erp_imta_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_imta_estado check (estado in ('A','I'))
);

-- (impuesto_id ya indexado por la PK/UK)

comment on table  erp_gen_impuesto_tasa is 'Tasas de un impuesto (IVA10, IVA5…). El porcentaje vigente está en erp_gen_impuesto_tasa_vig. Abrev: imta';
comment on column erp_gen_impuesto_tasa.impuesto_tasa_id   is 'Identificador técnico (PK, identity)';
comment on column erp_gen_impuesto_tasa.impuesto_id        is 'Impuesto (FK erp_gen_impuesto)';
comment on column erp_gen_impuesto_tasa.codigo             is 'Código corto (IVA10, IVA5…)';
comment on column erp_gen_impuesto_tasa.nombre             is 'Nombre de la tasa';
comment on column erp_gen_impuesto_tasa.codigo_oficial     is 'Código oficial (SIFEN dTasaIVA: 10, 5, 0)';
comment on column erp_gen_impuesto_tasa.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_impuesto_tasa.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_impuesto_tasa.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_impuesto_tasa.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_impuesto_tasa.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
