-- =============================================================================
-- Tabla  : erp_stk_ruta_traslado   (abrev: rutr)
-- Kilómetros y horas estimadas de viaje por par de sucursales.
-- =============================================================================
create table erp_stk_ruta_traslado (
    ruta_traslado_id     number generated by default on null as identity,
    empresa_id           number         not null,
    sucursal_id_origen   number         not null,
    sucursal_id_destino  number         not null,
    kilometros           number(10,2),
    horas_estimadas      number(8,2)   not null,
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_rutr primary key (ruta_traslado_id),
    constraint fk_erp_rutr_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_rutr_suc_origen foreign key (sucursal_id_origen) references erp_gen_sucursal (sucursal_id),
    constraint fk_erp_rutr_suc_destino foreign key (sucursal_id_destino) references erp_gen_sucursal (sucursal_id),
    constraint uk_erp_rutr_emp_origen_destino unique (empresa_id, sucursal_id_origen, sucursal_id_destino),
    constraint ck_erp_rutr_sucursales check (sucursal_id_origen <> sucursal_id_destino),
    constraint ck_erp_rutr_valores check (horas_estimadas >= 0 and coalesce(kilometros, 0) >= 0),
    constraint ck_erp_rutr_estado check (estado in ('A','I'))
);

create index idx_erp_rutr_sucursal_origen on erp_stk_ruta_traslado (sucursal_id_origen);
create index idx_erp_rutr_sucursal_destino on erp_stk_ruta_traslado (sucursal_id_destino);

comment on table  erp_stk_ruta_traslado is 'Kilómetros y horas estimadas de viaje por par de sucursales. Abrev: rutr';
comment on column erp_stk_ruta_traslado.ruta_traslado_id    is 'Identificador técnico (PK, identity)';
comment on column erp_stk_ruta_traslado.empresa_id          is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_ruta_traslado.sucursal_id_origen  is 'Sucursal de salida (FK erp_gen_sucursal)';
comment on column erp_stk_ruta_traslado.sucursal_id_destino is 'Sucursal de llegada (FK erp_gen_sucursal)';
comment on column erp_stk_ruta_traslado.kilometros          is 'Kilómetros estimados de recorrido';
comment on column erp_stk_ruta_traslado.horas_estimadas     is 'Horas estimadas de viaje';
comment on column erp_stk_ruta_traslado.estado              is 'A=Activo, I=Inactivo';
comment on column erp_stk_ruta_traslado.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_ruta_traslado.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_ruta_traslado.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_ruta_traslado.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
