-- =============================================================================
-- Tabla  : erp_stk_usuario_deposito   (abrev: usdp)
-- Restricción fina opcional: en qué depósitos despacha y recibe cada usuario.
-- =============================================================================
create table erp_stk_usuario_deposito (
    usuario_deposito_id  number generated by default on null as identity,
    usuario_id           number         not null,
    deposito_id          number         not null,
    es_despachador       varchar2(1)    default on null 'S' not null,
    es_receptor          varchar2(1)    default on null 'S' not null,
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_usdp primary key (usuario_deposito_id),
    constraint fk_erp_usdp_usu foreign key (usuario_id) references adm_seg_usuario (usuario_id) on delete cascade,
    constraint fk_erp_usdp_dpo foreign key (deposito_id) references erp_stk_deposito (deposito_id) on delete cascade,
    constraint uk_erp_usdp_usu_dpo unique (usuario_id, deposito_id),
    constraint ck_erp_usdp_es_despachador check (es_despachador in ('S','N')),
    constraint ck_erp_usdp_es_receptor check (es_receptor in ('S','N')),
    constraint ck_erp_usdp_estado check (estado in ('A','I'))
);

create index idx_erp_usdp_deposito_id on erp_stk_usuario_deposito (deposito_id);

comment on table  erp_stk_usuario_deposito is 'Restricción fina opcional: en qué depósitos despacha y recibe cada usuario. Abrev: usdp';
comment on column erp_stk_usuario_deposito.usuario_deposito_id is 'Identificador técnico (PK, identity)';
comment on column erp_stk_usuario_deposito.usuario_id          is 'Usuario (FK adm_seg_usuario)';
comment on column erp_stk_usuario_deposito.deposito_id         is 'Depósito (FK erp_stk_deposito)';
comment on column erp_stk_usuario_deposito.es_despachador      is 'S=Puede crear y despachar desde el depósito';
comment on column erp_stk_usuario_deposito.es_receptor         is 'S=Puede recibir en el depósito';
comment on column erp_stk_usuario_deposito.estado              is 'A=Activo, I=Inactivo';
comment on column erp_stk_usuario_deposito.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_usuario_deposito.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_usuario_deposito.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_usuario_deposito.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
