-- =============================================================================
-- Tabla  : erp_gen_persona_rol   (abrev: prro)
-- Roles de cada persona en cada empresa (una persona puede ser cliente de una empresa y proveedor de otra).
-- =============================================================================
create table erp_gen_persona_rol (
    persona_rol_id      number generated by default on null as identity (cache 1000),
    persona_id          number         not null,
    empresa_id          number         not null,
    tipo_rol_id         number         not null,
    codigo_interno      varchar2(30),
    fecha_desde         date           default on null trunc(current_date) not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_prro primary key (persona_rol_id),
    constraint fk_erp_prro_prs foreign key (persona_id) references erp_gen_persona (persona_id) on delete cascade,
    constraint fk_erp_prro_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_prro_tirl foreign key (tipo_rol_id) references erp_gen_tipo_rol (tipo_rol_id),
    constraint uk_erp_prro_prs_emp_rol unique (persona_id, empresa_id, tipo_rol_id),
    constraint ck_erp_prro_estado check (estado in ('A','I'))
);

-- (empresa_id, persona_id ya indexado por la PK/UK)
create index idx_erp_prro_tipo_rol_id on erp_gen_persona_rol (tipo_rol_id);
create index idx_erp_prro_emp_rol on erp_gen_persona_rol (empresa_id, tipo_rol_id);

comment on table  erp_gen_persona_rol is 'Roles de cada persona en cada empresa (una persona puede ser cliente de una empresa y proveedor de otra). Abrev: prro';
comment on column erp_gen_persona_rol.persona_rol_id     is 'Identificador técnico (PK, identity)';
comment on column erp_gen_persona_rol.persona_id         is 'Persona (FK erp_gen_persona)';
comment on column erp_gen_persona_rol.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_gen_persona_rol.tipo_rol_id        is 'Rol (FK erp_gen_tipo_rol)';
comment on column erp_gen_persona_rol.codigo_interno     is 'Código de la persona en ese rol y empresa (ej. código de cliente)';
comment on column erp_gen_persona_rol.fecha_desde        is 'Desde cuándo tiene el rol';
comment on column erp_gen_persona_rol.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_persona_rol.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_persona_rol.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_persona_rol.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_persona_rol.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
