-- =============================================================================
-- Tabla  : erp_doc_tipo_doc_fiscal   (abrev: tdfi)
-- Código de un tipo de documento en el registro mensual de comprobantes, con vigencia.
-- Los códigos cambian con el tiempo: una fila por vigencia, nunca una columna por versión.
-- =============================================================================
create table erp_doc_tipo_doc_fiscal (
    tipo_doc_fiscal_id  number generated by default on null as identity,
    tipo_documento_id   number         not null,
    codigo_registro     varchar2(10)   not null,
    descripcion         varchar2(100),
    fecha_desde         date           not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_tdfi primary key (tipo_doc_fiscal_id),
    -- al eliminar el tipo de documento se eliminan sus códigos fiscales
    constraint fk_erp_tdfi_tido foreign key (tipo_documento_id) references erp_doc_tipo_documento (tipo_documento_id) on delete cascade,
    constraint uk_erp_tdfi_tido_fecha unique (tipo_documento_id, fecha_desde)
);

-- (tipo_documento_id ya indexado por la PK/UK)

comment on table  erp_doc_tipo_doc_fiscal is 'Código de un tipo de documento en el registro mensual de comprobantes, con vigencia. Abrev: tdfi';
comment on column erp_doc_tipo_doc_fiscal.tipo_doc_fiscal_id is 'Identificador técnico (PK, identity)';
comment on column erp_doc_tipo_doc_fiscal.tipo_documento_id  is 'Tipo de documento (FK erp_doc_tipo_documento)';
comment on column erp_doc_tipo_doc_fiscal.codigo_registro    is 'Código del tipo de comprobante en el registro mensual de comprobantes';
comment on column erp_doc_tipo_doc_fiscal.descripcion        is 'Descripción oficial del código';
comment on column erp_doc_tipo_doc_fiscal.fecha_desde        is 'Desde cuándo rige el código (vale hasta la siguiente vigencia)';
comment on column erp_doc_tipo_doc_fiscal.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_tipo_doc_fiscal.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_tipo_doc_fiscal.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_tipo_doc_fiscal.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
