-- =============================================================================
-- Tabla  : erp_stk_saldo   (abrev: sal)
-- Saldo actual de stock por depósito, producto, lote y ubicación, con reservado y costo en moneda funcional y de reporte. Solo lo modifica erp_stk_saldo_ctr, en la transacción del movimiento.
-- =============================================================================
create table erp_stk_saldo (
    saldo_id                 number generated by default on null as identity (cache 1000),
    empresa_id               number         not null,
    deposito_id              number         not null,
    producto_id              number         not null,
    lote_id                  number,
    deposito_ubicacion_id    number,
    cantidad                 number(18,4)   default on null 0 not null,
    cantidad_reservada       number(18,4)   default on null 0 not null,
    costo_promedio           number(18,6)   default on null 0 not null,
    costo_promedio_reporte   number(18,6)   default on null 0 not null,
    es_disponible            varchar2(1)    default on null 'S' not null,
    fecha_ultimo_movimiento  date,
    creado_por               varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion           timestamp with local time zone default on null systimestamp not null,
    modificado_por           varchar2(100),
    fecha_modificacion       timestamp with local time zone,
    constraint pk_erp_sal primary key (saldo_id),
    constraint fk_erp_sal_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_sal_dpo foreign key (deposito_id) references erp_stk_deposito (deposito_id),
    constraint fk_erp_sal_pro foreign key (producto_id) references erp_stk_producto (producto_id),
    constraint fk_erp_sal_lot foreign key (lote_id) references erp_stk_lote (lote_id),
    constraint fk_erp_sal_dpub foreign key (deposito_ubicacion_id) references erp_stk_deposito_ubicacion (deposito_ubicacion_id),
    constraint ck_erp_sal_reservada check (cantidad_reservada >= 0),
    constraint ck_erp_sal_costo check (costo_promedio >= 0 and costo_promedio_reporte >= 0),
    constraint ck_erp_sal_es_disponible check (es_disponible in ('S','N'))
);

create unique index uk_erp_sal_clave on erp_stk_saldo (empresa_id, deposito_id, producto_id, coalesce(lote_id, 0), coalesce(deposito_ubicacion_id, 0));
create index idx_erp_sal_pro_dpo on erp_stk_saldo (producto_id, deposito_id);
create index idx_erp_sal_deposito_id on erp_stk_saldo (deposito_id);
create index idx_erp_sal_lote_id on erp_stk_saldo (lote_id);
create index idx_erp_sal_ubicacion on erp_stk_saldo (deposito_ubicacion_id);

comment on table  erp_stk_saldo is 'Saldo actual de stock por depósito, producto, lote y ubicación, con reservado y costo en moneda funcional y de reporte. Solo lo modifica erp_stk_saldo_ctr, en la transacción del movimiento. Abrev: sal';
comment on column erp_stk_saldo.saldo_id                is 'Identificador técnico (PK, identity)';
comment on column erp_stk_saldo.empresa_id              is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_saldo.deposito_id             is 'Depósito (FK erp_stk_deposito)';
comment on column erp_stk_saldo.producto_id             is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_saldo.lote_id                 is 'Lote o serie; null si el producto no lo maneja (FK erp_stk_lote)';
comment on column erp_stk_saldo.deposito_ubicacion_id   is 'Ubicación; null = sin ubicación (FK erp_stk_deposito_ubicacion)';
comment on column erp_stk_saldo.cantidad                is 'Existencia física en unidad base';
comment on column erp_stk_saldo.cantidad_reservada      is 'Parte de la existencia comprometida (pedidos, traslados aprobados)';
comment on column erp_stk_saldo.costo_promedio          is 'Costo unitario del saldo en moneda funcional (promedio ponderado o último costo, según el producto)';
comment on column erp_stk_saldo.costo_promedio_reporte  is 'Costo unitario del saldo en moneda de reporte';
comment on column erp_stk_saldo.es_disponible           is 'N=Stock en cuarentena: no se vende ni se reserva';
comment on column erp_stk_saldo.fecha_ultimo_movimiento is 'Fecha del último movimiento';
comment on column erp_stk_saldo.creado_por              is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_saldo.fecha_creacion          is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_saldo.modificado_por          is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_saldo.fecha_modificacion      is 'Fecha y hora de la última modificación (trigger _bu)';
