-- =============================================================================
-- Tabla  : erp_stk_deposito   (abrev: dpo)
-- Depósitos de cada sucursal (propios, de terceros/consignación o en tránsito).
-- =============================================================================
create table erp_stk_deposito (
    deposito_id           number generated by default on null as identity,
    sucursal_id           number         not null,
    departamento_id       number,
    codigo                varchar2(10)   not null,
    nombre                varchar2(100)  not null,
    tipo                  varchar2(1)    default on null 'P' not null,
    debe_controlar_stock  varchar2(1)    default on null 'S' not null,
    es_principal          varchar2(1)    default on null 'N' not null,
    direccion             varchar2(400),
    ubicacion_id          number,
    estado                varchar2(1)    default on null 'A' not null,
    creado_por            varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion        timestamp with local time zone default on null systimestamp not null,
    modificado_por        varchar2(100),
    fecha_modificacion    timestamp with local time zone,
    constraint pk_erp_dpo primary key (deposito_id),
    constraint fk_erp_dpo_suc foreign key (sucursal_id) references erp_gen_sucursal (sucursal_id),
    constraint fk_erp_dpo_dpto foreign key (departamento_id) references erp_gen_departamento (departamento_id),
    constraint fk_erp_dpo_ubi foreign key (ubicacion_id) references erp_gen_ubicacion (ubicacion_id),
    constraint uk_erp_dpo_suc_codigo unique (sucursal_id, codigo),
    constraint ck_erp_dpo_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_dpo_tipo check (tipo in ('P','C','T')),
    constraint ck_erp_dpo_debe_controlar check (debe_controlar_stock in ('S','N')),
    constraint ck_erp_dpo_es_principal check (es_principal in ('S','N')),
    constraint ck_erp_dpo_estado check (estado in ('A','I'))
);

-- (sucursal_id ya indexado por la PK/UK)
create index idx_erp_dpo_departamento_id on erp_stk_deposito (departamento_id);
create index idx_erp_dpo_ubicacion_id on erp_stk_deposito (ubicacion_id);

comment on table  erp_stk_deposito is 'Depósitos de cada sucursal (propios, de terceros/consignación o en tránsito). Abrev: dpo';
comment on column erp_stk_deposito.deposito_id          is 'Identificador técnico (PK, identity)';
comment on column erp_stk_deposito.sucursal_id          is 'Sucursal (FK erp_gen_sucursal)';
comment on column erp_stk_deposito.departamento_id      is 'Departamento dueño del stock (FK erp_gen_departamento), opcional';
comment on column erp_stk_deposito.codigo               is 'Código interno';
comment on column erp_stk_deposito.nombre               is 'Nombre';
comment on column erp_stk_deposito.tipo                 is 'P=Propio, C=De terceros / consignación, T=En tránsito';
comment on column erp_stk_deposito.debe_controlar_stock is 'S=No permite saldo negativo';
comment on column erp_stk_deposito.es_principal         is 'S=Depósito por defecto de la sucursal';
comment on column erp_stk_deposito.direccion            is 'Dirección física si es distinta de la sucursal';
comment on column erp_stk_deposito.ubicacion_id         is 'Ciudad (FK erp_gen_ubicacion)';
comment on column erp_stk_deposito.estado               is 'A=Activo, I=Inactivo';
comment on column erp_stk_deposito.creado_por           is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_deposito.fecha_creacion       is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_deposito.modificado_por       is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_deposito.fecha_modificacion   is 'Fecha y hora de la última modificación (trigger _bu)';
