-- =============================================================================
-- Tabla  : erp_gen_tipo_rol   (abrev: tirl)
-- Roles que puede tener una persona (cliente, proveedor, empleado, transportista, productor…) y en qué módulos se usan.
-- =============================================================================
create table erp_gen_tipo_rol (
    tipo_rol_id         number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    es_ventas           varchar2(1)    default on null 'N' not null,
    es_compras          varchar2(1)    default on null 'N' not null,
    es_cobrar           varchar2(1)    default on null 'N' not null,
    es_pagar            varchar2(1)    default on null 'N' not null,
    es_stock            varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_tirl primary key (tipo_rol_id),
    constraint uk_erp_tirl_codigo unique (codigo),
    constraint ck_erp_tirl_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_tirl_modulos check (es_ventas in ('S','N') and es_compras in ('S','N') and es_cobrar in ('S','N') and es_pagar in ('S','N') and es_stock in ('S','N')),
    constraint ck_erp_tirl_estado check (estado in ('A','I'))
);


comment on table  erp_gen_tipo_rol is 'Roles que puede tener una persona (cliente, proveedor, empleado, transportista, productor…) y en qué módulos se usan. Abrev: tirl';
comment on column erp_gen_tipo_rol.tipo_rol_id        is 'Identificador técnico (PK, identity)';
comment on column erp_gen_tipo_rol.codigo             is 'Código en mayúsculas (CLIENTE, PROVEEDOR…)';
comment on column erp_gen_tipo_rol.nombre             is 'Nombre visible';
comment on column erp_gen_tipo_rol.es_ventas          is 'S=Se ofrece en Ventas';
comment on column erp_gen_tipo_rol.es_compras         is 'S=Se ofrece en Compras';
comment on column erp_gen_tipo_rol.es_cobrar          is 'S=Puede tener cuentas a cobrar (clientes, socios…)';
comment on column erp_gen_tipo_rol.es_pagar           is 'S=Puede tener cuentas a pagar (proveedores, empleados…)';
comment on column erp_gen_tipo_rol.es_stock           is 'S=Se ofrece en Inventario (transportistas, depositarios)';
comment on column erp_gen_tipo_rol.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_tipo_rol.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_tipo_rol.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_tipo_rol.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_tipo_rol.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
