-- =============================================================================
-- Tabla  : erp_gen_empresa_config   (abrev: emcf)
-- Configuración ERP de cada empresa de ADM: país, moneda funcional, impuestos y datos fiscales.
-- =============================================================================
create table erp_gen_empresa_config (
    empresa_config_id        number generated by default on null as identity,
    empresa_id               number         not null,
    pais_id                  number         not null,
    moneda_id_funcional      number         not null,
    moneda_id_reporte        number,
    rubro_id                 number,
    precio_incluye_impuesto  varchar2(1)    default on null 'S' not null,
    tipo_cotizacion          varchar2(1)    default on null 'V' not null,
    tipo_contribuyente       varchar2(1)    default on null 'J' not null,
    dv_ruc                   varchar2(1),
    es_agente_retencion      varchar2(1)    default on null 'N' not null,
    es_exportador            varchar2(1)    default on null 'N' not null,
    direccion                varchar2(400),
    ubicacion_id             number,
    telefono                 varchar2(30),
    email                    varchar2(200),
    creado_por               varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion           timestamp with local time zone default on null systimestamp not null,
    modificado_por           varchar2(100),
    fecha_modificacion       timestamp with local time zone,
    constraint pk_erp_emcf primary key (empresa_config_id),
    constraint fk_erp_emcf_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_emcf_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint fk_erp_emcf_mon_func foreign key (moneda_id_funcional) references erp_gen_moneda (moneda_id),
    constraint fk_erp_emcf_mon_rep foreign key (moneda_id_reporte) references erp_gen_moneda (moneda_id),
    constraint fk_erp_emcf_ubi foreign key (ubicacion_id) references erp_gen_ubicacion (ubicacion_id),
    constraint fk_erp_emcf_rub foreign key (rubro_id) references erp_gen_rubro (rubro_id),
    constraint uk_erp_emcf_empresa unique (empresa_id),
    constraint ck_erp_emcf_precio_inc check (precio_incluye_impuesto in ('S','N')),
    constraint ck_erp_emcf_tipo_cotizacion check (tipo_cotizacion in ('C','V')),
    constraint ck_erp_emcf_tipo_contrib check (tipo_contribuyente in ('F','J')),
    constraint ck_erp_emcf_es_agente_ret check (es_agente_retencion in ('S','N')),
    constraint ck_erp_emcf_es_exportador check (es_exportador in ('S','N'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_emcf_pais_id on erp_gen_empresa_config (pais_id);
create index idx_erp_emcf_mon_func on erp_gen_empresa_config (moneda_id_funcional);
create index idx_erp_emcf_moneda_id_reporte on erp_gen_empresa_config (moneda_id_reporte);
create index idx_erp_emcf_ubicacion_id on erp_gen_empresa_config (ubicacion_id);
create index idx_erp_emcf_rubro_id on erp_gen_empresa_config (rubro_id);

comment on table  erp_gen_empresa_config is 'Configuración ERP de cada empresa de ADM: país, moneda funcional, impuestos y datos fiscales. Abrev: emcf';
comment on column erp_gen_empresa_config.empresa_config_id       is 'Identificador técnico (PK, identity)';
comment on column erp_gen_empresa_config.empresa_id              is 'Empresa (FK adm_gen_empresa), una configuración por empresa';
comment on column erp_gen_empresa_config.pais_id                 is 'País fiscal de la empresa (FK erp_gen_pais)';
comment on column erp_gen_empresa_config.moneda_id_funcional     is 'Moneda contable/funcional (FK erp_gen_moneda)';
comment on column erp_gen_empresa_config.moneda_id_reporte       is 'Moneda alternativa para reportes de grupo (FK erp_gen_moneda)';
comment on column erp_gen_empresa_config.rubro_id                is 'Perfil de rubro de la empresa (FK erp_gen_rubro)';
comment on column erp_gen_empresa_config.precio_incluye_impuesto is 'S=Los precios se cargan con impuesto incluido';
comment on column erp_gen_empresa_config.tipo_cotizacion         is 'Tasa por defecto para convertir: C=Compra, V=Venta';
comment on column erp_gen_empresa_config.tipo_contribuyente      is 'F=Persona física, J=Persona jurídica (SIFEN iTipCont)';
comment on column erp_gen_empresa_config.dv_ruc                  is 'Dígito verificador del RUC (el número está en adm_gen_empresa.nro_documento)';
comment on column erp_gen_empresa_config.es_agente_retencion     is 'S=Es agente de retención';
comment on column erp_gen_empresa_config.es_exportador           is 'S=Es exportador';
comment on column erp_gen_empresa_config.direccion               is 'Dirección fiscal';
comment on column erp_gen_empresa_config.ubicacion_id            is 'Ciudad de la dirección fiscal (FK erp_gen_ubicacion)';
comment on column erp_gen_empresa_config.telefono                is 'Teléfono';
comment on column erp_gen_empresa_config.email                   is 'Correo electrónico';
comment on column erp_gen_empresa_config.creado_por              is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_empresa_config.fecha_creacion          is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_empresa_config.modificado_por          is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_empresa_config.fecha_modificacion      is 'Fecha y hora de la última modificación (trigger _bu)';
