-- =============================================================================
-- Tabla  : erp_doc_fe_lote_detalle   (abrev: feld)
-- Documentos electrónicos que integran un lote y el resultado de cada uno en ese envío.
-- =============================================================================
create table erp_doc_fe_lote_detalle (
    fe_lote_detalle_id  number generated by default on null as identity (cache 1000),
    fe_lote_id          number         not null,
    fe_documento_id     number         not null,
    orden               number(3)      not null,
    estado_resultado    varchar2(1),
    codigo_respuesta    varchar2(4),
    mensaje_respuesta   varchar2(255),
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_feld primary key (fe_lote_detalle_id),
    constraint fk_erp_feld_felo foreign key (fe_lote_id) references erp_doc_fe_lote (fe_lote_id),
    constraint fk_erp_feld_fedo foreign key (fe_documento_id) references erp_doc_fe_documento (fe_documento_id),
    constraint uk_erp_feld_lote_documento unique (fe_lote_id, fe_documento_id),
    constraint ck_erp_feld_estado_resultado check (estado_resultado in ('A','O','R'))
);

-- (fe_lote_id ya indexado por la PK/UK)
create index idx_erp_feld_fe_documento_id on erp_doc_fe_lote_detalle (fe_documento_id);

comment on table  erp_doc_fe_lote_detalle is 'Documentos electrónicos que integran un lote y el resultado de cada uno en ese envío. Abrev: feld';
comment on column erp_doc_fe_lote_detalle.fe_lote_detalle_id is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_lote_detalle.fe_lote_id         is 'Lote (FK erp_doc_fe_lote)';
comment on column erp_doc_fe_lote_detalle.fe_documento_id    is 'Documento electrónico (FK erp_doc_fe_documento)';
comment on column erp_doc_fe_lote_detalle.orden              is 'Posición del documento dentro del lote';
comment on column erp_doc_fe_lote_detalle.estado_resultado   is 'A=Aprobado, O=Aprobado con observación, R=Rechazado; null = sin resultado';
comment on column erp_doc_fe_lote_detalle.codigo_respuesta   is 'Código de respuesta del documento en este lote';
comment on column erp_doc_fe_lote_detalle.mensaje_respuesta  is 'Mensaje de respuesta del documento en este lote';
comment on column erp_doc_fe_lote_detalle.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_lote_detalle.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_lote_detalle.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_lote_detalle.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
