-- =============================================================================
-- Tabla  : erp_gen_rubro   (abrev: rub)
-- Perfiles de rubro (comercio, agro, industria…): plantilla de funcionalidades para configurar una empresa.
-- =============================================================================
create table erp_gen_rubro (
    rubro_id            number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(400),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_rub primary key (rubro_id),
    constraint uk_erp_rub_codigo unique (codigo),
    constraint ck_erp_rub_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_rub_estado check (estado in ('A','I'))
);


comment on table  erp_gen_rubro is 'Perfiles de rubro (comercio, agro, industria…): plantilla de funcionalidades para configurar una empresa. Abrev: rub';
comment on column erp_gen_rubro.rubro_id           is 'Identificador técnico (PK, identity)';
comment on column erp_gen_rubro.codigo             is 'Código en mayúsculas';
comment on column erp_gen_rubro.nombre             is 'Nombre visible';
comment on column erp_gen_rubro.descripcion        is 'Para qué tipo de empresa sirve';
comment on column erp_gen_rubro.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_rubro.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_rubro.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_rubro.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_rubro.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
