-- =============================================================================
-- Tabla  : erp_stk_producto_equiv   (abrev: preq)
-- Productos equivalentes o sustitutos de otro producto.
-- =============================================================================
create table erp_stk_producto_equiv (
    producto_equiv_id        number generated by default on null as identity,
    producto_id              number         not null,
    producto_id_equivalente  number         not null,
    tipo                     varchar2(1)    default on null 'E' not null,
    prioridad                number(3)      default on null 1 not null,
    observacion              varchar2(400),
    estado                   varchar2(1)    default on null 'A' not null,
    creado_por               varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion           timestamp with local time zone default on null systimestamp not null,
    modificado_por           varchar2(100),
    fecha_modificacion       timestamp with local time zone,
    constraint pk_erp_preq primary key (producto_equiv_id),
    constraint fk_erp_preq_pro foreign key (producto_id) references erp_stk_producto (producto_id) on delete cascade,
    constraint fk_erp_preq_pro_equiv foreign key (producto_id_equivalente) references erp_stk_producto (producto_id),
    constraint uk_erp_preq_pro_equiv unique (producto_id, producto_id_equivalente),
    constraint ck_erp_preq_tipo check (tipo in ('E','S')),
    constraint ck_erp_preq_distinto check (producto_id <> producto_id_equivalente),
    constraint ck_erp_preq_estado check (estado in ('A','I'))
);

create index idx_erp_preq_equivalente on erp_stk_producto_equiv (producto_id_equivalente);

comment on table  erp_stk_producto_equiv is 'Productos equivalentes o sustitutos de otro producto. Abrev: preq';
comment on column erp_stk_producto_equiv.producto_equiv_id       is 'Identificador técnico (PK, identity)';
comment on column erp_stk_producto_equiv.producto_id             is 'Producto (FK erp_stk_producto)';
comment on column erp_stk_producto_equiv.producto_id_equivalente is 'Producto que lo reemplaza (FK erp_stk_producto)';
comment on column erp_stk_producto_equiv.tipo                    is 'E=Equivalente (idéntico en uso), S=Sustituto (alternativa aceptable)';
comment on column erp_stk_producto_equiv.prioridad               is 'Orden en que se ofrece';
comment on column erp_stk_producto_equiv.observacion             is 'Observación';
comment on column erp_stk_producto_equiv.estado                  is 'A=Activo, I=Inactivo';
comment on column erp_stk_producto_equiv.creado_por              is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_producto_equiv.fecha_creacion          is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_producto_equiv.modificado_por          is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_producto_equiv.fecha_modificacion      is 'Fecha y hora de la última modificación (trigger _bu)';
