-- =============================================================================
-- Tabla  : erp_stk_producto   (abrev: pro)
-- Productos y servicios por empresa. Maestro delgado: lo propio de cada rubro va en atributos (JSON) y en tablas hermanas; el costo vive solo en saldos y movimientos.
-- =============================================================================
create table erp_stk_producto (
    producto_id               number generated by default on null as identity (cache 1000),
    empresa_id                number         not null,
    codigo                    varchar2(30)   not null,
    nombre                    varchar2(200)  not null,
    descripcion               varchar2(4000),
    descripcion_fe            varchar2(120),
    tipo                      varchar2(1)    default on null 'B' not null,
    unidad_id                 number         not null,
    unidad_id_compra          number,
    factor_compra             number(18,6)   default on null 1 not null,
    unidad_id_venta           number,
    factor_venta              number(18,6)   default on null 1 not null,
    categoria_fiscal_id       number         not null,
    categoria_id              number,
    marca_id                  number,
    tiene_lote                varchar2(1)    default on null 'N' not null,
    tiene_serie               varchar2(1)    default on null 'N' not null,
    tiene_vencimiento         varchar2(1)    default on null 'N' not null,
    dias_vida_util            number(5),
    meses_garantia            number(3),
    metodo_costo              varchar2(1),
    porcentaje_descuento_max  number(5,2),
    peso_neto                 number(18,4),
    peso_bruto                number(18,4),
    volumen                   number(18,6),
    largo                     number(18,4),
    ancho                     number(18,4),
    alto                      number(18,4),
    atributos                 varchar2(4000),
    estado                    varchar2(1)    default on null 'A' not null,
    creado_por                varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion            timestamp with local time zone default on null systimestamp not null,
    modificado_por            varchar2(100),
    fecha_modificacion        timestamp with local time zone,
    constraint pk_erp_pro primary key (producto_id),
    constraint fk_erp_pro_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_pro_uni foreign key (unidad_id) references erp_stk_unidad (unidad_id),
    constraint fk_erp_pro_uni_compra foreign key (unidad_id_compra) references erp_stk_unidad (unidad_id),
    constraint fk_erp_pro_uni_venta foreign key (unidad_id_venta) references erp_stk_unidad (unidad_id),
    constraint fk_erp_pro_cafi foreign key (categoria_fiscal_id) references erp_gen_categoria_fiscal (categoria_fiscal_id),
    constraint fk_erp_pro_ctg foreign key (categoria_id) references erp_stk_categoria (categoria_id),
    constraint fk_erp_pro_mar foreign key (marca_id) references erp_stk_marca (marca_id),
    constraint uk_erp_pro_emp_codigo unique (empresa_id, codigo),
    constraint ck_erp_pro_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_pro_tipo check (tipo in ('B','S','K','P')),
    constraint ck_erp_pro_tiene_lote check (tiene_lote in ('S','N')),
    constraint ck_erp_pro_tiene_serie check (tiene_serie in ('S','N')),
    constraint ck_erp_pro_tiene_vencimiento check (tiene_vencimiento in ('S','N')),
    constraint ck_erp_pro_lote_serie check (tiene_lote = 'N' or tiene_serie = 'N'),
    constraint ck_erp_pro_vencimiento check (tiene_vencimiento = 'N' or tiene_lote = 'S' or tiene_serie = 'S'),
    constraint ck_erp_pro_sin_stock check (tipo in ('B','P') or (tiene_lote = 'N' and tiene_serie = 'N')),
    constraint ck_erp_pro_metodo_costo check (metodo_costo in ('P','U')),
    constraint ck_erp_pro_factores check (factor_compra > 0 and factor_venta > 0),
    constraint ck_erp_pro_descuento_max check (porcentaje_descuento_max between 0 and 100),
    constraint ck_erp_pro_medidas check (coalesce(peso_neto, 0) >= 0 and coalesce(peso_bruto, 0) >= 0 and coalesce(volumen, 0) >= 0),
    constraint ck_erp_pro_atributos_json check (atributos is json),
    constraint ck_erp_pro_estado check (estado in ('A','I'))
);

create index idx_erp_pro_unidad_id on erp_stk_producto (unidad_id);
create index idx_erp_pro_unidad_id_compra on erp_stk_producto (unidad_id_compra);
create index idx_erp_pro_unidad_id_venta on erp_stk_producto (unidad_id_venta);
create index idx_erp_pro_categoria_fiscal on erp_stk_producto (categoria_fiscal_id);
create index idx_erp_pro_categoria_id on erp_stk_producto (categoria_id);
create index idx_erp_pro_marca_id on erp_stk_producto (marca_id);
create index idx_erp_pro_emp_nombre on erp_stk_producto (empresa_id, upper(nombre));

comment on table  erp_stk_producto is 'Productos y servicios por empresa. Maestro delgado: lo propio de cada rubro va en atributos (JSON) y en tablas hermanas; el costo vive solo en saldos y movimientos. Abrev: pro';
comment on column erp_stk_producto.producto_id              is 'Identificador técnico (PK, identity)';
comment on column erp_stk_producto.empresa_id               is 'Empresa (FK adm_gen_empresa)';
comment on column erp_stk_producto.codigo                   is 'Código interno en mayúsculas, único por empresa';
comment on column erp_stk_producto.nombre                   is 'Nombre';
comment on column erp_stk_producto.descripcion              is 'Descripción larga';
comment on column erp_stk_producto.descripcion_fe           is 'Descripción abreviada para el documento electrónico';
comment on column erp_stk_producto.tipo                     is 'B=Bien, S=Servicio, K=Kit (compuesto, sin stock propio), P=Producción';
comment on column erp_stk_producto.unidad_id                is 'Unidad base en la que se lleva el stock (FK erp_stk_unidad)';
comment on column erp_stk_producto.unidad_id_compra         is 'Unidad habitual de compra (FK erp_stk_unidad)';
comment on column erp_stk_producto.factor_compra            is 'Unidades base que contiene una unidad de compra';
comment on column erp_stk_producto.unidad_id_venta          is 'Unidad habitual de venta (FK erp_stk_unidad)';
comment on column erp_stk_producto.factor_venta             is 'Unidades base que contiene una unidad de venta';
comment on column erp_stk_producto.categoria_fiscal_id      is 'Cómo tributa (FK erp_gen_categoria_fiscal)';
comment on column erp_stk_producto.categoria_id             is 'Categoría (FK erp_stk_categoria)';
comment on column erp_stk_producto.marca_id                 is 'Marca (FK erp_stk_marca)';
comment on column erp_stk_producto.tiene_lote               is 'S=Se controla por lote';
comment on column erp_stk_producto.tiene_serie              is 'S=Se controla por número de serie (una unidad por serie)';
comment on column erp_stk_producto.tiene_vencimiento        is 'S=El lote o la serie llevan fecha de vencimiento';
comment on column erp_stk_producto.dias_vida_util           is 'Vida útil en días desde la elaboración';
comment on column erp_stk_producto.meses_garantia           is 'Meses de garantía';
comment on column erp_stk_producto.metodo_costo             is 'P=Promedio ponderado, U=Último costo; null = parámetro ERP_STK_METODO_COSTO de la empresa';
comment on column erp_stk_producto.porcentaje_descuento_max is 'Porcentaje máximo de descuento en venta';
comment on column erp_stk_producto.peso_neto                is 'Peso neto de la unidad base (kg)';
comment on column erp_stk_producto.peso_bruto               is 'Peso bruto de la unidad base (kg)';
comment on column erp_stk_producto.volumen                  is 'Volumen de la unidad base (m3)';
comment on column erp_stk_producto.largo                    is 'Largo (cm)';
comment on column erp_stk_producto.ancho                    is 'Ancho (cm)';
comment on column erp_stk_producto.alto                     is 'Alto (cm)';
comment on column erp_stk_producto.atributos                is 'Atributos adicionales (JSON) validados contra la definición de la categoría';
comment on column erp_stk_producto.estado                   is 'A=Activo, I=Inactivo';
comment on column erp_stk_producto.creado_por               is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_producto.fecha_creacion           is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_producto.modificado_por           is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_producto.fecha_modificacion       is 'Fecha y hora de la última modificación (trigger _bu)';
