-- =============================================================================
-- Tabla  : erp_doc_fe_config   (abrev: feco)
-- Configuración de facturación electrónica (SIFEN) de cada empresa: ambiente, versión del
-- formato, CSC del QR (cifrado), certificado, direcciones y plazos.
-- Manual Técnico SIFEN v150: §7.10 direcciones (pág. 41), §13.8 CSC (pág. 205), plazos (pág. 62 y 117).
-- =============================================================================
create table erp_doc_fe_config (
    fe_config_id             number generated by default on null as identity,
    empresa_id               number         not null,
    ambiente                 varchar2(1)    default on null 'T' not null,
    version_formato          varchar2(3)    default on null '150' not null,
    fe_certificado_id        number,
    id_csc                   varchar2(4),
    csc_cifrado              raw(2000),
    tipo_regimen             number(2),
    nombre_fantasia          varchar2(255),
    url_servicios            varchar2(400),
    url_consulta_qr          varchar2(400),
    debe_declarar_esquema    varchar2(1)    default on null 'S' not null,
    max_documentos_lote      number(3)      default on null 50 not null,
    horas_limite_envio       number(4)      default on null 72 not null,
    horas_cancelacion_fe     number(4)      default on null 48 not null,
    horas_cancelacion_otros  number(4)      default on null 168 not null,
    horas_consulta_lote      number(4)      default on null 48 not null,
    max_intentos             number(3)      default on null 10 not null,
    minutos_reintento        number(5)      default on null 5 not null,
    estado                   varchar2(1)    default on null 'A' not null,
    creado_por               varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion           timestamp with local time zone default on null systimestamp not null,
    modificado_por           varchar2(100),
    fecha_modificacion       timestamp with local time zone,
    constraint pk_erp_feco primary key (fe_config_id),
    constraint fk_erp_feco_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_feco_fece foreign key (fe_certificado_id) references erp_doc_fe_certificado (fe_certificado_id),
    constraint uk_erp_feco_empresa unique (empresa_id),
    constraint ck_erp_feco_ambiente check (ambiente in ('T','P')),
    constraint ck_erp_feco_version check (regexp_like(version_formato, '^[0-9]{3}$')),
    constraint ck_erp_feco_id_csc check (id_csc is null or regexp_like(id_csc, '^[0-9]{1,4}$')),
    constraint ck_erp_feco_declarar_esquema check (debe_declarar_esquema in ('S','N')),
    constraint ck_erp_feco_max_lote check (max_documentos_lote between 1 and 50),
    constraint ck_erp_feco_plazos check (horas_limite_envio > 0 and horas_cancelacion_fe > 0
                                         and horas_cancelacion_otros > 0 and horas_consulta_lote > 0),
    constraint ck_erp_feco_reintentos check (max_intentos > 0 and minutos_reintento > 0),
    constraint ck_erp_feco_estado check (estado in ('A','I'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_feco_fe_certificado_id on erp_doc_fe_config (fe_certificado_id);

comment on table  erp_doc_fe_config is 'Configuración de facturación electrónica (SIFEN) de cada empresa. Abrev: feco';
comment on column erp_doc_fe_config.fe_config_id            is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_config.empresa_id              is 'Empresa (FK adm_gen_empresa), una configuración por empresa';
comment on column erp_doc_fe_config.ambiente                is 'T=Test, P=Producción';
comment on column erp_doc_fe_config.version_formato         is 'Versión del formato del DE (dVerFor); parámetro para absorber notas técnicas';
comment on column erp_doc_fe_config.fe_certificado_id       is 'Certificado con el que se firma (FK erp_doc_fe_certificado)';
comment on column erp_doc_fe_config.id_csc                  is 'Identificador del código de seguridad del contribuyente (IdCSC)';
comment on column erp_doc_fe_config.csc_cifrado             is 'Código de seguridad del contribuyente (CSC) cifrado con AES-256; nunca en claro';
comment on column erp_doc_fe_config.tipo_regimen            is 'Tipo de régimen del emisor (cTipReg, tabla 1 del manual), opcional';
comment on column erp_doc_fe_config.nombre_fantasia         is 'Nombre de fantasía declarado en el RUC (dNomFanEmi), opcional';
comment on column erp_doc_fe_config.url_servicios           is 'Dirección base de los servicios web; null = la del manual según el ambiente';
comment on column erp_doc_fe_config.url_consulta_qr         is 'Dirección de consulta del QR; null = la del manual según el ambiente';
comment on column erp_doc_fe_config.debe_declarar_esquema   is 'S=El rDE declara xmlns:xsi y xsi:schemaLocation como en el manual';
comment on column erp_doc_fe_config.max_documentos_lote     is 'Máximo de DE por lote (hasta 50)';
comment on column erp_doc_fe_config.horas_limite_envio      is 'Horas desde la firma para transmitir el DE (72)';
comment on column erp_doc_fe_config.horas_cancelacion_fe    is 'Horas desde la aprobación para cancelar una factura electrónica (48)';
comment on column erp_doc_fe_config.horas_cancelacion_otros is 'Horas desde la aprobación para cancelar los demás DE (168)';
comment on column erp_doc_fe_config.horas_consulta_lote     is 'Horas durante las que se consulta un lote antes de pasar a la consulta por CDC';
comment on column erp_doc_fe_config.max_intentos            is 'Reintentos automáticos antes de dejar el documento para revisión';
comment on column erp_doc_fe_config.minutos_reintento       is 'Espera base entre reintentos (se duplica en cada intento)';
comment on column erp_doc_fe_config.estado                  is 'A=Activo, I=Inactivo';
comment on column erp_doc_fe_config.creado_por              is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_config.fecha_creacion          is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_config.modificado_por          is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_config.fecha_modificacion      is 'Fecha y hora de la última modificación (trigger _bu)';
