-- =============================================================================
-- Tabla  : erp_gen_feriado   (abrev: feri)
-- Feriados por país (vencimientos, días hábiles, intereses).
-- =============================================================================
create table erp_gen_feriado (
    feriado_id          number generated by default on null as identity,
    pais_id             number         not null,
    fecha               date           not null,
    nombre              varchar2(100)  not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_feri primary key (feriado_id),
    constraint fk_erp_feri_pai foreign key (pais_id) references erp_gen_pais (pais_id),
    constraint uk_erp_feri_pais_fecha unique (pais_id, fecha)
);

-- (pais_id ya indexado por la PK/UK)

comment on table  erp_gen_feriado is 'Feriados por país (vencimientos, días hábiles, intereses). Abrev: feri';
comment on column erp_gen_feriado.feriado_id         is 'Identificador técnico (PK, identity)';
comment on column erp_gen_feriado.pais_id            is 'País (FK erp_gen_pais)';
comment on column erp_gen_feriado.fecha              is 'Fecha del feriado';
comment on column erp_gen_feriado.nombre             is 'Motivo del feriado';
comment on column erp_gen_feriado.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_feriado.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_feriado.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_feriado.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
