-- =============================================================================
-- Tabla  : erp_doc_fe_documento   (abrev: fedo)
-- Documento electrónico (DE) de un documento comercial: CDC, XML firmado, QR y su ciclo de
-- vida. El estado de ENVÍO es independiente del resultado en SIFEN y del estado del receptor.
-- Un solo DE por documento de origen (UK) y un solo registro por CDC (UK).
-- Manual Técnico SIFEN v150: §10.1 CDC (pág. 56), plazo de 72 h desde la firma (pág. 62).
-- =============================================================================
create table erp_doc_fe_documento (
    fe_documento_id      number generated by default on null as identity (cache 1000),
    empresa_id           number         not null,
    origen_modulo        varchar2(3)    not null,
    origen_tipo          varchar2(30)   not null,
    origen_id            number         not null,
    tipo_documento_id    number         not null,
    numerador_id         number,
    fe_certificado_id    number,
    fe_lote_id           number,
    tipo_de              number(2)      not null,
    timbrado             varchar2(8)    not null,
    establecimiento      varchar2(3)    not null,
    punto_expedicion     varchar2(3)    not null,
    numero               number(7)      not null,
    serie                varchar2(2),
    tipo_emision         number(1)      default on null 1 not null,
    cdc                  varchar2(44)   not null,
    codigo_seguridad     varchar2(9)    not null,
    version_formato      varchar2(3)    not null,
    ambiente             varchar2(1)    not null,
    fecha_emision        timestamp      not null,
    fecha_firma          timestamp      not null,
    fecha_limite_envio   timestamp      not null,
    receptor_documento   varchar2(20),
    receptor_nombre      varchar2(255),
    moneda               varchar2(3),
    monto_total          number,
    monto_impuesto       number,
    cantidad_items       number(3),
    digest_value         varchar2(44)   not null,
    url_qr               varchar2(1000),
    datos                clob,
    xml_firmado          clob           not null,
    estado_envio         varchar2(1)    default on null 'P' not null,
    estado_sifen         varchar2(1)    default on null 'N' not null,
    estado_receptor      varchar2(1),
    codigo_respuesta     varchar2(4),
    mensaje_respuesta    varchar2(255),
    protocolo            varchar2(15),
    fecha_envio          timestamp,
    fecha_respuesta      timestamp,
    intentos             number(3)      default on null 0 not null,
    proximo_intento      timestamp      default on null localtimestamp,
    ultimo_error         varchar2(1000),
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_fedo primary key (fe_documento_id),
    constraint fk_erp_fedo_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_fedo_tido foreign key (tipo_documento_id) references erp_doc_tipo_documento (tipo_documento_id),
    constraint fk_erp_fedo_nume foreign key (numerador_id) references erp_doc_numerador (numerador_id),
    constraint fk_erp_fedo_fece foreign key (fe_certificado_id) references erp_doc_fe_certificado (fe_certificado_id),
    constraint fk_erp_fedo_felo foreign key (fe_lote_id) references erp_doc_fe_lote (fe_lote_id),
    constraint uk_erp_fedo_cdc unique (cdc),
    constraint uk_erp_fedo_origen unique (empresa_id, origen_modulo, origen_tipo, origen_id),
    constraint ck_erp_fedo_origen_mayus check (origen_modulo = upper(origen_modulo) and origen_tipo = upper(origen_tipo)),
    constraint ck_erp_fedo_cdc check (regexp_like(cdc, '^[0-9]{44}$')),
    constraint ck_erp_fedo_codigo_seguridad check (regexp_like(codigo_seguridad, '^[0-9]{9}$')),
    constraint ck_erp_fedo_tipo_emision check (tipo_emision in (1, 2)),
    constraint ck_erp_fedo_ambiente check (ambiente in ('T','P')),
    constraint ck_erp_fedo_estado_envio check (estado_envio in ('P','L','E','S','T','X','C')),
    constraint ck_erp_fedo_estado_sifen check (estado_sifen in ('N','A','O','R','C','I')),
    constraint ck_erp_fedo_estado_receptor check (estado_receptor in ('N','C','P','D','X'))
);

-- (empresa_id ya indexado por la PK/UK)
create index idx_erp_fedo_cola on erp_doc_fe_documento (estado_envio, proximo_intento);
create index idx_erp_fedo_emp_fecha on erp_doc_fe_documento (empresa_id, fecha_emision);
create index idx_erp_fedo_tipo_documento_id on erp_doc_fe_documento (tipo_documento_id);
create index idx_erp_fedo_nume_numero on erp_doc_fe_documento (numerador_id, numero);
create index idx_erp_fedo_fe_certificado_id on erp_doc_fe_documento (fe_certificado_id);
create index idx_erp_fedo_fe_lote_id on erp_doc_fe_documento (fe_lote_id);

comment on table  erp_doc_fe_documento is 'Documento electrónico (DE) de un documento comercial: CDC, XML firmado, QR y ciclo de vida. Abrev: fedo';
comment on column erp_doc_fe_documento.fe_documento_id    is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_documento.empresa_id         is 'Empresa (FK adm_gen_empresa)';
comment on column erp_doc_fe_documento.origen_modulo      is 'Módulo del documento comercial de origen (VEN, COM, STK…)';
comment on column erp_doc_fe_documento.origen_tipo        is 'Entidad de origen (FACTURA, NOTA_CREDITO, REMISION…)';
comment on column erp_doc_fe_documento.origen_id          is 'Identificador del documento de origen';
comment on column erp_doc_fe_documento.tipo_documento_id  is 'Tipo de documento (FK erp_doc_tipo_documento)';
comment on column erp_doc_fe_documento.numerador_id       is 'Numerador del que salió el número (FK erp_doc_numerador)';
comment on column erp_doc_fe_documento.fe_certificado_id  is 'Certificado con el que se firmó (FK erp_doc_fe_certificado)';
comment on column erp_doc_fe_documento.fe_lote_id         is 'Último lote en el que se envió (FK erp_doc_fe_lote)';
comment on column erp_doc_fe_documento.tipo_de            is 'Tipo de documento electrónico (iTiDE)';
comment on column erp_doc_fe_documento.timbrado           is 'Número de timbrado';
comment on column erp_doc_fe_documento.establecimiento    is 'Establecimiento (3 dígitos)';
comment on column erp_doc_fe_documento.punto_expedicion   is 'Punto de expedición (3 dígitos)';
comment on column erp_doc_fe_documento.numero             is 'Número del documento';
comment on column erp_doc_fe_documento.serie              is 'Serie (dos letras), si corresponde';
comment on column erp_doc_fe_documento.tipo_emision       is '1=Normal, 2=Contingencia (iTipEmi)';
comment on column erp_doc_fe_documento.cdc                is 'Código de control de 44 dígitos';
comment on column erp_doc_fe_documento.codigo_seguridad   is 'Código de seguridad aleatorio de 9 dígitos (dCodSeg)';
comment on column erp_doc_fe_documento.version_formato    is 'Versión del formato con la que se generó (dVerFor)';
comment on column erp_doc_fe_documento.ambiente           is 'T=Test, P=Producción';
comment on column erp_doc_fe_documento.fecha_emision      is 'Fecha y hora de emisión del DE (hora local de la empresa)';
comment on column erp_doc_fe_documento.fecha_firma        is 'Fecha y hora de la firma digital (hora local de la empresa)';
comment on column erp_doc_fe_documento.fecha_limite_envio is 'Límite para transmitir sin extemporaneidad (firma + horas de la configuración)';
comment on column erp_doc_fe_documento.receptor_documento is 'RUC o documento del receptor';
comment on column erp_doc_fe_documento.receptor_nombre    is 'Nombre o razón social del receptor';
comment on column erp_doc_fe_documento.moneda             is 'Moneda de la operación (ISO 4217)';
comment on column erp_doc_fe_documento.monto_total        is 'Total general de la operación (dTotGralOpe)';
comment on column erp_doc_fe_documento.monto_impuesto     is 'Liquidación total del IVA (dTotIVA)';
comment on column erp_doc_fe_documento.cantidad_items     is 'Cantidad de ítems';
comment on column erp_doc_fe_documento.digest_value       is 'DigestValue SHA-256 del DE en Base64';
comment on column erp_doc_fe_documento.url_qr             is 'Dirección completa del código QR (dCarQR sin escapar)';
comment on column erp_doc_fe_documento.datos              is 'Datos de entrada (JSON) con los que se generó el DE';
comment on column erp_doc_fe_documento.xml_firmado        is 'XML del rDE firmado (UTF-8, sin declaración XML)';
comment on column erp_doc_fe_documento.estado_envio       is 'P=Pendiente, L=En lote, E=Enviado, S=Sin respuesta, T=Error técnico, X=Detenido (requiere revisión), C=Concluido';
comment on column erp_doc_fe_documento.estado_sifen       is 'N=Sin resultado, A=Aprobado, O=Aprobado con observación, R=Rechazado, C=Cancelado, I=Inutilizado';
comment on column erp_doc_fe_documento.estado_receptor    is 'N=Notificado, C=Conforme, P=Parcialmente conforme, D=Disconforme, X=Desconocido; null = sin manifestación';
comment on column erp_doc_fe_documento.codigo_respuesta   is 'Código de respuesta de SIFEN (dCodRes)';
comment on column erp_doc_fe_documento.mensaje_respuesta  is 'Mensaje de respuesta de SIFEN (dMsgRes)';
comment on column erp_doc_fe_documento.protocolo          is 'Número de transacción de la aprobación (dProtAut)';
comment on column erp_doc_fe_documento.fecha_envio        is 'Fecha y hora del último envío';
comment on column erp_doc_fe_documento.fecha_respuesta    is 'Fecha y hora del resultado';
comment on column erp_doc_fe_documento.intentos           is 'Intentos fallidos acumulados';
comment on column erp_doc_fe_documento.proximo_intento    is 'Cuándo puede volver a tomarse de la cola';
comment on column erp_doc_fe_documento.ultimo_error       is 'Último error técnico';
comment on column erp_doc_fe_documento.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_documento.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_documento.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_documento.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
