-- =============================================================================
-- Tabla  : erp_stk_tipo_movimiento   (abrev: timo)
-- Catálogo de tipos de movimiento de stock con su comportamiento.
-- =============================================================================
create table erp_stk_tipo_movimiento (
    tipo_movimiento_id        number generated by default on null as identity,
    codigo                    varchar2(20)   not null,
    nombre                    varchar2(100)  not null,
    naturaleza                varchar2(1)    not null,
    debe_exigir_motivo        varchar2(1)    default on null 'N' not null,
    debe_validar_vencimiento  varchar2(1)    default on null 'N' not null,
    debe_permitir_transito    varchar2(1)    default on null 'N' not null,
    es_manual                 varchar2(1)    default on null 'N' not null,
    estado                    varchar2(1)    default on null 'A' not null,
    creado_por                varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion            timestamp with local time zone default on null systimestamp not null,
    modificado_por            varchar2(100),
    fecha_modificacion        timestamp with local time zone,
    constraint pk_erp_timo primary key (tipo_movimiento_id),
    constraint uk_erp_timo_codigo unique (codigo),
    constraint ck_erp_timo_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_timo_naturaleza check (naturaleza in ('E','S','T')),
    constraint ck_erp_timo_debe_motivo check (debe_exigir_motivo in ('S','N')),
    constraint ck_erp_timo_debe_vencimiento check (debe_validar_vencimiento in ('S','N')),
    constraint ck_erp_timo_debe_transito check (debe_permitir_transito in ('S','N')),
    constraint ck_erp_timo_es_manual check (es_manual in ('S','N')),
    constraint ck_erp_timo_estado check (estado in ('A','I'))
);


comment on table  erp_stk_tipo_movimiento is 'Catálogo de tipos de movimiento de stock con su comportamiento. Abrev: timo';
comment on column erp_stk_tipo_movimiento.tipo_movimiento_id       is 'Identificador técnico (PK, identity)';
comment on column erp_stk_tipo_movimiento.codigo                   is 'Código en mayúsculas (AJUSTE_ENT, COMPRA, VENTA, TRAS_DESPACHO…)';
comment on column erp_stk_tipo_movimiento.nombre                   is 'Nombre';
comment on column erp_stk_tipo_movimiento.naturaleza               is 'E=Entrada (líneas positivas), S=Salida (líneas negativas), T=Transferencia (ambos signos)';
comment on column erp_stk_tipo_movimiento.debe_exigir_motivo       is 'S=El movimiento exige un motivo';
comment on column erp_stk_tipo_movimiento.debe_validar_vencimiento is 'S=No permite sacar lotes vencidos';
comment on column erp_stk_tipo_movimiento.debe_permitir_transito   is 'S=Puede mover depósitos de tránsito (solo traslados)';
comment on column erp_stk_tipo_movimiento.es_manual                is 'S=Lo puede registrar un usuario desde Inventario; N=solo lo generan los documentos';
comment on column erp_stk_tipo_movimiento.estado                   is 'A=Activo, I=Inactivo';
comment on column erp_stk_tipo_movimiento.creado_por               is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_tipo_movimiento.fecha_creacion           is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_tipo_movimiento.modificado_por           is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_tipo_movimiento.fecha_modificacion       is 'Fecha y hora de la última modificación (trigger _bu)';
