-- =============================================================================
-- Tabla  : erp_doc_fe_cod_respuesta   (abrev: fecr)
-- Catálogo de códigos de respuesta de SIFEN con su efecto y cómo resolver.
-- Las respuestas se interpretan por código, nunca por el texto del mensaje.
-- Manual Técnico SIFEN v150 cap. 12 (pág. 145-159).
-- =============================================================================
create table erp_doc_fe_cod_respuesta (
    fe_cod_respuesta_id  number generated by default on null as identity,
    codigo               varchar2(4)    not null,
    mensaje              varchar2(255)  not null,
    servicio             varchar2(20),
    efecto               varchar2(1)    not null,
    es_reintentable      varchar2(1)    default on null 'N' not null,
    como_resolver        varchar2(1000),
    estado               varchar2(1)    default on null 'A' not null,
    creado_por           varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion       timestamp with local time zone default on null systimestamp not null,
    modificado_por       varchar2(100),
    fecha_modificacion   timestamp with local time zone,
    constraint pk_erp_fecr primary key (fe_cod_respuesta_id),
    constraint uk_erp_fecr_codigo unique (codigo),
    constraint ck_erp_fecr_codigo check (regexp_like(codigo, '^[0-9]{4}$')),
    constraint ck_erp_fecr_efecto check (efecto in ('A','O','R','E','I')),
    constraint ck_erp_fecr_es_reintentable check (es_reintentable in ('S','N')),
    constraint ck_erp_fecr_estado check (estado in ('A','I'))
);

comment on table  erp_doc_fe_cod_respuesta is 'Catálogo de códigos de respuesta de SIFEN con su efecto y cómo resolver. Abrev: fecr';
comment on column erp_doc_fe_cod_respuesta.fe_cod_respuesta_id is 'Identificador técnico (PK, identity)';
comment on column erp_doc_fe_cod_respuesta.codigo              is 'Código de respuesta de 4 dígitos (dCodRes)';
comment on column erp_doc_fe_cod_respuesta.mensaje             is 'Mensaje oficial';
comment on column erp_doc_fe_cod_respuesta.servicio            is 'Servicio o grupo al que pertenece (siRecepDE, siRecepLoteDE, firma, DE…)';
comment on column erp_doc_fe_cod_respuesta.efecto              is 'A=Aprobado/éxito, O=Aprobado con observación, R=Rechazo, E=En proceso (volver a consultar), I=Informativo';
comment on column erp_doc_fe_cod_respuesta.es_reintentable     is 'S=Se puede reintentar el mismo envío sin corregir el documento';
comment on column erp_doc_fe_cod_respuesta.como_resolver       is 'Qué hacer cuando llega este código';
comment on column erp_doc_fe_cod_respuesta.estado              is 'A=Activo, I=Inactivo';
comment on column erp_doc_fe_cod_respuesta.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_fe_cod_respuesta.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_fe_cod_respuesta.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_fe_cod_respuesta.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
