-- =============================================================================
-- Tabla  : erp_gen_cotizacion   (abrev: cot)
-- Cotización por fecha: 1 unidad de moneda origen = tasa en moneda destino. General (empresa null) o por empresa.
-- =============================================================================
create table erp_gen_cotizacion (
    cotizacion_id       number generated by default on null as identity,
    empresa_id          number,
    moneda_id_origen    number         not null,
    moneda_id_destino   number         not null,
    fecha               date           not null,
    tasa_compra         number(18,6)   not null,
    tasa_venta          number(18,6)   not null,
    fuente              varchar2(3)    default on null 'MAN' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_cot primary key (cotizacion_id),
    constraint fk_erp_cot_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint fk_erp_cot_mon_origen foreign key (moneda_id_origen) references erp_gen_moneda (moneda_id),
    constraint fk_erp_cot_mon_destino foreign key (moneda_id_destino) references erp_gen_moneda (moneda_id),
    constraint uk_erp_cot_mon_fecha_emp unique (moneda_id_origen, moneda_id_destino, fecha, empresa_id),
    constraint ck_erp_cot_monedas check (moneda_id_origen <> moneda_id_destino),
    constraint ck_erp_cot_tasas_pos check (tasa_compra > 0 and tasa_venta > 0),
    constraint ck_erp_cot_fuente check (fuente in ('BCP','SET','API','MAN'))
);

-- (moneda_id_origen ya indexado por la PK/UK)
create index idx_erp_cot_empresa_id on erp_gen_cotizacion (empresa_id);
create index idx_erp_cot_moneda_id_destino on erp_gen_cotizacion (moneda_id_destino);

comment on table  erp_gen_cotizacion is 'Cotización por fecha: 1 unidad de moneda origen = tasa en moneda destino. General (empresa null) o por empresa. Abrev: cot';
comment on column erp_gen_cotizacion.cotizacion_id      is 'Identificador técnico (PK, identity)';
comment on column erp_gen_cotizacion.empresa_id         is 'Empresa; null = cotización general (FK adm_gen_empresa)';
comment on column erp_gen_cotizacion.moneda_id_origen   is 'Moneda origen (FK erp_gen_moneda)';
comment on column erp_gen_cotizacion.moneda_id_destino  is 'Moneda destino (FK erp_gen_moneda)';
comment on column erp_gen_cotizacion.fecha              is 'Fecha de la cotización';
comment on column erp_gen_cotizacion.tasa_compra        is 'Tasa comprador';
comment on column erp_gen_cotizacion.tasa_venta         is 'Tasa vendedor';
comment on column erp_gen_cotizacion.fuente             is 'BCP=Banco Central, SET=DNIT, API=servicio externo, MAN=manual';
comment on column erp_gen_cotizacion.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_cotizacion.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_cotizacion.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_cotizacion.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
