-- =============================================================================
-- Tabla  : erp_doc_motivo   (abrev: moti)
-- Catálogo tipificado de motivos: anulación, nota de crédito/débito, inutilización y rechazo.
-- General (empresa null) o propio de una empresa. Código SIFEN del motivo de emisión de
-- notas: Manual Técnico SIFEN v150, campo E401 iMotEmi (pág. 77).
-- =============================================================================
create table erp_doc_motivo (
    motivo_id           number generated by default on null as identity,
    empresa_id          number,
    tipo                varchar2(1)    not null,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    codigo_sifen        number(2),
    descripcion_sifen   varchar2(40),
    debe_exigir_detalle varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_moti primary key (motivo_id),
    constraint fk_erp_moti_emp foreign key (empresa_id) references adm_gen_empresa (empresa_id),
    constraint uk_erp_moti_tipo_codigo_emp unique (tipo, codigo, empresa_id),
    constraint ck_erp_moti_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_moti_tipo check (tipo in ('A','C','D','I','R')),
    constraint ck_erp_moti_sifen check ((codigo_sifen is null and descripcion_sifen is null)
                                        or (codigo_sifen is not null and descripcion_sifen is not null and tipo in ('C','D'))),
    constraint ck_erp_moti_exigir_detalle check (debe_exigir_detalle in ('S','N')),
    constraint ck_erp_moti_estado check (estado in ('A','I'))
);

create index idx_erp_moti_empresa_id on erp_doc_motivo (empresa_id);

comment on table  erp_doc_motivo is 'Catálogo tipificado de motivos: anulación, nota de crédito/débito, inutilización y rechazo. Abrev: moti';
comment on column erp_doc_motivo.motivo_id           is 'Identificador técnico (PK, identity)';
comment on column erp_doc_motivo.empresa_id          is 'Empresa; null = motivo general (FK adm_gen_empresa)';
comment on column erp_doc_motivo.tipo                is 'A=Anulación, C=Nota de crédito, D=Nota de débito, I=Inutilización de número, R=Rechazo';
comment on column erp_doc_motivo.codigo              is 'Código en mayúsculas';
comment on column erp_doc_motivo.nombre              is 'Nombre';
comment on column erp_doc_motivo.codigo_sifen        is 'Motivo de emisión SIFEN (iMotEmi) para notas de crédito y débito';
comment on column erp_doc_motivo.descripcion_sifen   is 'Descripción oficial del motivo (dDesMotEmi)';
comment on column erp_doc_motivo.debe_exigir_detalle is 'S=Además exige un texto explicativo';
comment on column erp_doc_motivo.estado              is 'A=Activo, I=Inactivo';
comment on column erp_doc_motivo.creado_por          is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_doc_motivo.fecha_creacion      is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_doc_motivo.modificado_por      is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_doc_motivo.fecha_modificacion  is 'Fecha y hora de la última modificación (trigger _bu)';
