-- =============================================================================
-- Tabla  : erp_gen_rubro_func   (abrev: rufu)
-- Funcionalidades que activa cada perfil de rubro.
-- =============================================================================
create table erp_gen_rubro_func (
    rubro_func_id       number generated by default on null as identity,
    rubro_id            number         not null,
    funcionalidad_id    number         not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_rufu primary key (rubro_func_id),
    constraint fk_erp_rufu_rub foreign key (rubro_id) references erp_gen_rubro (rubro_id) on delete cascade,
    constraint fk_erp_rufu_func foreign key (funcionalidad_id) references erp_gen_funcionalidad (funcionalidad_id) on delete cascade,
    constraint uk_erp_rufu_rub_func unique (rubro_id, funcionalidad_id)
);

-- (rubro_id ya indexado por la PK/UK)
create index idx_erp_rufu_funcionalidad_id on erp_gen_rubro_func (funcionalidad_id);

comment on table  erp_gen_rubro_func is 'Funcionalidades que activa cada perfil de rubro. Abrev: rufu';
comment on column erp_gen_rubro_func.rubro_func_id      is 'Identificador técnico (PK, identity)';
comment on column erp_gen_rubro_func.rubro_id           is 'Rubro (FK erp_gen_rubro)';
comment on column erp_gen_rubro_func.funcionalidad_id   is 'Funcionalidad (FK erp_gen_funcionalidad)';
comment on column erp_gen_rubro_func.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_rubro_func.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_rubro_func.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_rubro_func.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
