-- =============================================================================
-- Tabla  : erp_gen_moneda   (abrev: mon)
-- Monedas (ISO 4217) con decimales de importe y de precio.
-- =============================================================================
create table erp_gen_moneda (
    moneda_id           number generated by default on null as identity,
    codigo              varchar2(3)    not null,
    nombre              varchar2(50)   not null,
    simbolo             varchar2(10)   not null,
    decimales           number(1)      default on null 2 not null,
    decimales_precio    number(1)      default on null 4 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_mon primary key (moneda_id),
    constraint uk_erp_mon_codigo unique (codigo),
    constraint ck_erp_mon_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_mon_decimales check (decimales between 0 and 4),
    constraint ck_erp_mon_decimales_precio check (decimales_precio between 0 and 6),
    constraint ck_erp_mon_estado check (estado in ('A','I'))
);


comment on table  erp_gen_moneda is 'Monedas (ISO 4217) con decimales de importe y de precio. Abrev: mon';
comment on column erp_gen_moneda.moneda_id          is 'Identificador técnico (PK, identity)';
comment on column erp_gen_moneda.codigo             is 'Código ISO 4217 (PYG, USD, BRL…)';
comment on column erp_gen_moneda.nombre             is 'Nombre de la moneda';
comment on column erp_gen_moneda.simbolo            is 'Símbolo para mostrar (₲, US$…)';
comment on column erp_gen_moneda.decimales          is 'Decimales de importes (PYG=0, USD=2)';
comment on column erp_gen_moneda.decimales_precio   is 'Decimales de precios unitarios';
comment on column erp_gen_moneda.estado             is 'A=Activo, I=Inactivo';
comment on column erp_gen_moneda.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_gen_moneda.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_gen_moneda.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_gen_moneda.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
