-- =============================================================================
-- Tabla  : erp_stk_unidad   (abrev: uni)
-- Unidades de medida con su código oficial para el documento electrónico (SIFEN cUniMed).
-- =============================================================================
create table erp_stk_unidad (
    unidad_id           number generated by default on null as identity,
    codigo              varchar2(10)   not null,
    nombre              varchar2(100)  not null,
    simbolo             varchar2(10),
    codigo_sifen        number(5),
    decimales           number(1)      default on null 4 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_uni primary key (unidad_id),
    constraint uk_erp_uni_codigo unique (codigo),
    constraint ck_erp_uni_codigo_mayus check (codigo = upper(codigo)),
    constraint ck_erp_uni_decimales check (decimales between 0 and 4),
    constraint ck_erp_uni_estado check (estado in ('A','I'))
);


comment on table  erp_stk_unidad is 'Unidades de medida con su código oficial para el documento electrónico (SIFEN cUniMed). Abrev: uni';
comment on column erp_stk_unidad.unidad_id          is 'Identificador técnico (PK, identity)';
comment on column erp_stk_unidad.codigo             is 'Código interno en mayúsculas (UNI, KG, LT…)';
comment on column erp_stk_unidad.nombre             is 'Nombre';
comment on column erp_stk_unidad.simbolo            is 'Símbolo para imprimir';
comment on column erp_stk_unidad.codigo_sifen       is 'Código oficial de la unidad en SIFEN (cUniMed)';
comment on column erp_stk_unidad.decimales          is 'Decimales admitidos en cantidades (0 = solo enteros)';
comment on column erp_stk_unidad.estado             is 'A=Activo, I=Inactivo';
comment on column erp_stk_unidad.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_unidad.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_unidad.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_unidad.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
