-- =============================================================================
-- Tabla  : erp_stk_traslado_recep   (abrev: trre)
-- Recepciones de un traslado (puede haber varias: recepción parcial).
-- =============================================================================
create table erp_stk_traslado_recep (
    traslado_recep_id   number generated by default on null as identity (cache 1000),
    traslado_id         number         not null,
    numero              number(4)      not null,
    fecha_recepcion     timestamp with local time zone not null,
    usuario_recibe      varchar2(100)  not null,
    movimiento_id       number,
    observacion         varchar2(4000),
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp with local time zone default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp with local time zone,
    constraint pk_erp_trre primary key (traslado_recep_id),
    constraint fk_erp_trre_tra foreign key (traslado_id) references erp_stk_traslado (traslado_id),
    constraint fk_erp_trre_mov foreign key (movimiento_id) references erp_stk_movimiento (movimiento_id),
    constraint uk_erp_trre_tra_numero unique (traslado_id, numero)
);

create index idx_erp_trre_movimiento_id on erp_stk_traslado_recep (movimiento_id);

comment on table  erp_stk_traslado_recep is 'Recepciones de un traslado (puede haber varias: recepción parcial). Abrev: trre';
comment on column erp_stk_traslado_recep.traslado_recep_id  is 'Identificador técnico (PK, identity)';
comment on column erp_stk_traslado_recep.traslado_id        is 'Traslado (FK erp_stk_traslado)';
comment on column erp_stk_traslado_recep.numero             is 'Número de recepción dentro del traslado';
comment on column erp_stk_traslado_recep.fecha_recepcion    is 'Fecha y hora de la recepción';
comment on column erp_stk_traslado_recep.usuario_recibe     is 'Usuario que recibió';
comment on column erp_stk_traslado_recep.movimiento_id      is 'Movimiento de stock de la recepción (FK erp_stk_movimiento)';
comment on column erp_stk_traslado_recep.observacion        is 'Observación';
comment on column erp_stk_traslado_recep.creado_por         is 'Usuario que creó el registro (APP_USER o usuario de BD)';
comment on column erp_stk_traslado_recep.fecha_creacion     is 'Fecha y hora de creación (con zona horaria)';
comment on column erp_stk_traslado_recep.modificado_por     is 'Usuario de la última modificación (trigger _bu)';
comment on column erp_stk_traslado_recep.fecha_modificacion is 'Fecha y hora de la última modificación (trigger _bu)';
