-- GENERADO por tools/build-supporting-objects.ps1 - NO EDITAR (fuente: apps/adm/database)

-- >>> apps/adm/database/tables/adm_gen_empresa.sql
-- =============================================================================
-- Tabla : adm_gen_empresa
-- App   : adm (Administración Central)  | Módulo: gen (General)
-- Desc  : Empresas / unidades de negocio. Permite que todas las apps sean
--         multi-empresa y que los roles se asignen por empresa.
-- =============================================================================
create table adm_gen_empresa (
    empresa_id          number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    razon_social        varchar2(200)  not null,
    nombre_comercial    varchar2(200),
    nro_documento       varchar2(20),
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_gen_empresa primary key (empresa_id),
    constraint uk_empresa_codigo unique (codigo),
    constraint ck_empresa_estado check (estado in ('A','I'))
);

comment on table  adm_gen_empresa        is 'Empresas / unidades de negocio (multi-empresa)';
comment on column adm_gen_empresa.estado is 'A=Activo, I=Inactivo';

-- >>> apps/adm/database/tables/adm_seg_aplicacion.sql
-- =============================================================================
-- Tabla : adm_seg_aplicacion
-- App   : adm | Módulo: seg (Seguridad)
-- Desc  : Catálogo de sistemas/aplicaciones (ADM, ERP, CRM...). Cada una puede
--         apuntar a su app APEX para armar el menú/portal de lanzamiento.
-- =============================================================================
create table adm_seg_aplicacion (
    aplicacion_id       number generated by default on null as identity,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    apex_app_id         number,
    icono               varchar2(100),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_aplicacion primary key (aplicacion_id),
    constraint uk_aplicacion_codigo unique (codigo),
    constraint uk_aplicacion_apex_app_id unique (apex_app_id),
    constraint ck_aplicacion_estado check (estado in ('A','I')),
    constraint ck_aplicacion_codigo_mayus check (codigo = upper(codigo))
);

comment on table  adm_seg_aplicacion             is 'Sistemas/aplicaciones gestionados por la seguridad central';
comment on column adm_seg_aplicacion.apex_app_id is 'ID de la aplicación APEX (APP_ID)';

-- >>> apps/adm/database/tables/adm_seg_modulo.sql
-- =============================================================================
-- Tabla : adm_seg_modulo
-- App   : adm | Módulo: seg
-- Desc  : Módulos funcionales de cada aplicación (ERP->FIN, STK, PRD...).
-- =============================================================================
create table adm_seg_modulo (
    modulo_id           number generated by default on null as identity,
    aplicacion_id       number         not null,
    codigo              varchar2(20)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    icono               varchar2(100),
    orden               number(4)      default on null 0 not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_modulo primary key (modulo_id),
    constraint fk_admsegaplicacion_admsegmodulo foreign key (aplicacion_id)
        references adm_seg_aplicacion (aplicacion_id),
    constraint uk_modulo_aplicacion_codigo unique (aplicacion_id, codigo),
    constraint ck_modulo_estado check (estado in ('A','I')),
    constraint ck_modulo_codigo_mayus check (codigo = upper(codigo))
);

create index idx_modulo_aplicacion on adm_seg_modulo (aplicacion_id);

comment on table adm_seg_modulo is 'Módulos funcionales por aplicación';

-- >>> apps/adm/database/tables/adm_seg_permiso.sql
-- =============================================================================
-- Tabla : adm_seg_permiso
-- App   : adm | Módulo: seg
-- Desc  : Permisos atómicos dentro de un módulo. Pueden ser de tipo:
--           PAGINA  -> acceso a una página APEX (apex_pagina_id)
--           ACCION  -> botón/proceso (crear, anular, aprobar...)
--           REPORTE -> reportes/exportaciones
--         El código es único global, formato sugerido APP_MODULO_ENTIDAD_ACCION
--         (ej. ERP_FIN_FACTURA_ANULAR).
-- =============================================================================
create table adm_seg_permiso (
    permiso_id          number generated by default on null as identity,
    modulo_id           number         not null,
    codigo              varchar2(60)   not null,
    nombre              varchar2(150)  not null,
    descripcion         varchar2(500),
    tipo                varchar2(10)   default on null 'ACCION' not null,
    apex_pagina_id      number,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_permiso primary key (permiso_id),
    constraint fk_admsegmodulo_admsegpermiso foreign key (modulo_id)
        references adm_seg_modulo (modulo_id),
    constraint uk_permiso_codigo unique (codigo),
    constraint ck_permiso_tipo check (tipo in ('PAGINA','ACCION','REPORTE')),
    constraint ck_permiso_pagina check (tipo <> 'PAGINA' or apex_pagina_id is not null),
    constraint ck_permiso_estado check (estado in ('A','I')),
    constraint ck_permiso_codigo_mayus check (codigo = upper(codigo))
);

create index idx_permiso_modulo on adm_seg_permiso (modulo_id);

comment on table  adm_seg_permiso                is 'Permisos atómicos (página, acción o reporte)';
comment on column adm_seg_permiso.apex_pagina_id is 'Página APEX protegida cuando tipo = PAGINA';

-- >>> apps/adm/database/tables/adm_seg_rol.sql
-- =============================================================================
-- Tabla : adm_seg_rol
-- App   : adm | Módulo: seg
-- Desc  : Roles. Un rol pertenece a una aplicación (aplicacion_id) o es
--         global (aplicacion_id null, ej. SUPERADMIN).
--         es_superadmin = 'S' otorga todos los permisos de todas las apps.
-- =============================================================================
create table adm_seg_rol (
    rol_id              number generated by default on null as identity,
    aplicacion_id       number,
    codigo              varchar2(40)   not null,
    nombre              varchar2(100)  not null,
    descripcion         varchar2(500),
    es_superadmin       varchar2(1)    default on null 'N' not null,
    estado              varchar2(1)    default on null 'A' not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_rol primary key (rol_id),
    constraint fk_admsegaplicacion_admsegrol foreign key (aplicacion_id)
        references adm_seg_aplicacion (aplicacion_id),
    constraint uk_rol_codigo unique (codigo),
    constraint ck_rol_es_superadmin check (es_superadmin in ('S','N')),
    constraint ck_rol_estado check (estado in ('A','I')),
    constraint ck_rol_codigo_mayus check (codigo = upper(codigo))
);

create index idx_rol_aplicacion on adm_seg_rol (aplicacion_id);

comment on table  adm_seg_rol               is 'Roles por aplicación o globales';
comment on column adm_seg_rol.aplicacion_id is 'Null = rol global';

-- >>> apps/adm/database/tables/adm_seg_rol_permiso.sql
-- =============================================================================
-- Tabla : adm_seg_rol_permiso
-- App   : adm | Módulo: seg
-- Desc  : Permisos otorgados a cada rol (N:M).
-- =============================================================================
create table adm_seg_rol_permiso (
    rol_permiso_id      number generated by default on null as identity,
    rol_id              number         not null,
    permiso_id          number         not null,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_rol_permiso primary key (rol_permiso_id),
    constraint fk_admsegrol_admsegrolpermiso foreign key (rol_id)
        references adm_seg_rol (rol_id) on delete cascade,
    constraint fk_admsegpermiso_admsegrolpermiso foreign key (permiso_id)
        references adm_seg_permiso (permiso_id) on delete cascade,
    constraint uk_rol_permiso unique (rol_id, permiso_id)
);

create index idx_rol_permiso_permiso on adm_seg_rol_permiso (permiso_id);

comment on table adm_seg_rol_permiso is 'Permisos asignados a roles';

-- >>> apps/adm/database/tables/adm_seg_usuario.sql
-- =============================================================================
-- Tabla : adm_seg_usuario
-- App   : adm | Módulo: seg
-- Desc  : Usuarios únicos para TODAS las aplicaciones.
--         tipo_autenticacion:
--           LOCAL -> contraseña propia (hash + salt en esta tabla)
--           SSO   -> autenticado por proveedor externo (OCI IAM / Google / MS),
--                    aquí solo se controla estado y autorización.
--         Las contraseñas NUNCA se guardan en claro.
-- =============================================================================
create table adm_seg_usuario (
    usuario_id              number generated by default on null as identity,
    username                varchar2(100)  not null,
    email                   varchar2(200)  not null,
    nombres                 varchar2(100)  not null,
    apellidos               varchar2(100),
    tipo_autenticacion      varchar2(10)   default on null 'LOCAL' not null,
    password_hash           raw(64),
    password_salt           raw(32),
    debe_cambiar_password   varchar2(1)    default on null 'S' not null,
    fecha_cambio_password   timestamp,
    intentos_fallidos       number(3)      default on null 0 not null,
    fecha_ultimo_login      timestamp,
    empresa_id_defecto      number,
    estado                  varchar2(1)    default on null 'A' not null,
    creado_por              varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion          timestamp      default on null systimestamp not null,
    modificado_por          varchar2(100),
    fecha_modificacion      timestamp,
    constraint pk_adm_seg_usuario primary key (usuario_id),
    constraint fk_admgenempresa_admsegusuario foreign key (empresa_id_defecto)
        references adm_gen_empresa (empresa_id),
    constraint uk_usuario_username unique (username),
    constraint uk_usuario_email unique (email),
    constraint ck_usuario_username_mayus check (username = upper(username)),
    constraint ck_usuario_tipo_autenticacion check (tipo_autenticacion in ('LOCAL','SSO')),
    constraint ck_usuario_password_local check (tipo_autenticacion <> 'LOCAL' or password_hash is not null),
    constraint ck_usuario_debe_cambiar check (debe_cambiar_password in ('S','N')),
    constraint ck_usuario_estado check (estado in ('A','I','B'))
);

comment on table  adm_seg_usuario        is 'Usuarios centrales de todas las aplicaciones';
comment on column adm_seg_usuario.estado is 'A=Activo, I=Inactivo, B=Bloqueado (intentos fallidos)';

-- >>> apps/adm/database/tables/adm_seg_usuario_rol.sql
-- =============================================================================
-- Tabla : adm_seg_usuario_rol
-- App   : adm | Módulo: seg
-- Desc  : Roles asignados a usuarios, opcionalmente por empresa y con vigencia.
--         empresa_id null = el rol aplica a todas las empresas.
-- =============================================================================
create table adm_seg_usuario_rol (
    usuario_rol_id      number generated by default on null as identity,
    usuario_id          number         not null,
    rol_id              number         not null,
    empresa_id          number,
    fecha_desde         date           default on null trunc(sysdate) not null,
    fecha_hasta         date,
    creado_por          varchar2(100)  default on null coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
    fecha_creacion      timestamp      default on null systimestamp not null,
    modificado_por      varchar2(100),
    fecha_modificacion  timestamp,
    constraint pk_adm_seg_usuario_rol primary key (usuario_rol_id),
    constraint fk_admsegusuario_admsegusuariorol foreign key (usuario_id)
        references adm_seg_usuario (usuario_id) on delete cascade,
    constraint fk_admsegrol_admsegusuariorol foreign key (rol_id)
        references adm_seg_rol (rol_id),
    constraint fk_admgenempresa_admsegusuariorol foreign key (empresa_id)
        references adm_gen_empresa (empresa_id),
    constraint uk_usuario_rol_empresa unique (usuario_id, rol_id, empresa_id),
    constraint ck_usuario_rol_vigencia check (fecha_hasta is null or fecha_hasta >= fecha_desde)
);

create index idx_usuario_rol_rol     on adm_seg_usuario_rol (rol_id);
create index idx_usuario_rol_empresa on adm_seg_usuario_rol (empresa_id);

comment on table adm_seg_usuario_rol is 'Roles por usuario (y por empresa) con vigencia';

-- >>> apps/adm/database/tables/adm_aud_login.sql
-- =============================================================================
-- Tabla : adm_aud_login
-- App   : adm | Módulo: aud (Auditoría)
-- Desc  : Bitácora de intentos de inicio de sesión (exitosos y fallidos).
-- =============================================================================
create table adm_aud_login (
    login_id            number generated by default on null as identity,
    username            varchar2(100)  not null,
    resultado           varchar2(20)   not null,
    apex_app_id         number,
    ip_cliente          varchar2(50),
    fecha               timestamp      default on null systimestamp not null,
    constraint pk_adm_aud_login primary key (login_id),
    constraint ck_login_resultado check (resultado in ('OK','PASSWORD_INVALIDO','USUARIO_NO_EXISTE','BLOQUEADO','INACTIVO','SIN_ACCESO'))
);

create index idx_login_username_fecha on adm_aud_login (username, fecha);

comment on table adm_aud_login is 'Bitácora de inicios de sesión';
